sul-dlss/preservation_catalog

.gitignore
Gemfile
Gemfile.lock
app/controllers/moab_storage_controller.rb
config/application.rb
config/routes.rb
spec/controllers/moab_storage_controller_spec.rb

The idea was to get a very basic (crude, even) show action working so we could split out tickets to do additional work - I believe this PR achieves that.
I have indicated spots in the code that I know need more attention, and created github issues for them.  Please leave a comment if you see more things that we need to change.
@SaravShah helped with this.
I included some other refactoring which I can split out into a separate PR if you deem it worth the trouble.
Resolves #12

show action initial implementation

---

.rubocop.yml
app/controllers/catalog_controller.rb
config/routes.rb
spec/controllers/catalog_controller_spec.rb

* add a CatalogController, which updates the Object Inventory Store (i.e. takes client requests and manipulates the database, based on the contents of moab objects on the file system).
* routes and tests for CatalogController
* change a couple rubocop defaults to allow common departmental practices
this is a first pass at implementing #45.  at the very least, it will require updating `CatalogController#moab_size` to get the actual moab size once sul-dlss/moab-versioning#21 is implemented.  for the purposes of getting a start on this, we've hardcoded a dummy value.
this assumes for now that callers to PCC will either ask to add a record for a moab to the object inventory store, or update an existing record, but that the caller will already know whether the object moab is cataloged in the …

update catalog for a single druid

---

app/controllers/moab_storage_controller.rb
app/models/preserved_object.rb
spec/controllers/moab_storage_controller_spec.rb

Show action now shows object size of the moab directory. 
Note: Didn't add tests for private methods, since they're pretty simple and are used in public methods.
Note2: Another way to test object_size instead of using `be_between` maybe use the `\du`unix command and use the directory size number from there to compare.
paired w/ @jmartin-sul

Moab object size method in show action

---

README.md
config/database.yml

Fixes #59 
The deploy failed due to discrepancies between `database.yml` and puppet. It's possible to keep `preservation_core_catalog`, and change the username/db in puppet, and I'm open to that, but we can save ssh keystrokes with a shorter username.

Switch db credentials for dev

---

spec/models/preserved_object_spec.rb

Given that more tests will find their way into this spec file, I thought it made more sense to refactor the tests under a "validation" context.  I also tried to distinguish between required and optional attributes, and fixed a spec that was only partially written.

preserved_object_spec: refactor to prepare for more tests

---

.rubocop.yml
app/models/endpoint.rb
app/models/endpoint_type.rb
app/models/preservation_copy.rb
app/models/preservation_policy.rb
app/models/preserved_object.rb
app/models/status.rb
db/migrate/20170907215045_add_details_to_endpoints.rb
db/migrate/20170907215505_remove_status_from_preservation_copies.rb
db/migrate/20170907215849_create_statuses.rb
db/migrate/20170907234425_add_status_to_preservation_copies.rb
db/migrate/20170908000116_create_endpoint_types.rb
db/migrate/20170908000316_remove_endpoint_type_from_endpoint.rb
db/migrate/20170908000340_add_endpoint_type_to_endpoint.rb
db/migrate/20170908203419_create_preservation_policies.rb
db/migrate/20170908204701_create_endpoints_preservation_policies.rb
db/migrate/20170908214803_remove_preservation_policy_from_preserved_objects.rb
db/migrate/20170908214835_add_preservation_policy_to_preserved_object.rb
db/schema.rb
spec/models/endpoint_spec.rb
spec/models/endpoint_type_spec.rb
spec/models/preservation_copy_spec.rb
spec/models/preservation_policy_spec.rb
spec/models/preserved_object_spec.rb
spec/models/status_spec.rb

this is an attempt to implement the schema improvements outlined in #46.  paired w/ @SaravShah on the implementation.
i'd initially figured i'd squash everything into one commit, but i was actually able to separate things out into somewhat logical groupings of changes that built on one another.  unfortunately, we were a bit messy about committing our WIP, and we did all the test updates after the implementation.  so while i'd ideally like each commit to be a working build, that's unlikely to be the case, since some of the test fixes were clumped together.  the different chunks of the schema migration and their accompanying model changes are pretty well grouped, though, hopefully.  happy to do more commit squashing or splitting if people have suggestions, and will try to be better about …

schema updates

---

README.md

Adding ```postgres``` to ```psql -f db/scripts/pcc_setup.sql postgres``` and ```psql -f db/scripts/preservation_core_catalog_setup.sql postgres```

add postgres to rake commands

---

README.md

Just noticed we had the rails boilerplate text and it was time for it to go away.

README.md: replace boilerplate text somewhat

---

Gemfile.lock

The shoulda-matchers gem we're using was not working for me because I think Gemfile.lock was pointing to a commit that is problematic. This PR hopefully fixes the problem.
As a side-effect, I hope this will get rid of the warning:
"The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.4.
To update, run gem install bundler --pre"
as this also changes our bundler version to be a regular release rather than a pre-release. There are also some fairly minor updates of other gems that I hope will be OK.

Update Gemfile.lock with working shoulda-matchers

---

lib/benchmarking/checksum_testing.rb
lib/benchmarking/postgres_testing.rb

Closes #96 
The results are here:
https://docs.google.com/spreadsheets/d/1_gCiXPSYd-abElPzDDUuU_wy0IAV2Rhk4uz-qQjRYGo/edit#gid=0
Basically, changing the size of the input file buffer has no real effect on execution time. The original 3-checksum implementation from
https://github.com/sul-dlss/moab-versioning/blob/2beb8ed8448c5a3952e75bd80a59ecf897ab154f/lib/moab/file_signature.rb#L144-L163
as tested here, is CPU-bound. Consider the following ruby-prof output snippet, generated by running the script on a 2.1G file:
```
%self      total      self      wait     child     calls  name
72.50    167.637   167.637     0.000     0.000  5758599   Digest::Base#update
23.93     55.319    55.319     0.000     0.000  1919534   IO#read
2.33    231.182     5.396     0.000   225.787        1 …
```

Benchmarking script for calculating checksums

---

app/controllers/catalog_controller.rb
app/controllers/moab_storage_controller.rb
app/models/moab_storage_directory.rb
config/application.rb
config/initializers/moab_config.rb
lib/benchmarking/checksum_testing.rb
lib/benchmarking/moab_enumeration_testing.rb
lib/benchmarking/postgres_testing.rb
spec/models/moab_storage_directory_spec.rb

the `MoabStorageDirectory` class offers a couple of methods that allow storage root traversal and listing.  each takes a directory that contains a druid tree (such as a storage trunk in a storage root).
`.find_moab_paths` will allow the caller to pass in a block, which will then get the `druid`, `path`, and `MatchData` object as parameters for each druid under the specified directory.  `.list_moab_druids` provides a convenient wrapper around this method, and just returns a list of all druids in the given directory.
closes #67

enumerate moabs in directory

---

.gitignore
.rubocop.yml
app/models/preserved_object.rb
app/services/preserved_object_handler.rb
spec/models/preservation_copy_spec.rb
spec/models/preserved_object_spec.rb
spec/services/preserved_object_handler_spec.rb

Service for heaving lifting for existence check from online Moab storage_roots to PCC db.  Has logic for update/create of PreservedObject as indicated by comparison of online Moab object's current version (and size) with what is in PCC db.
Idea is that controller can do:
```ruby
po_handler = PreservedObjectHandler(druid, version, size)
results = po_handler.update_or_create
```
and look at details in results to determine what HTTP response to send.
Additionally, code on the same machine could instantiate `PreservedObjectHandler` directly and avoid the overhead of the HTTP call.
Connected to #65 
Closes #90 (what to do when storage root moab is older than db)
Closes #81  (when to update size)
Implemented the most basic interpretation of method to update db table entry:
if entry already …

PreservedObjectHandler service

---

app/models/preservation_policy.rb

Fixes #135 
Arguably, existing specs cover the additional validations -- there's one to check that
PreservationPolicy.new is not valid, for example.

validate that ttl fields are only integers greater than zero

---

spec/lib/audit/moab_to_catalog_spec.rb

- merged in a rush, didn't rebase off master (sorry) and had to update the storage_dir used in RSpec tests.

Update storage_dir to new storage path

---

.rubocop.yml
Gemfile
Gemfile.lock
lib/audit/catalog_to_moab_existence.rb
spec/lib/audit/catalog_to_moab_existence_spec.rb
spec/load_fixtures_helper.rb
spec/models/endpoint_spec.rb
spec/models/endpoint_type_spec.rb
spec/models/preservation_copy_spec.rb
spec/models/preservation_policy_spec.rb
spec/models/status_spec.rb
spec/rails_helper.rb

Wrote an rspec "shared context" https://relishapp.com/rspec/rspec-core/docs/example-groups/shared-context to allow easy loading of our fixture moabs into the test db for specs.
Also:
- ensures that tests are run with test db seeded (added to rails_helper)
- adjusts model specs affected by ^^
- bare beginnings of catalog to moab existence check code (useful for "testing" the load_fixtures_helper "shared context" ... and next work to do!)
Closes #149 (fixture moabs put in test db)
Connected to #108 (catalog to moab existence check)

helper to load moab fixtures into catalog; always seeds test db for specs 

---

lib/audit/moab_to_catalog.rb

To avoid looking at storage roots unnecessarily, instead of 
```ruby
current_version = Stanford::StorageServices.current_version(druid)
```
do 
```ruby
moab = Moab::StorageObject.new(druid, object_dir)
moab_version = moab.current_version_id  # this should be cheaper as it instantiates fewer objects to get version number
```
connects #167

refactor the way in which we get current version of a moab

---

spec/rails_helper.rb

Remove 
```
Rake::Task["db:migrate"].invoke
Rake::Task["db:seed"].invoke
```
and add
```
Rake::Task["db:reset"].invoke
```
``` rake db:reset``` drops, creates, migrates and seeds the db.
connects #169

Add db:reset rake task

---

app/models/preserved_object.rb
app/services/preserved_object_handler.rb

instead of using ``` /\A[a-z]{2}\d{3}[a-z]{2}\d{4}\z/``` we can use ```DruidTools::Druid.pattern```
connects #133

change druid regex to use druid-tools

---

app/models/preservation_policy.rb
db/migrate/20171011142253_add_index_to_preservation_policies.rb
db/schema.rb
spec/models/preservation_copy_spec.rb
spec/models/preservation_policy_spec.rb
spec/models/preserved_object_spec.rb
spec/services/preserved_object_handler_spec.rb

Using `default` as the same `preservation_policy_name` across different specs was making rspec try to create more than one `preservation_policy` object whose name was `default`, triggering the uniqueness validation, so my workaround was to make the name unique to each spec.
Resolve #137

make preservation_policy_name unique and indexed

---

.rubocop.yml
Gemfile
Gemfile.lock
app/services/preserved_object_handler.rb
lib/audit/moab_to_catalog.rb
lib/benchmarking/moab_to_catalog_testing.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/services/preserved_object_handler_spec.rb

* remaining TODO
closes #183
closes #157
closes #131
closes #180

split `PreservedObjectHandler#update_or_create` into separate `#update` and `#create` methods

---

lib/audit/moab_to_catalog.rb
lib/benchmarking/moab_to_catalog_testing.rb
spec/lib/audit/moab_to_catalog_spec.rb

the first commit does what's described in the associated issue.
the second commit is a handful of small touchups to the script that does performance profiling on `MoabToCatalog.check_existence` (née `check_moab_to_catalog_existence`).  those were pretty easy fixes, so i went ahead and did them while i was there.  hopefully uncontroversial, but if they're distracting, i'm happy to put them in a separate PR with an associated ticket (or to discard them altogether if people think they're a bad idea).  i tested that script a bit, and it seems to still work fine after the changes (though i didn't test the profiling stuff, since that was commented out).
closes #202

rename MoabToCatalog.check_moab_to_catalog_existence to check_existence

---

.rubocop.yml
Gemfile.lock
lib/audit/moab_to_catalog.rb
spec/lib/audit/moab_to_catalog_spec.rb

Use more efficient way to get the size of a moab object directly from Moab::StorageObject.
Resolves #206

moab_to_catalog: get size more efficiently

---

spec/load_fixtures_helper.rb
spec/models/endpoint_type_spec.rb
spec/models/preservation_copy_spec.rb
spec/models/preservation_policy_spec.rb
spec/models/preserved_object_spec.rb
spec/models/status_spec.rb

for endpoint_type_spec, the tests seemed clearer to me when I put the EndpointType.create in the 3 tests relying on it, rather than the "let" statement.
I believe this resolves #126 (replace inline created test fixtures with seeded objects) as much as is appropriate.
Also resolves #139 - we don't need to use 604800 as the ttl value in our specs, and that is the only place (besides settings.yml) where that value is used.

Remove inline test fixtures

---

.rubocop.yml
lib/audit/moab_to_catalog.rb
spec/lib/audit/moab_to_catalog_spec.rb

besides creating the seed_catalog method, I adjusted the logic in the check_existence method to only create the object if expect_to_create is true (and object doesn't already exist).
Resolves #201
Resolves #204

moab_to_catalog split out check_existence vs seed_catalog

---

config/settings.yml
config/settings/development.yml
config/settings/test.yml

Fixes #217 
This seems like a bit of a hack but it does get the fixtures out of the settings object -- I'm open to discussing better approaches.

Get settings for fixture storage roots out of the way of shared_configs

---

spec/lib/audit/moab_to_catalog_spec.rb

Without requiring rails_helper, I'm unable to run the moab_to_catalog tests on their own (i.e. without running the entire test suite). This is just a convenience PR.

Require rails_helper so we can run moab_to_catalog_spec on its own.

---

.rubocop.yml
app/services/preserved_object_handler.rb
lib/audit/moab_to_catalog.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/services/preserved_object_handler_spec.rb

helper method `#update_per_version_comparison` becomes `#confirm_version_on_db_object` (paired w/ @tingulfsen)
connects to #221 
Note that travis fails on rubocop, and it is due to WIP on update_version work.

turn #update into #confirm_version

---

.rubocop.yml
app/services/preserved_object_handler.rb
lib/audit/moab_to_catalog.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/services/preserved_object_handler_spec.rb

this splits out the version updating for ingest robots and such from the version confirmation for audit checks and such.
closes #181
closes #197
closes #211
closes #218
closes #221
much pairing and branch wrangling with @tingulfsen and @ndushay.

split POH #update into #update_version and #confirm_version

---

app/services/preserved_object_handler.rb

issue #225: PreservedObjectHandler#update_db_object should just return a result list, instead of taking one as a param and appending to it.
issue #240:  switch to using Array#concat instead of Array#<< for joining result lists from helper methods to running result lists in the caller.
see https://ruby-doc.org/core-2.4.0/Array.html#method-i-3C-3C and https://ruby-doc.org/core-2.4.0/Array.html#method-i-concat
closes #225
closes #240

(PC) PreservedObjectHandler result handling

---

app/services/preserved_object_handler.rb
spec/load_fixtures_helper.rb
spec/models/preserved_copy_spec.rb
spec/services/preserved_object_handler_spec.rb

This corrects the conflation of default_status (used at create time only) and "ok" status (used in other logic to indicate "ok")

Status ok vs default

---

Rakefile

Fixes #68
The new rake task is only for seeding the catalog, so maybe break out the rest of the ticket into a new ticket or two?
If anyone knows how to avoid adding the line to application.rb then feel free to amend this branch as you please.

A basic rake task to seed the catalog from all the storage roots.

---

app/services/preserved_object_handler.rb
spec/services/preserved_object_handler_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

looks like more methods will be repeating this pattern, so i took a shot at centralizing it to a method that takes a block and does the error handling.  that part is in the third commit (and required no spec changes).
also, a couple other bits of minor housekeeping (which did require a bit of spec touchup).

centralize common ActiveRecord rescue behavior in PreservedObjectHandler

---

config/deploy.rb

i'm not sure if we want to do this, but it's something that we do in other projects, and i noticed just now when deploying that we don't do it in preservation catalog.  seemed easier to put up this PR and have people reject it if we don't want it than to file an issue and all, since it's such a simple change.

automatically update shared_configs upon deployment

---

Gemfile
lib/audit/moab_to_catalog.rb
lib/profiler.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/lib/profiler_spec.rb

- lifted `ruby-prof` out of development gem group, to deploy it
- auto-loaded paths in lib, which made it possible to invoke the profiler in a console
- added a profiler that outputs `FlatPrinterWithLineNumbers` (other output options are available)
- added a profiled version of `seed_from_disk` and specs for it
- should probably add specs for the Profiler class
closes #290

Add profiler and version of seed_from_disk using it

---

app/services/preserved_object_handler.rb
spec/services/preserved_object_handler_create_spec.rb

- Added a flag in the `create_db_objects()` method to run the timestamp update for ` create_with_validation` and not for `create` 
- we want to update PC.last_checked_on_storage and PC.last_audited for `create_with_validation`
- I figured that this was a good idea because I have access to the `PreservedCopy` in the `create_db_objects()` method and wouldn't have to use a `.find_by` call. 
connects #288

Update pohandler.create/validations timestamps

---

app/services/preserved_object_handler.rb
db/seeds.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb

since that method is already wrapping high-level groups of DB operations which go together to form what should be a single atomic update
test transactions by forcing one part of the database updating to fail, after the prior step has succeeded, and check that the prior step was rolled back.
* the first commit is just a bit of log message clean up that i couldn't resist
* the second adds transactionality to the initial database seeding of endpoints etc
* the third is a bit of refactoring that sets up
* the fourth, which just adds transactionality to the method that already wraps high-level sets of DB operations
my plan is to put up a follow-on PR that maybe fleshes out the tests for this a bit more (#324), as well as adding a `db/README.md` (#281) which gives a bit of basic guidance about …

transactionality in POH: rename with_active_record_rescue to with_active_record_transaction_and_rescue, have it wrap its yield in a transaction

---

Gemfile.lock

this will hopefully allow us to get past the objects considered invalid due to versions missing content directories.

use moab-versioning v3.0.0

---

.rubocop.yml
README.md
Rakefile
lib/audit/moab_to_catalog.rb
spec/lib/audit/moab_to_catalog_spec.rb

this contains some unticketed touchups that seemed like the right thing to do while i was in there, and felt like they wouldn't be conflict-y with the WIP based on the waffle board when i was looking at it this afternoon.  hopefully not too controversial, happy to break up into something more conservative if people would prefer.  broke into logical commits, but also hopefully not too painful to review all at once.
* minor fixes for accuracy to catalog seeding documentation (#332)
* fix require statements (#333)
* slightly more descriptive name for seeding profiling log file
* turn MoabToCatalog instance methods into class methods to make it all consistent across the class
* clearer names for loop vars
* rake seed_catalog task: flush output to stdout in a more timely fashion
* …

Moab to catalog touchups

---

.rubocop.yml
README.md
Rakefile
lib/audit/catalog_to_moab.rb
lib/audit/moab_to_catalog.rb
lib/benchmarking/moab_to_catalog_testing.rb
lib/profiler.rb
spec/lib/audit/catalog_to_moab_spec.rb
spec/lib/audit/moab_to_catalog_spec.rb

our moab_to_catalog method names were almost the opposite of what I expected.  Do folks think this is an improvement?

rename seeding and check_existence methods to be clearer

---

lib/audit/moab_to_catalog.rb
spec/lib/audit/moab_to_catalog_spec.rb

- Removed ``` PreservedObject.exists?(druid: druid) ``` from ```MoabToCatalog.seed_catalog_for_dir(storage_dir) ``` because ``` PreservedObject.exists?(druid: druid) ``` is called in ``` PreservedObjectHandler#create_after_validation ``` 
- Removed / changed corresponding spec tests
- connects #311

remove duplicate PreservedObject.exists? from M2C.seed_catalog_for_dir

---

config/settings.yml

we don't need it clogging up space (and grep results) on our local implementation, IMHO.

turn off provenance logging for development

---

.rubocop.yml
app/services/preserved_object_handler.rb
spec/services/preserved_object_handler_update_version_spec.rb

Implements `#update_version_after_validation` method in PreservedObjectHandler.
Also added FIXME notes in #confirm_version implementation methods.
closes #283 
closes #287

PreservedObjectHandler.update_version_after_validation implemented

---

.rubocop.yml
Rakefile
lib/audit/moab_to_catalog.rb
spec/lib/audit/moab_to_catalog_spec.rb

- I'm deleting all PreservedCopies that have an endpoint_name of whatever you specify
- Then i'm deleting the rest of the orphan PreservedObejcts
- Had to do this weird syntax in `moab_to_catalog_spec.rb` lines 259-264
```
begin
subject
rescue
end
```
If anyone knows how to get around this, I would like to know!
- Also, should I add a `puts` statement that says something like `Congrats you deleted all the data off #{endpoint_name}` ?
closes #342

 rake task to drop specific storage root

---

db/migrate/20171204215532_add_status_to_preserved_copies.rb

The problem and solution this addresses is documented here: https://www.viget.com/articles/adding-a-not-null-column-to-an-existing-table
The migration would run locally (because of an empty table), but wouldn't run on prod during a capistrano deployment, because the table was populated.
Fixes #376

Refactor migration to allow it to run when the table is populated

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb

HONEYBADGER_API_KEY and HONEYBADGER_ENV are configured in puppet as environment variables, to save us from maintaining an extra shared config file
Fixes #32

Install and configure honeybadger

---

.rubocop.yml
app/models/preservation_policy.rb
app/services/preserved_object_handler.rb
db/seeds.rb
spec/load_fixtures_helper.rb
spec/models/endpoint_spec.rb
spec/models/preservation_policy_spec.rb
spec/models/preserved_copy_spec.rb
spec/models/preserved_object_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb

i went with caching the id for the default preservation policy, instead of caching the whole active record object.  this felt safer to me -- my gut feeling left me slightly leery of caching a whole AR object, i know ActiveJob advises users to pass around job IDs instead of job objects (which are often activerecord objects underneath if e.g. delayed_job is used), and users on stack exchange etc advised against caching active record objects.  we only need the id anyway, since either the id or the object can be used to set the association.  as a bonus, this is a slightly lighter thing to cache, but i'd guess that's pretty negligible.
the cache eviction is naive, as pointed out in the comments, but i think it'll be performant enough, with as infrequently as we'd expect to add pres policies. …

default PreservationPolicy caching

---

.rubocop.yml
app/services/preserved_object_handler.rb
app/services/preserved_object_handler_results.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

This shortens PreservedObjectHandler by about 100 lines (from about 400 to about 300).
Closes #327

PreservedObjectHandler: refactored results and logging into separate class

---

app/models/preserved_copy.rb
app/services/preserved_object_handler.rb
db/README.md
spec/models/preserved_copy_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb

~~NOTE: this is WIP, because we should merge #369 first, and then rebase this on master.  though i have rebased this on the branch used by #369, under the assumption that it'll get merged in something pretty similar to its current form.~~
* a bit of re-arrangement so that like things are grouped contiguously
* a slightly more conventional approach to enum usage
* db/README.md: fix for accuracy now that PreservedCopy.status is an enum
* slightly more thorough #status validation tests
closes #373

enums touchups

---

Rakefile

closes #391 (branch name is wrong 👎 )
When I started the prod run yesterday I thought it would be more clear if I got a statement saying that the "Seeding has started" for those especially large roots
before:
``` 
preservation_core_catalog 353-add-statement ⚡  rake populate[fixture_sr1]                        
You're about to populate all the data for fixture_sr1. Are you sure you want to continue? [y/N]
y
You have successfully populated all the data for fixture_sr1
```
after:
```
preservation_core_catalog 353-add-statement ⚡  rake populate[fixture_sr1]                        
You're about to populate all the data for fixture_sr1. Are you sure you want to continue? [y/N]
y
Starting to populate db for fixture_sr1
You have successfully populated all the data for fixture_sr1
```

Add puts statement

---

spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb

noticed a second spot in pohandler_confirm_version_spec  to improve the timestamp update tests;  then went looking for other spots and just ended up tweaking some comments/descriptions in one other file.

Improve timestamp specs

---

app/models/preserved_copy.rb
app/services/preserved_object_handler.rb
spec/load_fixtures_helper.rb
spec/models/preserved_copy_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb

Since the "default" status in PreservedCopy was essentially a stand in for "validity unknown", I revised the code to have a distinct status for "validity unknown" and removed the "default" status.
Note that no db migration needed because a value was added to the status enum, but no existing values were changed.
- Resolves #409 (status when creating missing catalog entry)
- Resolves #371 (add scary warning about changes to PreservedCopy.status enum)
- bonus: gets rid of a copy pasta comment that annoyed @tingulfsen

Validity unknown status

---

app/services/preserved_object_handler.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

At the moment, this is the ultimate in shameless green implementation.
Do we want to:
- merge it as is and make a separate ticket to refactor?
- refactor check_exist as part of this PR?
- move on to more pressing concerns?
Resolves #424
Review advice:   look at the commits separately

fix M2C.check_exist bug when disk version < catalog version

---

app/services/preserved_object_handler.rb
db/migrate/20171220010020_add_audit_timestamps_to_preserved_copies.rb
db/schema.rb
spec/models/preserved_copy_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

~~WIP until #437 is merged;  then this will be rebased on master.~~
PreservedCopy datestamps:
- last_moab_validation
- last_version_audit
replace:
- last_audited
- last_check_on_storage
To allow us to distinguish between these two types of audit checks.  This was discussed here:  https://github.com/sul-dlss/preservation_catalog/pull/432#discussion_r157886007
I tried to break up the commits so it would be somewhat manageable for review.  The truth is after the db migration, the specs won't pass without all these commits.  :-P
Resolves #434

Improve audit timestamps

---

.rubocop.yml
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_results_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

Initial approach for #455;  
Better testing for PreservedObjectHandlerResults allows us to reduce test code for PreservedObjectHandler
(this grew out of Naomi writing a few tests to ensure that seeding the catalog would report errors to dor workflows)
Connected to #455

Test results not behavior

---

.rubocop.yml
Gemfile
Gemfile.lock
app/services/preserved_object_handler.rb
app/services/preserved_object_handler_results.rb
app/services/workflow_errors_reporter.rb
config/settings.yml
config/settings/development.yml
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_results_spec.rb
spec/services/shared_examples_preserved_object_handler.rb
spec/services/workflow_errors_reporter_spec.rb
spec/spec_helper.rb

Incorporated it into the PreservedObjectHandler.report_results method. 
Wrote RSpec tests using WebMock. 
Only have two workflow steps, `'moab-valid' and 'pc-process'` The `'pc-process'` name is just all other errors other than `PreservedObjectHandlerResults::INVALID_MOAB` so if there is another name we should use, let me know.
connects to #404 
(Travis fails will be fixed in follow on PR)

Implemented the workflow services rest call to send error messages to preservationWF.

---

lib/audit/catalog_to_moab.rb

fixes an issue caused by PR #459 adding some code that used the old log_results method, which was replaced by report_results (in the subsequently merged but previously started PR #454)

fix calls to log_results (by making them calls to its successor report_results)

---

app/services/preserved_object_handler.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

~~pretty close, added new tests, still need to:~~
paired with @tingulfsen for most of this.
supersedes #438 
closes #431
closes #433

Check existence revalidates on bad status

---

lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_spec.rb

Catches up on the missing specs for `lib/audit/catalog_to_moab.check_catalog_version`
One question:  should `check_catalog_version` take a storage_dir argument and avoid the endpoint lookup for each preserved_copy object?   Or should the argument go away and code stay as is?
Resolves #479
🎉 upped our coverage to 97% with this!  w00t!

add specs for existing C2M.check_catalog_version method

---

lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_class_spec.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb

shall we have 2 reviewers on this before merge??
This avoids all sorts of annoyances later.
Note that I envision that all methods besides `check_catalog_version` will be private ... but we can cross that bridge in other PRs.
Note further that I envisioned a large file for specs, so I split it ...

catalog_to_moab: use an instance for #check_catalog_version

---

app/models/preserved_copy.rb
lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/models/preserved_copy_spec.rb

- adds a method on preserved_copy to check the version agains its preserved_object current_version. I picked that location instead of the po_handler, since preserved copy is handed into `check_catalog_version`.
- implements the new method inside of `check_catalog_version` with an `if` statement that adds results to the handler (includes a new code for when versions match)
- specs for the new method
Connects to #483
(#483 is finished when the code in this PR is called from `C2M.check_catalog_version` )

Add method to match pc version against its po current version

---

app/services/workflow_errors_reporter.rb
spec/services/workflow_errors_reporter_spec.rb

When we sent this errorMessage:
`"PreservedObjectHandler(bp534qj1626, 7, 12877062629, services-disk02) Invalid moab, validation errors: [\"Version directory name not in 'v00xx' format: original-v1\"]"` 
- Ruby didn't escape the quotes, the errorMessage didn't have parsable structure when a PUT request was sent.
- WorkflowService responded with a 400 bad request.
- Wrote RSpec test to test this. 
- We discovered this in prod, but was reproducible in stage.
paired w/ @tallenaz @jmartin-sul

HTML Escape text in error message sent to workflow

---

.rubocop.yml
app/services/preserved_object_handler.rb
lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb

2 reviewers, please.
- I duplicated 3 methods, more or less, from `POHandler` in `CatalogToMoab`.  In our streamlined, shameless green, critical path work only, this felt expeditious and didn't even conflict with Sandi Metz ("hold your nose, duplicate code ... for the 2nd and 3rd times ... then refactor")
- I did a wonderful job of calling it out with comments
- I finished implementing the work from PR #477 (PR #489), actually calling the pres_copy methods now that they exist.
- I got all OCD and alphabetized the rubocop exceptions ...
Fixes #491
Fixes #489

catalog_to_moab.check_catalog_version: implement case of catalog_version > moab_version

---

lib/audit/catalog_to_moab.rb

"[C2m] is just a check to see that the Moab directories actually exist. Nothing fancy" - Julian
- Audit requirement on C2M is correct and there is nothing beyond "does moab exist?" and "is the version what we expect" 
- PR removes TODO comment `# TODO: original spec asks for verifying files???? read audit requirements`
closes #481

Remove unnecessary comment regarding audit requirements after checking with Julian

---

app/services/preserved_object_handler.rb

Found this small refactor while working on another issue
Saves some keystrokes, and a reference to pres_object

Use pres_copy.matches_po_current_version? where we can

---

spec/services/preserved_object_handler_results_spec.rb
spec/services/shared_examples_preserved_object_handler.rb
spec/services/workflow_errors_reporter_spec.rb

2 reviewers?  Beats me.
- specs that ensure we call `WorkflowErrorsReporter.update_workflow` as appropriate
- implemented rest of public method specs for `POHandlerResults` class (preparatory for #528, #509 and #455)
- fixed a typo in a spec description
- removed vestigial comments in a shared_examples spec
Closes #385
Connects to #455 
Connects to #528

pohandler_results_spec revisions

---

.rubocop.yml
app/services/audit_results.rb
app/services/preserved_object_handler.rb
lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/services/audit_results_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

~~WIP: to be reviewed after #530 is merged~~
AuditResults is the new name for PreservedObjectHandlerResults
Closes #512

AuditResults is the new name for PreservedObjectHandlerResults

---

app/services/workflow_errors_reporter.rb
spec/services/workflow_errors_reporter_spec.rb

Only needs 1 set of eyes. 
Rails.logger.warn to Rails.logger.error, so we can get notified when these requests don't go through. They shouldn't happen often.
closes #502

Turn Rails.logger.warn to Rails.logger.error in workflow_errors_reporter

---

app/services/audit_results.rb

1 reviewer?
Closes #428
The motivation is to make it easier for us to understand the results when debugging.

audit_results: use symbols for codes instead of integers

---

app/services/audit_results.rb
app/services/preserved_object_handler.rb
lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/services/audit_results_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

- audit_results
- remove incoming_size as it's not doing anything for us here
- renamed "incoming_version" to "actual_version" so it applies beyond POHandler
- removed some FIXME and TODO lines that are no longer needed -- do you agree with me?
Connects to #539

AuditResults: renamed "incoming_version" to "actual_version"

---

.rubocop.yml
app/services/preserved_object_handler.rb
lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb

since this adds its own `preserved_copy#save!` call, which also happens in #519 and #525, so those should probably get merged first, and then this should get rebased.
assumed similar behavior to `PreservedObjectHandler#check_existence`.
paired w/ @SaravShah
closes #480

C2M#check_catalog_version: handle pres copy status status already bad

---

app/models/preserved_copy.rb
app/services/preserved_object_handler.rb
lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/models/preserved_copy_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

this is branched off of c2m-handle-pc-status-already-bad from PR #526, because that PR includes a comment that references one of the statuses being removed here (because it ripped off a method from POH that did the same, also fixed in this PR).  so we should merge that PR and rebase this one on master before merging it (hence the WIP).
closes #372

Remove duplicate checksum validation failure statuses

---

.rubocop.yml
app/services/audit_results.rb
app/services/preserved_object_handler.rb
lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/services/audit_results_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

2 reviewers?
3 reviewers so everyone understands the changes??
~~WIP until #544 is merged;  then will rebase this on master~~
~~WIP until caller is in log msg_prefix ...~~
- audit_results:  
- msg_prefix only in logs, not result messages
- add check_name attribute so it can be included in log msg_prefix
- specs:  use better var names for audit_results object
Connects to #539

Audit results msg prefix

---

.rubocop.yml
app/models/preserved_copy.rb
config/settings.yml
lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_class_spec.rb
spec/models/preserved_copy_spec.rb

Extracts the SQL query from check_version_on_dir into PreservedCopy
This made writing the spec more straightforward
Adds a spec on c2m to test that sql orders objects differently
depending on last_version_audit timestamp
To get the spec running we saved the preserved_copy, though
we haven't agreed on the best way of saving the pc
The spec seems a bit fragile in the way it uses timestamps in
method calls
Paired with @jmartin-sul 
Closes #476 but shouldn't be merged until we get further along with how to save the preserved_copy in `check_catalog_version`, which connects this to #478 
Closes #537

Refactor to spec for ordering in c2m SQL query

---

app/services/audit_results.rb
app/services/preserved_object_handler.rb
spec/services/audit_results_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

(again, probably everyone should see this)
AuditResults constant names were confusing me:
- "OBJECT" referring to db vs. moab.
- "actual" which I neglected to migrate to the constants
- THE_INCREDIBLY_LONG_NAMES_I_WROTE_WERE_BOTHERING_ME
Connects to #539

audit_results: constant names made less confusing and shorter

---

lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb

When we remove the unexpected_version result, rspec complains:
```
expected: (:unexpected_version, "PreservedCopy")
got: (:actual_vers_gt_db_obj, "PreservedCopy") (1 time)
(:actual_vers_gt_db_obj, "PreservedObject") (1 time)
```
The two `actual_ver` messages seem sufficient. Fixes #484

De-dup results when catalog_version < moab_version

---

.rubocop.yml
Rakefile
app/models/preserved_copy.rb
lib/audit/catalog_to_moab.rb
spec/models/preserved_copy_spec.rb

- probably only needs 1 pair of eyes
- adds .normalize_date(timestamp) so last_checked_b4_date can either be a Time object, String, or nil.
- RSpec tests for this method
- ~~Rubocop exception~~
closes #485

Date format

---

app/services/audit_results.rb

closes #516 
It took me a while to come up with these names. Let me know if you have better suggestions.
- Not sure about `CHECKSUM_MISMATCH => "The checksums for %{file1} does not match. Computed %{algorithm} checksum: %{computed_checksum}. Expected checksum: %{expected_checksum}",` 
- If there are multiple mismatchs for md5, sha1, or sha256 would we have to send an error result separately for each one?

 add CV errors to result handler

---

lib/audit/checksum.rb
spec/lib/audit/checksum_spec.rb

Fixes #572 
Should just need 1 pair of eyes, granted that the approach discussed in #572 is acceptable to all.

Reduce duplication in lib/audit/checksum class

---

db/migrate/20180218003253_add_index_to_db_dates.rb
db/schema.rb

2 reviewers?
It turns out we have been using updated_at when we query the db for timings and state via the rails console.
So far we've only used `PreservedCopy.updated_at` in those queries, by and large, but I thought we might play it safe.  Happy to index fewer fields with this PR if there's a reason not to index.  (Performance concerns?)
Closes #442
If we deploy to stage and prod with cap, this migration will happen appropriately.  No db data manipulation needed.

db migration to index po and pc created_at and updated_at dates

---

lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb

The reason we didn't get any log messages for the error we were deliberately triggering in production was:
- the `PreservedObject` current_version was updated, but not the `PreservedCopy` version
- the code trapping for version mismatch wasn't calling `report_results`.
This PR address the second problem.
Connects to #548

C2M reports results when there is a version mismatch

---

.rubocop.yml
lib/audit/catalog_to_moab.rb
lib/audit/moab_to_catalog.rb

Since I've been perusing logs for info for our new stats chart, I discovered that we had no beginning and ending markers when we ran a check for a single root.  This PR fixes this oversight.
1 reviewer, unless anyone has strong opinions about directory names vs root names showing up in output.

seeding, m2c, c2m: better output

---

app/services/audit_results.rb
app/services/preserved_object_handler.rb
spec/services/audit_results_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

- DB_OBJ_DOES_NOT_EXIST result is NOT reported to workflows (it's not really an error)
- DB_OBJ_DOES_NOT_EXIST result is a WARN in rails logs, not ERROR
- also tweaked msg sent to workflows, as there should be no separator between the workflows prefix and the first error message, and the separator '&&' makes more sense than '||'.
- removed some of the duplicate log messages
FIxes #584
Connected to #410

Object creation is not an error

---

.travis.yml
Gemfile

Created a gem group :not_travis which is now excluded (along with :deploy and :development groups) when running travis specs.
Came across this tip while setting up travis for sul-dlss/preservation_robots

create :not_travis group of gems to allow travis builds to go faster

---

.travis.yml
Gemfile
Gemfile.lock

PR #588 (merged) was a bust, as the gems in the :not_travis group were NOT loaded in development or production environments.   This is because bundler loads "default" gems in no group, then the gems in the group matching the "environment" (test, development, production).  
PR #589 is also a bust, in that the new_relic gem is installed by travis.
This PR should allow everything to work as it should.

put newrelic_rpm in production gem group and remove not_travis group

---

spec/lib/audit/catalog_to_moab_instance_spec.rb

adds a MOAB_NOT_FOUND result

---

.rubocop.yml
README.md
Rakefile
lib/audit/checksum.rb
spec/lib/audit/checksum_spec.rb

- Made it so methods took `endpoint_name` instead of `storage_dir` to be more synonymous to c2m and m2c checks. 
- removed `algorithm` as a parameter since it is not used.
- Updated README with the given changes
connects #578

Checksum validate disk all endpoints

---

.rubocop.yml
app/models/preserved_copy.rb
lib/audit/catalog_to_moab.rb
spec/lib/audit/catalog_to_moab_class_spec.rb
spec/models/preserved_copy_spec.rb

~~on hold for a bit since we aren't working on checksum validation quite yet (i just happened to be playing with scopes and this query at the end of the day last friday).  just making a PR so we can easily link the branch to the issue it addresses.~~
adds `fixity_check_expired`, and a couple utility scopes for filtering pres copies by endpoint.  also refactors an existing scope to use the new endpoint filter scope (`by_storage_location`) instead of taking a storage location param itself.
closes #515

(CV) PreservedCopy scopes: fixity_check_expired, and related minor refactoring

---

.rubocop.yml
README.md
Rakefile
app/services/preserved_object_handler.rb
lib/active_record_utils.rb
lib/audit/catalog_to_moab.rb
lib/audit/checksum.rb
spec/lib/active_record_utils_spec.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/lib/audit/checksum_spec.rb

* CV: profiling output should use name of profile method in file name like similar M2C and C2M methods (also fix tests and documentation)
* centralize some re-useable activerecord code
* have C2M use transactions when it does updates that should be grouped atomically
TODO:
fine to do any of those things in this ticket or in follow on tickets.
also, i know utility classes are a thing some people don't like.  happy to hear suggestions for a better approach, though i think this is better than rewriting the code in this PR multiple times across different classes that need to do very similar things.
~~this is now rebased on #606, which should get merged first (because this will refactor a thing from that PR).~~
closes #609 
closes #573

miscellaneous polish (shared ActiveRecord helper methods, readme, log file names)

---

lib/audit/checksum.rb
spec/lib/audit/checksum_spec.rb

- Logging this to tell users: If the druid inputted came up with 0 pre copies log this as an error. We are 
expecting at least 1 preserved copy for a given druid.
- I can change it to 
` Rails.logger.debug("Found #{pres_copies.size}.")` as a general statement too, without the conditional.

Remove unnecessary interpolation in Checksum.validate_druid

---

Rakefile
app/models/endpoint.rb
app/models/host_settings.rb
config/initializers/moab_config.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml
lib/audit/catalog_to_moab.rb
lib/audit/checksum.rb
lib/audit/moab_to_catalog.rb
spec/lib/audit/catalog_to_moab_class_spec.rb
spec/lib/audit/checksum_spec.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/load_fixtures_helper.rb
spec/models/endpoint_spec.rb
spec/models/host_settings_spec.rb

- HostSettings class (with specs) gets storage_roots for the host configured in `storage_root_map`
- Replaces calls to `Settings.moab.storage_roots` with `HostSettings.storage_roots`
- Adds `storage_root_map` to settings
Paired with @atz and @jmartin-sul 
Early on, `HostSettings.storage_roots` was memoized, but then the test environment would use the laptop's hostname instead of the `default` host configured in `storage_root_map`.  No memoization worked with the existing tests, options for maintaining memoization seemed ugly, so I think of this as a shameless green PR.
I tested this out on a live deployment to the new prod server, and verified that `HostSettings.storage_roots` returns the same roots configured in `shared_configs`.
Maybe needs only one pair of eyes.
Closes #617

HostSettings specifies storage_roots by hostname for sharding

---

Rakefile
app/services/audit_results.rb
lib/audit/checksum.rb
spec/lib/audit/checksum_spec.rb
spec/services/audit_results_spec.rb

* invalid usage of Rake tasks should return non-zero error code 
* AuditResults: add method for detecting whether results include a given code
* AuditResults: add #to_json method and test 
* non-zero exit code from cv_druid rake task if validation fails for any examined pres copy
closes #633

proper unix exit codes for rake tasks

---

.rubocop.yml
app/controllers/catalog_controller.rb
config/routes.rb
spec/controllers/catalog_controller_spec.rb

This is just a first pass PR to see what other devs think and if they have any thoughts on what I should change. 
`catalog_controller.rb` - `def create` method w/ the http_status return codes. Thought it would be useful if we returned useful http codes...I can change them to other http codes if someone doesn't like them.  I added these codes because I was getting a 204 (no content) return code whether success or failure of object creation. 
`audit_results.rb` - `contains_result_code?(code)` is used by `CatalogController#create` ( PR John put up I merged into my branch)
connects #109

[WIP] Create route ReST Calls (first pass)

---

Gemfile.lock
config/initializers/moab_config.rb
config/settings.yml
spec/services/checksum_validator_spec.rb

1st Commit is some RSpec refactoring that was done during code club w/ @atz. I can separate this out into another commit if wanted.
2nd Commit contains moab-versioning update and adding the configurable checksum w/ RSpec tests.
( I can move the whole`context 'checksums are configurable' do..` bock into the `context #validate_checkums' do` block if wanted as well. )
ad hoc paired w/ @jmartin-sul  for 2nd commit.
closes #663

Selectable checksum test

---

Gemfile
Gemfile.lock
app/models/preserved_copy.rb
config/initializers/okcomputer.rb
spec/lib/okcomputer_spec.rb
spec/rails_helper.rb
spec/support/okcomputer_check_matcher.rb

- RSpec matchers from okcomputer
- use `spec/support` dir for add'l test scaffolding
- Amend activerecord scope to accept `ActiveSupport::TimeWithZone` objects, which are of course compatible with ActiveRecord querying. These are returned by statements like `2.days.ago`.
Fixes #574

Introduce okcomputer, 2 types of checks and tests to match

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

This connects w/ https://github.com/sul-dlss/preservation_robots/pull/54/commits/2745cbb633464c07d446654fa52ec4965b20ffcd
`Preservation_Robot` couldn't extract an `endpoint_name` however, we could find the `storage_location` of the object. 
Update all `endpoint_name` to `storage_location` in the `catalog_controller` w/ RSpec tests.

Change how we find endpoint bc of pres_robot

---

spec/rails_helper.rb

The tasks are loaded by `load_tasks`, so we know Rake is already available.

Remove unnecessary require statement

---

config/application.rb
lib/audit/catalog_to_moab.rb
lib/audit/checksum.rb
lib/audit/moab_to_catalog.rb
spec/lib/audit/catalog_to_moab_class_spec.rb
spec/lib/audit/checksum_spec.rb
spec/lib/audit/moab_to_catalog_spec.rb

Previously, code was calling both `Rails.logger` (to file) and `puts` (to `STDOUT`) with the same messages.  I consolidated those lines by having a single logger that outputs to both.
This cleans up:
- the code
- our test output, by keeping the `puts` statements from firing during `rspec` or CI

Logger chain

---

config/application.rb

The configuration attribute didn't exist w/o loading the railtie, resulting in a `NoMethodError` (only in production environment).

Allow `config.active_job` to succeed in production.rb

---

app/models/host_settings.rb
config/settings.yml
spec/models/host_settings_spec.rb

Add baseline empty storage_root_map to Settings.yml and provide failover.
Because the lookup is based on system name, we should anticipate that it will be invoked on systems not yet present in the configuration (even if that is a dev system). Returning an empty hash is preferable to raising an uninformative `NoMethodError`.

Host settings robustness

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

Robots sends druid as `druid:xx000xx0000`. preserved_object_handler needs the druid in `xx000xx0000` format. So remove `druid:` by using split.

normalize inputs to controller

---

app/services/checksum_validator.rb
app/services/preserved_object_handler.rb
spec/lib/profiler_spec.rb
spec/load_fixtures_helper.rb

Inside `app` everything is auto/eager-loaded by Rails, so you never need to explicitly require anything else that lives inside `app`.
The way `lib` is invoked most typically is via `autoload_path` or in pure Ruby, `ruby -I ./lib` or the `RUBYLIB` ENV var. So components should be available to each other if naming conventions are followed.
We don't actually follow naming conventions fully (e.g. `Checksum` is not in an `Audit` module), *but* for referencing peers in the same directory that doesn't matter.

Reduce unnecessary requires

---

README.md
config/deploy.rb

Adds a capistrano task to call seed_catalog
and perform it after migrations on a deploy
Fixes #736

Add db:seed to cap

---

config/initializers/config.rb

This follows what we did w/ Hyku and greatly enhances flexibility.
See: https://github.com/railsconfig/config#fine-tuning
Example usage, overriding `Settings.zip_storage` for a single process without changing the YAML file or code:
```
SETTINGS__ZIP_STORAGE=foobar be rails c
[1] pry(main)> Settings.zip_storage
=> "foobar"
```
This is just using the core functionality of the Rails `config` gem, but setting it up for bash instead of Heroku.

Allow individuals settings to be overridden via (bash) ENV

---

Gemfile
Gemfile.lock
app/jobs/endpoint_delivery_base.rb
app/jobs/s3_endpoint_delivery_job.rb
app/lib/preservation_catalog/s3.rb
app/models/druid_version_zip.rb
config/settings.yml
spec/jobs/integration_spec.rb
spec/jobs/s3_endpoint_delivery_job_spec.rb
spec/lib/preservation_catalog/s3_spec.rb
spec/models/druid_version_zip_spec.rb

- uses the current `aws-sdk-s3` gem
- non-activerecord model for `DruidVersionZip` for logic around zipfiles
- basic S3 configurations/invocations consolidated to a handful of class methods
- placeholder metadata (including md5) posted with S3 object, future work will tie in the checksum from TCR or equivalent
I will follow up with live-S3 integration testing in a separate PR.
Fixes #710

Aws worker

---

lib/audit/checksum.rb

While trying to reproduce status ok to unexpected version on storage, thought this would help as to why if you run cv twice w/in a short period of time - you will probably not find any PC's

add logging to checksum.validate_disk

---

app/services/checksum_validator.rb
spec/services/checksum_validator_spec.rb

When status is set to `PreservedCopy::UNEXPECTED_VERSION_ON_STORAGE`, we want to log more information than just the status information. We want to also long the corresponding `AuditResults::UNEXPECTED_VERSION` message.
closes #752

Additional logging for when we change status 

---

spec/controllers/catalog_controller_spec.rb

Via the `#create` and `#update` ReST calls in the `catalog_controller`, the `druid` parameter should be allowed to take in either `druid:xx000xx0000` or `xx000xx0000`.
Change `druid` to `prefixed_druid` and `druid_no_pre` to `bare_druid` - better variable naming
Closes #729

catalog controller can take druid with or without prefix

---

spec/lib/preservation_catalog/s3_spec.rb

Separately, Ops will take care of establishing a policy for the **test** bucket that includes, e.g., the automatic removal of every object after 24 hours.

Fixes #777: Avoid S3 collisions during near-simultaneous live S3 tests

---

app/models/preserved_copy.rb
app/models/zip_checksum.rb
db/migrate/20180517220356_create_zip_checksums.rb
db/schema.rb
spec/factories/zip_checksum.rb
spec/models/preserved_copy_spec.rb
spec/models/zip_checksum_spec.rb

Create new table that will store the `md5` checksum for each archive zip created. Table contains `md5`, `create_info` - which will have the shell command and OS info under which the zip was created), and the `preserved_copy_id` (preserved_copies has many zip_checksums)
Also introduce zip_checksum factory as the last commit, but the `zip_checksum_spec.rb` uses it before hand.
closes #754

Zip checksum table

---

config/deploy/stage.rb
config/initializers/resque.rb
config/resque.yml
config/routes.rb
config/settings.yml
config/settings/development.yml

Previous discussion at https://github.com/sul-dlss/preservation_catalog/pull/761
This adds resque config files to wire the app up to redis/resque, and restricts the resque dashboard to what we specify via a setting. 
If the settings approach is agreeable, I'll have PRs in to shared configs that set up the resque dashboards in stage/prod

Add resque config and add routes for dashboard

---

app/models/endpoint.rb
app/models/endpoint_type.rb
app/models/preserved_copy.rb
app/models/preserved_object.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml
db/README.md
db/migrate/20180518175719_remove_access_key_from_endpoints.rb
db/migrate/20180518180326_remove_recovery_cost_from_endpoints.rb
db/schema.rb
db/seeds.rb
spec/factories/endpoint.rb
spec/models/endpoint_spec.rb
spec/models/endpoint_type_spec.rb
spec/models/preserved_copy_spec.rb
spec/models/preserved_object_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb

still needs:
i'd also like to:
closes #713

Target archive endpoints

---

app/models/endpoint.rb

This fixes cap production deploys while we are in a state where the database accommodates archive endpoints, but our config data has none.

endpoint: add guard clause for no archive_endpoints configured

---

spec/services/workflow_errors_reporter_spec.rb

Doing assignments to `Settings` in tests is an anti-pattern because it requires undoing them later or invisibly side-effecting the rest of the suite.
Side note: one of the tests calling only `request_params` was under the `.update_workflow` description.

Fix order dependence and mistaken nesting in workflow_errors_reporter_spec

---

app/jobs/zipmaker_job.rb
spec/jobs/zipmaker_job_spec.rb

Fixes #707 
paired with @SaravShah on rspec, with some of @ndushay 's help 
This PR assumes a zip storage file system layout that doesn't include the bucket name, and may need some team discussion to decide whether it's correct.
The form of the zip command draws from https://github.com/sul-dlss/preservation_catalog/issues/737#issuecomment-388504059

Add code, fixture, spec for zipmaker worker

---

README.md
Rakefile
lib/audit/moab_to_catalog.rb
spec/lib/audit/moab_to_catalog_spec.rb

In cleaning up some objects (see #814), it became obvious that we will need a rake task to run M2C for a single druid.  I wrote it so that it could be hooked up to a ReST call, if desired (See #630).
Closes #815

way to run M2C for single druid

---

app/services/audit_results.rb

I found this a bit tortured:
```
E, [2018-06-02T05:01:34.619074 #12833] ERROR -- : check_catalog_version(yf454wt8752, services-disk12) This check is unable to validate an incoming status of invalid_checksum
```
So I changed it to 
```
E, [2018-06-02T05:01:34.619074 #12833] ERROR -- : check_catalog_version(yf454wt8752, services-disk12) unable to validate when PreservedCopy status is invalid_checksum
```

audit_results: tweak error messages

---

app/services/checksum_validator.rb
spec/services/checksum_validator_spec.rb

Fixes #688 
I'm open to adding to tests, if they seem insufficient, say, for a change in timestamp value, or testing that timestamps don't get updated in the else condition.

Update more timestamps in checksum validator

---

app/services/moab_validation_handler.rb
app/services/preserved_object_handler.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

otherwise, status can be set to any errors that may have been found (e.g. `'invalid_moab'`, `'unexpected_version_on_storage'`), or `'validity_unknown'` if e.g. no errors were found but checksum validation wasn't run.
closes #690

only set ok status if all validations (incl CV) have passed

---

app/models/preserved_copy.rb
app/services/checksum_validator.rb
lib/audit/checksum.rb
spec/lib/audit/checksum_spec.rb
spec/services/checksum_validator_spec.rb

- Ensure that our existing CV check only affects online PreservedCopy objects.
Additional refactors
- checksum_validator.new takes pres_copy as single argument
- fix checksum_validator_spec so it can be run alone (@atz does this improve random order issues?)
supersedes the M2C and C2M part of PR #823
Connected to #778

CV - ensure it is only for online pres_copies

---

app/jobs/zipmaker_job.rb
spec/jobs/zipmaker_job_spec.rb

Makes error reporting work.  As a bonus, one less unused variable.

Fix #844: Zip util outputs "errors" on STDOUT

---

Gemfile
Gemfile.lock
app/services/workflow_errors_reporter.rb
config/initializers/dor_workflow_service.rb
config/settings.yml
spec/controllers/catalog_controller_spec.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/lib/audit/checksum_spec.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/services/audit_results_spec.rb
spec/services/checksum_validator_spec.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/workflow_errors_reporter_spec.rb

Fixes #809 
- installs and configures `dor-workflow-service`
- replaces a lot of homegrown faraday code with a call to `dor-workflow-service`, with a spec (for a method that unexceptionally returns `true`)
- adds to `Settings` (would be nice to get the actual workflow service URL out of there)
- makes other specs aware of the `dor-workflow-service` call

Use dor-workflow-service for rest calls

---

lib/tasks/resque.rake

Note: because of #842, attempting to run `rake resque:work` will crash from an unrelated dependency (okcomputer) problem, but this is required both for the point where we've fixed that, or for the workaround of targeting just the `resque.rake` file directly (not loading `Rakefile`).

Make resque's rake tasks available

---

lib/profiler.rb
spec/lib/profiler_spec.rb

`Time.current` relies on Rails, but this `lib` class doesn't have any guarantee of Rails being loaded. Here I convert the call to use only the functionality available from the un-enhanced Ruby class.
This resolves a test order-dependency and test-independence failure (the spec could not previously run in isolation).
Would you prefer not to have 200 log files leftover by running specs on your local machine?  Me, too. I also made the test clean up after itself.
Fix #728

Fix #728 profiler_spec: no rails, do cleanup, order independence

---

README.md

This might be overkill, but I wanted to be as explicit as possible. 
~~This PR builds off of Joe's PR #727 , because of the `require 'audit'` part. I'll put this PR in WIP for now.~~ 
- rebased off master, which includes the `Audit::` Namespace (#727)
- Please let me know if i'm missing anything.
connects #833

Add Audit Check Usage via Console to README

---

app/jobs/zipmaker_job.rb
app/models/druid_version_zip.rb
spec/jobs/zipmaker_job_spec.rb
spec/models/druid_version_zip_spec.rb

- Move last auxiliary method from zipmaker to DruidVersionZip
- Handles chdir for zip creation
- Handles `mkdir -p` for zip destination directory
- Performs `touch` on existing zip file to prevent premature cleanup
Fix #849
Fix #845

Fix zipmaker bugs and gaps

---

app/lib/audit/catalog_to_moab.rb
app/lib/audit/checksum.rb
app/lib/audit/moab_to_catalog.rb
lib/profiler.rb
spec/lib/profiler_spec.rb

Fixes half of #869
Add method for simple one-liner invocation of profiler.  This reduces the need to have bespoke one-off methods that shadow regular methods for the purpose of profiling them. Whatever calls them (e.g. rake task) can now just invoke `Profiler.print_profile` itself.
Converts `Profiler` invocations in `Audit` module.  This is a setup for externalizing each `xxx_profiled` method to the place where it is called (seems like each is called in only one place).  (The second half of #869).  
After all, it shouldn't be the business logic for a class _how_ a given method is going to be profiled (or which are profilable).

Profiler oneliner

---

app/services/preserved_object_handler.rb
spec/services/preserved_object_handler_spec.rb

Ensure that our existing M2C and C2M checks only affect *online* PreservedCopy objects, using @jmartin-sul 's the elegant solution.
supersedes the M2C and C2M part of PR #823
Connected to #778

M2C, C2M: ensure they are only for online pres_copies

---

app/services/preserved_object_handler.rb

address oversight when I wrote code to ensure pohandler methods were always dealing with online pres_copies (see #836)

pohandler: remove redundant check for online pres_copy

---

app/services/checksum_validator.rb
spec/services/checksum_validator_spec.rb

MoabValidationHandler already does what we want here.
`full_druid` isn't used anywhere anymore.

Follow-up removal of unnecessary method and attribute

---

app/models/preserved_object.rb
db/migrate/20180511210539_noramlize_druid_name.rb
spec/models/preserved_object_spec.rb

This method existed to correct previously inserted data (druids w/ prefixes), but it has served its purpose and is no longer needed.  The more comprehensive validation ensures that no more druid prefixes can be inserted (i.e. the method will never be needed again).
This also helps because one of the tests for the removed method was silently invalid: was catching generic `raise_error`, but the actual exception was coming from the mock, not the model!
Fixes #893

Replace normalize_druid_name with more accurate validation

---

app/models/preserved_object.rb
spec/models/preserved_object_spec.rb

Create the preserved_copies through PreservedObject. No need to do `preserved_object: self`. 
Also the active record `create!` has transaction-ality, so you don't need to add another transaction here.

Re-write #create_archive_preserved_copies

---

lib/tasks/c2m_tasks.rake
lib/tasks/cv_tasks.rake
lib/tasks/m2c_tasks.rake

A follow-up after looking at rake tasks from Naomi's PR.
While maybe flushing is required internal to a task, it is not going to help anything at the end of a task, where the job is about to complete anyway.
Also standardized some log language ("done" was more common, instead of "finished") and corrected singular/plural language.

Remove unneeded explicit flush calls

---

.rubocop.yml
README.md
app/lib/audit/checksum.rb
spec/lib/audit/checksum_spec.rb

Fixes #914 (easy way to run CV for objects with certain status on certain storage root)
Connects to #912 (confirm workflow errors cleared by M2C, C2M) as it will make it really easy to test that for a significant number of druids.

Cv by root by status

---

config/deploy.rb

Fixes #891 
For example, we want the latest endpoint data from shared_configs before the db is seeded.

deploy: update shared_configs before migrating db

---

app/models/preserved_copy.rb
spec/models/preserved_copy_spec.rb

- use the same `pc` in tests, i.e. focus on what is **different** per test
- use factories when possible
- convert comment to formal YARD doc and adjust method param to comply w/ documented expectation
These commits were originally from last week, branched off of the `10_gb` branch, now rebased on master.

Touchups to PC spec and some YARD

---

config/deploy.rb

Because there was no symlink set to resque.yml in `shared_configs`.
Fixes #928

Why isn't resque picking up the redis url?

---

spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

These refactorings, which should be easy to review, were done to clear the way to adding an argument to some of the pohandler methods.  @jmartin-sul did some of them.
We need to add the argument for #817 - robots creating/updating preserved copies with status ok (instead of invalid_checksum).  I have a branch in progress for that but it still needs more love

Pohandler spec refactor

---

Gemfile
Gemfile.lock
config/resque-pool.yml
lib/tasks/resque.rake

This allows configuration of the number of workers to service each queue (by name).
Run with the (example) `resque-pool.yml` config:
```
$ bundle exec rake resque:pool
resque-pool-worker[preservation_catalog][6079]: Starting worker DN0a286.SUNet:6079:checksum_validation
resque-pool-worker[preservation_catalog][6080]: Starting worker DN0a286.SUNet:6080:checksum_validation
resque-pool-worker[preservation_catalog][6081]: Starting worker DN0a286.SUNet:6081:checksum_validation
resque-pool-worker[preservation_catalog][6082]: Starting worker DN0a286.SUNet:6082:endpoint_events
resque-pool-worker[preservation_catalog][6083]: Starting worker DN0a286.SUNet:6083:endpoint_events
resque-pool-worker[preservation_catalog][6084]: Starting worker DN0a286.SUNet:6084:endpoint_events …
```

Introduce resque-pool

---

app/models/druid_version_zip.rb
spec/models/druid_version_zip_spec.rb

Add DVZ methods #parts and #expected_parts.  Because we will only be able to store the **count** of parts in the S3 metadata, we need a way of reconstructing what filename is expected to correspond to part X of N, or the whole set of N filenames, as here.
This logic will be utilized after workers are converted subsequent to the PC model split.

DruidVersionZip logic for chunks

---

app/lib/audit/catalog_to_moab.rb
app/lib/audit/moab_to_catalog.rb
app/services/audit_results.rb
app/services/checksum_validator.rb
app/services/preserved_object_handler.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/services/audit_results_spec.rb

- For c2m/cv, direct check output to the c2m/cv logger via an argument to `report_results`
- For m2c, add a logger to poh constructor, and override it to point to the m2c logger
- `report_results` ultimately logs by a call to the `add` method of `Logger`, because the `log` method will not broadcast messages to both STDOUT and another logger.
- spec touchups to show poh receiving a logger override, and the calls to `add`
Fixes #858

Let m2c,c2m,cv write to their own logs

---

config/schedule.rb

Testing in prod indicates that using the
current date will return all preserved copies
Fixes #959

Let c2m check more than no preserved copies

---

.rubocop.yml
app/models/archive_endpoint.rb
app/models/archive_preserved_copy.rb
app/models/endpoint.rb
app/models/preserved_copy.rb
app/models/preserved_object.rb
db/seeds.rb
spec/models/archive_endpoint_spec.rb
spec/models/preserved_copy_spec.rb

ported and fixed the query, and added a test which would've demonstrated issue #899.
still need to:
i think the tentative plan is to get #956 merged, then #954, then this.
fixes #899

Fix archive pres copy creation (depends on #956, #954)

---

.rubocop.yml
app/lib/audit/catalog_to_moab.rb
app/services/preserved_object_handler.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

We need this so robots can set catalog entries to "ok" status when they update catalog, since they do checksum validation of the new content.  This is the guts of that work.  Still need to adjust controller and then the robot code.  (See #817)
- pohandler.create and .update_version methods take an optional param to indicate if checksums have already been validated for the new moab (or new version for the moab).   Note that the addition of this param created all sorts of additional complexities re:  what status we should set in a variety of circumstances. (see table below)
- moved a block of tests out of shared_examples because it was only used in one of the update_version contexts and it was no longer correct.
- updated some tests to use rspec change matcher ... because I was having a …

Pohandler methods take checksums_validated param

---

spec/lib/audit/catalog_to_moab_class_spec.rb
spec/lib/audit/catalog_to_moab_instance_spec.rb
spec/lib/audit/checksum_spec.rb
spec/services/checksum_validator_spec.rb

- Silence spammy log output during tests
- Minor refactor for reuse, associations and `find_by!` in test setups for consistency and reliability
Note that the CI for this PR is not cluttered with 500 lines of log output in the middle of the "green dots".

Quiet tests

---

.rubocop.yml
Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/prod.rb
config/deploy/stage.rb
lib/capistrano/tasks/capistrano-resque-pool.rake

The commands we were using from `capistrano-resque-pool` spun up a single pool of workers with no additional knowledge of their environment. The `resque-pool` service on the worker machines, however, spins up 3 pools of workers, where two of the pools have environment variables assigned telling them which credentials and buckets to use to replicate to. This PR intends to mirror the sevice set up through custom capistrano rake tasks, based off of what is in `capistrano-resque-pool`.
Happily, with this PR, objects make it all the way through the replication pipeline consistently across deployments.

Custom capistrano for resque-pool

---

spec/load_fixtures_helper.rb

ActiveRecord transactional test context means it is undone anyway.
These setups would probably be better represented via factories.

This custom "undoing" of fixture data is redundant

---

app/lib/audit/moab_to_catalog.rb
spec/lib/audit/moab_to_catalog_spec.rb

When calling `Audit::MoabToCatalog.check_existence_for_druid('db102hs3456')` with a druid that doesn't exist, the method errors out with a `TypeError` because when we pass in `moab.size` to the `po_handler` it calls this method: 
```
def size
size = 0
Find.find(object_pathname) do |path|
size += FileTest.size(path) unless FileTest.directory?(path)
end
size
end
```
If the path does not exist, then calling `size` will give `TypeError: no implicit conversion of Pathname into String`
closes #953

Fix TypeError when running M2C for a druid

---

app/jobs/plexer_job.rb
app/lib/audit/moab_to_catalog.rb
app/models/preserved_copy.rb
app/models/preserved_object.rb
app/models/zipped_moab_version.rb
spec/factories/zipped_moab_versions.rb
spec/jobs/integration_spec.rb
spec/jobs/plexer_job_spec.rb
spec/jobs/results_recorder_job_spec.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/models/preserved_copy_spec.rb
spec/models/zip_endpoint_spec.rb
spec/models/zip_part_spec.rb

This mostly required revision of some bulky tests' expectations.
Note: 10GB cap on `replicate!` now removed!
Next phase would include handoff to replication after ZMV rows are created.

Replication trigger (part 1): auto-filling DMZ's on PC creation

---

app/models/preserved_copy.rb
app/models/zipped_moab_version.rb
spec/jobs/application_job_spec.rb
spec/jobs/zipmaker_job_spec.rb
spec/models/preserved_copy_spec.rb
spec/models/zipped_moab_version_spec.rb
spec/rails_helper.rb

Added `replicatable_status?` to PC to encapsulate logic about whether it is OK to push dependent objects into pipeline.
`replicate!` doesn't raise, because that would make us unable to create PCs with non-replicatable statuses (since that auto-creates ZMVs) or ZMVs from such PCs.  Method is public on the anticipation of audit processes that might also invoke it directly.
Closes #989

Replication trigger (part 2, take 2): auto-hook replication

---

app/models/zipped_moab_version.rb
spec/models/zipped_moab_version_spec.rb

just being a little OCD about return types here.
feel free to close if this feels silly or counterproductive.  seemed better to merge #1018 than to hold it up over this, and it wasn't really harder to put up a PR than it was to file a ticket describing the issue.

have ZippedMoabVersion#replicate! guard clause return nil instead of false, for consistent return types

---

app/models/druid_version_zip.rb
spec/models/druid_version_zip_spec.rb

Closes #1034 
This should help `open3` from deadlocking due to generating too much output

Make zip command output less verbose

---

spec/jobs/results_recorder_job_spec.rb
spec/models/zip_part_spec.rb

```
context 'when some parts for zip_endpoint are replicated' do
it 'does not set parent zipped_moab_version status to ok' do
skip
end
end
```
- Moved this test to the the zip_part model to test the actual method that is doing this.
```
zmv.ok! if part.all_parts_replicated? # are all of the parts replicated for this zip_endpoint?
```
closes #967 
closes #964

Additional rspec tests for ResultsRecorderJob and ZipParts

---

app/jobs/s3_west_delivery_job.rb
spec/jobs/s3_west_delivery_job_spec.rb
spec/lib/preservation_catalog/s3_spec.rb

This prevents us having to worry about closing the filehandle, which is something explicitly recommended in the S3 docs.

Pass file_path to upload_file instead of open filehandle

---

config/schedule.rb
config/settings.yml
spec/models/complete_moab_spec.rb

- Use the `CV.validate_disk_all_storage_roots`  Rake task and run it every week. 
- The fixity time is now 90 days instead of 1 week. Didn't change the `archive_ttl` but added the question to StoryTime on whether or not we should change that too.
- Need to double check this runs smoothly.
closes #868 
closes #649

Schedule cv

---

config/initializers/resolv_replace.rb

The default Socket.getbyhostname and other libc-bound DNS resolutions in Ruby block the entire VM until they complete.  In a single thread this doesn't matter, but it can cause competition and deadlock in multi-threaded environments.  `resolv-replace` is included as part of Ruby to swap out the libc implementation for `resolv`, a thread-friendly pure ruby version.  It is a monkey-patch, but obviously one provided and supported by the Ruby maintainers themselves.

Use pure-ruby DNS resolution for thread-safety

---

Gemfile
Gemfile.lock

There have been many releases in recent months including several bugfixes around memory allocation and filehandle closing on file upload, including:
- `Ensure file handlers are closed when an exception is raised in Aws::S3::FileUploader`
See: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/CHANGELOG.md#1170-2018-07-11

Update amazon SDK

---

.rubocop.yml
app/models/preserved_object.rb
app/services/preserved_object_handler.rb
spec/services/preserved_object_handler_check_exist_spec.rb
spec/services/preserved_object_handler_confirm_version_spec.rb
spec/services/preserved_object_handler_create_spec.rb
spec/services/preserved_object_handler_update_version_spec.rb
spec/services/shared_examples_preserved_object_handler.rb

Small revisions to app code:
- `PO#complete_moabs` gets `autosave: true`
- 2 "getter" methods go public in POH
- associations are used to find and create
- keep non-transactional code outside the transaction block
Larger revisions to tests:
- remove unnecessarily eager `let!` statements
- associations are used to find and create
- intercept POH `pres_object` and `complete_moab` directly when desirable, rather than go underneath it to intercept the model's `.find_by!`
- use `change` matcher
- use imperative enum calls (e.g. `cm.ok!`)
Rebased to make mergeable after PC renaming.

POH use more OO, especially in specs

---

.travis.yml
README.md
spec/rails_helper.rb

This practice seems to have derived from having non-rails_helper'd code writing to the database, as with our old `./lib` directory.  It is unnecessary for anything using rails_helper, however, which now includes all the code that writes to the DB during tests.
We already have transactional fixtures turned on so every change during the rspec suite is atomically rolled back at the end of the example where it was made.
Also, we use the fixtures directory, but we don't use it for ActiveRecord fixtures, so that config in rails_helper is misleading.

Stop nuking the DB every time rspec runs

---

spec/models/druid_version_zip_part_spec.rb

Spec tests for `size` and `md5` methods in DruidVersionZipPart class.
Closes #969

Added tests for size and md5 in DruidVersionZipPart 

---

config/deploy/prod.rb
config/schedule.rb

Currently, this would run every hour and delete any files older than 1 day. So the oldest a file would be is 1 day (and 59 minutes). 
This may require further tuning depending on how we choose to enqueue backlog for `ZipmakerJob` or when we have completed the backlog and have different operational expectations for volume of work (i.e. drive less full, files could live longer).
The implication of cache purging is that the zip files must be kept longer than the latency between `ZipmakerJob`'s completion and completion of delivery job(s), inclusive of Plexer latency.  Otherwise the zip file will be deleted before it is delivered.  So any tuning should be measured against performance on those queues.
Closes #1032

Add zip cache cleanup cronjob and capistrano role

---

README.md

Our section on "how to deploy" did not actually describe how to deploy, instead restating the lines from earlier in the file about DB seeding.  Corrected that.
Changed `rake spec` to `rspec` for concision and clarity.  Trivial touchups otherwise.
I don't see anything related to model splitting or renaming that needs to be touched here.
Closes #1054

Mainly changes to Capistrano deploy docs

---

spec/models/complete_moab_spec.rb

Test that `ZippedMoabVersion.count` went from `0` to `3` instead of saying `.eq [ZMV Obj1, ZMV Obj2, ZMV Obj3]`
closes #985

Additional RSpec tests for create_zipped_mv

---

app/jobs/moab_replication_audit_job.rb
app/lib/audit/catalog_to_archive.rb
app/models/complete_moab.rb
app/services/preserved_object_handler.rb
config/deploy/prod.rb
config/schedule.rb
config/settings.yml
db/migrate/20180813235728_add_last_archive_audit_to_complete_moab.rb
db/schema.rb
spec/jobs/moab_replication_audit_job_spec.rb
spec/models/complete_moab_spec.rb

as discussed F2F in the handoff meeting on monday (see #780), this adds a setting that enables/disables automatic backfilling of unreplicated moab versions when the replication audit finds such things.  that flag defaults to disabling the backfill in this PR.  it can be re-enabled when we're in more of a steady state, where we have less of a backlog, or no expected backlog.
also does some other random touchups.
closes #901

moab replication audit scheduling, etc

---

config/initializers/okcomputer.rb

Ops doesn't need to be alerted when no workers are working
And bump up the failure queue threshold

Tweak prescat okcomputer checks

---

config/schedule.rb

Should fix
"/bin/bash: log/zip_cache_cleanup.log: No such file or directory"

Use absolute path to zip_cache_cleanup.log

---

app/models/zip_part.rb
spec/models/druid_version_zip_spec.rb
spec/models/zip_part_spec.rb

use the `ZMV`'s version (instead of `CompleteMoab`'s) when creating `DruidVersionZip` instance, which fixes `s3_key` always ending up with the `CompleteMoab`'s latest version, regardless of that `ZipPart`'s `ZMV` parent's specific version.
also, add test cases that speak to the original oversight.
worked w/ @tallenaz, @atz, and @SaravShah on investigation and writing of new tests.
closes #1088

ZipPart#s3_key and helper #druid_version_zip fixed to generate keys with the appropriate version

---

app/models/preservation_policy.rb
config/settings.yml
db/seeds.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/models/preservation_policy_spec.rb

- We don't want to use `settings.yml` to manage individual database  records
- `default_policy` already has the signature needed for all of our app and tests, just do the `find_or_create!` there
This is one third of the `seed_from_config` that we should continue to excise.

Remove PreservationPolicy.seed_from_config

---

app/models/moab_storage_root.rb
config/schedule.rb

`validate_disk_all_storage_roots` doesn't exist.  The README was already updated to reference `validate_expired_checksums!`, but our actual schedule was not. 
And remove some knowledge of internals of CM validation from MSR layer, using the method `validate_checksums!` instead of knowing what job should be invoked (and with what args).  The same thing is accomplished, but the OO interface is better.
Fixes #1116

Update CV enqueing job in schedule

---

Gemfile
Gemfile.lock
app/models/preserved_object.rb

This is necessary because minor releases add new cops which break the
build. This ensures that minor version bumps are intentional and not the
result of automatic version updates.

Update and pin rubocop

---

config/deploy.rb

Connects to #1122
Now, the first thing cap will do is shut down resque-pool, even before the user chooses which branch, which gives us a chance to check in on the process before the deploy resumes. The start up could be moved ahead at most three steps, if we want.

Give resque-pool more time to restart

---

config/schedule.rb

Problem: We have large zip files that may be old(ish), awaiting md5 creation and shipping to the cloud. By basing our deletion criteria on the age of the zip, rather than the age of md5 sidecar files, we increase the risk that we'll delete zips that are either awaiting md5 creation or are still in the process of being transferred to endpoints. This is especially true for Moabs with > 100 zip parts.
Solution: Look at the creation time of MD5 sidecar files instead; if an md5 sidecar has existed for > 1 day, chances are better that the associated zip file has been successfully uploaded.

Change cleanup logic of sdr-transfers

---

config/schedule.rb

We've seen an issue where very large archives (typically > 200GB) don't finish zipping *and* transferring within 24 hours, resulting in some zip parts being deleted from disk before transfer completes. This leads to incorrect zip_parts being reported for the final .zip file transfer, and may result in an overall failed transfer (expected zip_part not found on disk). 
By increasing mtime to 48hrs we decrease the likelihood of this happening, at the risk of running out of transfer space overall.

Update schedule.rb to increase cache_cleaner mtime

---

config/initializers/okcomputer.rb
config/settings.yml

Our monitor didn't pick up on audit workers being down earlier this week. This check detects the currently configured number of workers in stage and prod, and though it hard codes that number, it's something.
No, since this adds a check on behavior we already assume.

Add okcomputer check to count number of workers

---

config/initializers/okcomputer.rb

not 100% sure this is the right thing to do, but for your consideration...
because it seems like nagios should alert us when the worker count isn't as expected
N/A
closes #1231

make feature-worker-count a required check

---

app/jobs/part_replication_audit_job.rb
app/lib/preservation_catalog/ibm/audit.rb
app/lib/preservation_catalog/s3/audit.rb
app/models/zip_endpoint.rb
config/settings/development.yml
config/settings/test.yml
spec/jobs/part_replication_audit_job_spec.rb
spec/lib/preservation_catalog/ibm/audit_spec.rb
spec/lib/preservation_catalog/s3/audit_spec.rb
spec/models/zip_endpoint_spec.rb

only one of this and #1219 should be merged
to fix the issue with connecting to the IBM endpoint to audit it, per #1189 
this PR allows the audit job to select the audit class specific to the endpoint type.
in implementing #1219 at the end of last week, i realized this could be done without the enum and corresponding DB migration.  and indeed, i think that means we could do the same for the `delivery_class` stuff, which i was initially trying to parallel in this work; looking at the `delivery_class` stuff again, i think we could swap that `enum` for the sort of thing done in this PR, if we like this approach better.  but that's a different can of worms, which we won't open here.  (but happy to file a tech debt ticket to that effect if folks want)
FWIW, when i realized i could do things …

Use correct part audit class

---

app/controllers/application_controller.rb
app/controllers/objects_controller.rb
spec/requests/objects_controller_checksums_spec.rb
spec/requests/objects_controller_object_spec.rb
spec/spec_helper.rb

To provide better information to us (via Honeybadger) and consumers of the API when exceptions occur.  Related to #1229, in that it gives more information about why calling checksum report fails due to missing druids.
n/a

add info to some objects_controller error messages

---

Gemfile.lock
app/controllers/application_controller.rb
app/controllers/objects_controller.rb
app/errors/invalid_suri_syntax.rb

Removes a kludge introduced in PR #1207.   This will also clean up additional objects_controller endpoints that will be leveraging moab-versioning for information ... specifically the ones about to be written to allow us to retired the sdr-services-app.
Note that the following specs continue to pass, given moab-versioning v4.3.0:
- https://github.com/sul-dlss/preservation_catalog/blob/master/spec/requests/objects_controller_checksums_spec.rb#L173-L177
- https://github.com/sul-dlss/preservation_catalog/blob/master/spec/requests/objects_controller_checksums_spec.rb#L190-L194
n/a.

Moab vers update

---

app/controllers/objects_controller.rb
app/services/moab_storage_service.rb
spec/services/moab_storage_service_spec.rb

Additional API endpoints are coming in order to replace the sdr-services-app.  The MoabStorageService class introduced here will contain the code used by the objects_controller to get information about existing Moabs.   
It is possible that some of the audit job functionality could also utilize this new class for its moab lookups, but right now I am concerned only with the API endpoints.
n/a

use MoabStorageService for controllers

---

Gemfile
Gemfile.lock
app/services/workflow_reporter.rb
spec/services/workflow_reporter_spec.rb

The code was calling methods that had been deprecated.
n/a

Stop using deprecated workflow methods

---

app/services/audit_results.rb
app/services/workflow_reporter.rb
spec/services/audit_results_spec.rb
spec/services/checksum_validator_spec.rb
spec/services/workflow_reporter_spec.rb

To stop the "Failed to retrieve resource" errors for non-existent preservationAuditWF, e.g. https://app.honeybadger.io/projects/54415/faults/57642907.
NOTE:  I deployed to stage and tried to test it in situ, but the objects in prescat don't correspond to the objects in dor/argo very well so I gave up.
Closes #1245
n/a

create audit workflow if it doesn't exist

---

.rubocop.yml
app/controllers/objects_controller.rb
app/services/moab_storage_service.rb
config/routes.rb
spec/requests/objects_controller_checksums_spec.rb
spec/requests/objects_controller_content_diff_spec.rb
spec/requests/objects_controller_file_spec.rb
spec/routing/routing_spec.rb
spec/services/moab_storage_service_spec.rb

To replace `cm-inv-diff` endpoint in sdr-services-app.  There will be a `content_diff` method in preservation-client to be used instead of dor-services-app calling sdr-services-app.
Some small refactors added:
- renamed a private method in objects_controller to make the code clearer
- removed unnec lines from request specs
- tweaked a few method comments
Also added more routing specs.  (because I'm compulsive?)
issue #1243 exists for documenting endpoints;  it will be part of the work of the last 2 weeks of December - it's a great one for learning more about preservation.

add objects/content_diff endpoint

---

app/controllers/objects_controller.rb

🎵 "found a typo ... found a typo ... found a typo just now ..." 🎵 
n/a

content_diff comment fix

---

app/jobs/application_job.rb
app/jobs/druid_version_job_base.rb
app/jobs/zip_part_job_base.rb
spec/jobs/application_job_spec.rb
spec/jobs/plexer_job_spec.rb

refs #1087
To eliminate one possibility for why locks are not being deleted from Redis, viz., objects are changing between a lock being created and the lock being deleted, resulting in the lock key also changing and therefore not being found to delete.
Note that this is at least one logical possibility for the problem. We won't know for sure until this is actually run in prod.
This is a replacement for #1254.

Uses global id to construct lock key.

---

app/services/workflow_reporter.rb
spec/services/workflow_reporter_spec.rb

Fixes #1258
The implementation was never matching the exception message due to unescaped parentheses in the regex. Fix that, and change the test to make it fail without the `WorkflowReporter::MISSING_WF_REGEX` change.
Also, fix another bug where the second call to `WorkflowReporter.report_completed` was 1) not sending the `version` argument, and 2) sending an undefined `error_message` argument (copy-pasta). I suspect this bug was being hidden by the funky test setup.
no

Create missing preservationAuditWF

---

Gemfile.lock
app/services/workflow_reporter.rb
spec/services/workflow_reporter_spec.rb

Fixes dor-workflow-client#139
This keys off the class of the exception raised by dor-workflow-client instead of comparing the exception message to a regex. We only care about exceptions related to missing workflows. As of dor-workflow-client 3.13.0, a new custom exception class is raised when there is a missing workflow.
no

Rescue the missing workflow exception to autocreate `preservationAuditWF`

---

README.md
app/services/moab_validation_handler.rb
docker-compose.yml
spec/lib/audit/catalog_to_moab_spec.rb

Fixes #1184
* Trap for `Errno::ENOENT` on first call to `moab_validation_errors`
* When the trap triggers, add a `MOAB_NOT_FOUND` result and update the status to `online_moab_not_found`
Also includes opportunistic bits:
* Prefer appending arrays of values to iterating and shoveling in `MoabValidationHandler`
* Use docker-mounted volume for postgres-data instead of local folder
* Prevents permissions errors when starting up containers
* We do this in our other projects as well. See also: sul-dlss/dor-services-app#436 
* Fix README by adding the needed namespaces.
Yes, README fixes.

Trap for `Errno::ENOENT`

---

app/jobs/catalog_to_moab_job.rb
app/lib/audit/catalog_to_moab.rb
app/models/moab_storage_root.rb
spec/jobs/application_job_spec.rb
spec/jobs/catalog_to_moab_job_spec.rb
spec/lib/audit/catalog_to_moab_spec.rb
spec/models/moab_storage_root_spec.rb

I am not sure why this argument was there and not used when the storage location can be grabbed from the `CompleteMoab`. Possibly used to be used for dependency injection or testing? Instead, grab the storage location from the `CompleteMoab` since we no longer appear to be using this arg which is mostly getting in the way.
no

Remove an unused initialization argument from `Audit::CatalogToMoab`

---

app/services/workflow_reporter.rb
spec/services/workflow_reporter_spec.rb

Fixes #1267
To prevent passing non-namespaced ("bare") druids to the workflow client and service.
no

Pass only namespaced druids to dor-workflow-client

---

README.md
app/controllers/catalog_controller.rb
app/controllers/objects_controller.rb
config/routes.rb
spec/controllers/catalog_controller_spec.rb
spec/requests/catalog_controller_spec.rb

Fixes #1206
To begin versioning routes in prescat without breaking clients that use current routes which don't contain a path segment specifying the API version.
For now, prescat is taking the same approach as dor-services-app: using a `scope` rather than a `namespace`. A `namespace` would have the following additional consequences:
* The path helper prefixes would change, to include `v1` in them, *e.g., `v1_catalog`, `checksum_v1_object`
* The controller#action routing would change, looking for controllers in a namespaced directory, *e.g.*, `app/controllers/v1/catalog_controller.rb` (and, accordingly, all the controllers would need to be added to a new `V1` module`)
Yes, API docs iN README.

Add /v1-scoped routes and redirect old URLs to new ones

---

README.md

follow-on from a couple stray typos in the documentation part of https://github.com/sul-dlss/preservation_catalog/pull/1266/files
noticed a couple things that seemed like minor oversights from #1266
it was the only thing updated

a couple README touchups

---

app/controllers/objects_controller.rb
spec/requests/objects_controller_checksums_spec.rb

closes #1229
To provide a helpful message when content_diff endpoint is unable to find a requested druid.
No.

Returns 409 from content_diff when missing druid(s).

---

app/jobs/moab_to_catalog_job.rb
app/models/moab_storage_root.rb
spec/jobs/moab_to_catalog_job_spec.rb
spec/models/moab_storage_root_spec.rb

Request by Julian for `MoabToCatalogJob#preform`'s arguments when manually remediating druids.
n/a
Fixes #1158

MoabToCatalog#perform remove path argument

---

config/environments/production.rb

Use Resque as ActiveJob adapter in production

---

app/controllers/objects_controller.rb
spec/requests/objects_controller_content_diff_spec.rb

I'm seeing the client return 500, but I don't know where this problem originates. Logging the original exception will assist in this.
n/a

Notify honeybadger when there is a Moab error

---

app/controllers/catalog_controller.rb

This is only useful if you are bulk updating attributes with parameters, which we are not
n/a

Remove permit params

---

config/environments/production.rb

reduce noise levels in production logging after upgrade to rails 6 switched default to debug

switch to log level debugging in production

---

app/lib/audit/moab_to_catalog.rb

Fixes #1300 
Adds minimal documentation to indicate that moab_to_catalog class is used as CLI tool only.
n/a

moab_to_catalog gets clarification in class comment

---

Gemfile
Gemfile.lock

Pinned rack version for compatability with OKComputer.

---

app/lib/preservation_catalog/s3/audit.rb
spec/lib/preservation_catalog/s3/audit_spec.rb

closes #1307
S3 needs to be configured before it is used; the corrects this for Audit.
No.

Configures S3 when invoking from Audit.

---

app/jobs/ibm_south_delivery_job.rb
app/jobs/s3_east_delivery_job.rb
app/lib/preservation_catalog/ibm.rb
app/lib/preservation_catalog/ibm/audit.rb
app/lib/preservation_catalog/s3.rb
app/lib/preservation_catalog/s3/audit.rb
db/README.md

* former in light of switch from provisioning creds via environment variables
* latter because it was useful when i was looking into a replication failure, and is also a nice example of a multi-table join in ActiveRecord
i stumbled across the opportunity for these touchups while poking at a couple replication errors.
this is a documentation only fix.

fix comments re: S3 creds, useful example query for db readme

---

config/initializers/okcomputer.rb

the optional okcomputer check for reachability was failing, because it was using a defunct URL.  this fixes the checked URL so that it's reachable again.
when looking at the okcomputer checks with @kamchan (to investigate a nagios alert), i discovered some failing checks, of which this was one.  i assume the URL that was used before in this check went bad when we got rid of the need to refer to workflows by repository (@jcoyne?).
e.g. this URL returns a 404:  https://sul-lyberservices-test.stanford.edu/workflowsdr/objects/druid:oo000oo0000/workflows
but this URL returns a 200:  https://sul-lyberservices-test.stanford.edu/workflow/objects/druid:oo000oo0000/workflows
N/A

fix broken okcomputer WFS check

---

.rubocop.yml
README.md
app/controllers/application_controller.rb
app/controllers/objects_controller.rb
config/settings/test.yml
spec/controllers/catalog_controller_spec.rb
spec/rails_helper.rb
spec/requests/auth_spec.rb
spec/requests/catalog_controller_spec.rb
spec/requests/objects_controller_checksums_spec.rb
spec/requests/objects_controller_content_diff_spec.rb
spec/requests/objects_controller_file_spec.rb
spec/requests/objects_controller_object_spec.rb
spec/support/auth_helper.rb

This change restricts all API access to callers that provide a valid JWT, generated on the pres cat server being accessed (with its current HMAC secret).
Groundwork for this (to allow token generation) is laid in #1305.  That should be merged and all supporting work should be completed before this branch is merged and deployed.
yes
closes #1298

gate API access by JWT

---

app/controllers/application_controller.rb

to clarify which URL requests need to be excluded explicitly from auth checks for an API token.
comment only update

comment about exceptions to API token requirement

---

app/lib/active_record_utils.rb

Because stack traces are most useful in Rails logs, not in messages in the workflow service, or in argo.  Honeybadger generates its own stacktrace.
n/a

DB_UPDATE_FAILED message tweaked

---

app/lib/preservation_catalog/ibm/audit.rb
spec/lib/preservation_catalog/ibm/audit_spec.rb

same idea as #1310
audits that check for replicated zip parts on the IBM endpoint are still failing.
N/A
fixes #1337

fix PreservationCatalog::Ibm::Audit#bucket, add a test

---

app/services/storage_root_migration_service.rb
lib/tasks/prescat.rake
spec/services/storage_root_migration_service_spec.rb

closes #1322
To update complete moab records when migrating storage roots.
No.

Adds a storage root migration service and rake task.

---

Gemfile
Gemfile.lock
app/models/moab_storage_root.rb
app/services/reporter.rb
lib/tasks/prescat.rake
spec/services/reporter_spec.rb

* obtain results using DB cursor and page through them using default batch size to write CSV
* install supporting gem for easier cursor usage
this is an alternative implementation to #1345, prompted by PR review.
this implements #1317, to help migrate moabs from old storage hardware to new.
there is a description on the rake task. happy to add to README if folks want, though i have a slight preference for further documenting this usage as part of process writeup for #1332.
closes #1317

rake task to dump list of druids on storage root to CSV file (page through select results w/ cursor)

---

app/services/audit_results.rb
config/database.yml
db/migrate/20200122001712_add_status_details_to_complete_moabs.rb
db/schema.rb

Connects to #1331 - have the db retain full audit error info for Moabs.  This is related to preservation migration work (an easy way to see what the last audit showed).  It is also a prerequisite for #1249 - have audit results available via ReST API call instead of using workflows for this information.
This PR should unblock some pres migration work;  I will continue working on *populating* this new field in a separate PR.
n/a

add status_detail field to complete_moabs table; audit_results refactor

---

app/services/audit_results.rb
app/services/moab_validation_handler.rb
app/services/storage_root_migration_service.rb
spec/lib/audit/catalog_to_moab_spec.rb
spec/services/audit_results_spec.rb
spec/services/shared_examples_preserved_object_handler.rb
spec/services/storage_root_migration_service_spec.rb

FIxes #1331
Replaces PR #1352
To populate the status_details field for a CompleteMoab with any error results from the latest audit of the Moab. This helps us with storage root migration, and it also positions us to provide audit results via ReST API (#1249)
n/a

write to status_details for complete_moab

---

app/models/complete_moab.rb
app/models/moab_storage_root.rb
app/services/storage_root_migration_service.rb
db/migrate/20200206163659_add_from_moab_storage_root_to_complete_moabs.rb
db/migrate/20200206163659_add_migrated_at_to_complete_moabs.rb
db/schema.rb
spec/services/storage_root_migration_service_spec.rb

Fixes #1321 
This adds an additional relationship between `CompleteMoab` and `MoabStorageRoot` to record the from storage root when recording migration results.

Add additional relationship for migrated moab storage root

---

app/services/reporter.rb
lib/tasks/prescat.rake
spec/services/reporter_spec.rb

Fixes #1318 
Fixes #1319 
The refactor proposed here is also in order to make the service usable for #1320 
Adds storage root detail report and storage root audit error detail report.
DRAFT until completion of some DRY refactoring and cleanup of rake arguments.
TBD

Add storage root detail reports to rake tasks

---

app/services/audit_results.rb
app/services/workflow_reporter.rb

Requested in post standup discussion -- want to document WHY prescat writes to WF service in the janky way it does.
no, but code documentation was.

add comments re: why we report audit errors to workflow service

---

app/services/reporter.rb
lib/tasks/prescat.rake
spec/services/reporter_spec.rb

(follow on to #1360)
initially i started in on a minor bit of refactoring so that more could be done in the initial query (which was previously just used to list druids), since that query already collects almost all the data we might want to report.  when a test failed i went to do a bit of manual testing, and noticed that the rake tasks weren't actually working, so i fixed those in addition to getting rid of the need to collect the druid list separately from the loop that collates results.  then i noticed that the reports all used the same default file name no matter the type, so i fixed that by adding a report type param to the csv writing method.
i also finally realized we probably want column headers (after waffling on that when first creating the `Reporter` class), so i added those. …

Reporting fix and touchup

---

README.md
lib/tasks/prescat.rake

Fixes #1368 
Fixes #1369
Fixes #1370
For preservation storage migration, it will be convenient to have rake tasks to run validations (m2c, c2m, cv) on a particular storage root.
the rake tasks added have descriptions.
README has been updated

add audit:m2c, audit:c2m and audit:cv rake tasks

---

app/services/moab_storage_root_reporter.rb
lib/tasks/prescat.rake
spec/services/moab_storage_root_reporter_spec.rb

closes #1367
* better rake task names
* remove colons in default output file names
* shorten default output file names
* i kept `storage_` as a prefix because i'd prefer _some_ namespacing/grouping in the event that we add other reports.  easy enough to totally remove if you feel strongly that it should go.
* user entered "tag" for easier visual differentiation of report runs
* slop from #1365
will update in a subsequent PR, since the changes i had on that front need a little tweaking, and may conflict with changes in (as-yet unmerged) #1372.

More report fixup

---

.github/ISSUE_TEMPLATE/storage-migration-checklist.md

We are experimenting with using a github issue template for storage migration weekend checklists.
Connected to #1378
n/a

Storage migration template

---

.github/ISSUE_TEMPLATE/bug_report.md

To have more than the storage-migration-checklist template;  want to make sure the repo doesn't make it hard for non-migration issues to be reported during the next few months.
n/a

add bug_report template

---

config/initializers/okcomputer.rb

Should fix #1371. Thanks @mjgiarlo for pointing to this [stackoverflow](https://stackoverflow.com/questions/56402093/how-can-i-preload-concerns-in-a-rails-initializer-using-rails-6-zeitwerk/59971682#59971682)  article.
The current method generates a depreciation warning.
n/a

Remove OKComputerController logger bespoke configuration

---

app/controllers/objects_controller.rb

Spotted by @ndushay here: https://github.com/sul-dlss/preservation_catalog/pull/1389#discussion_r384666534
Inaccurate documentation is misleading.
Yes, a code comment.
No.

Correct code comment in ObjectsController

---

app/services/audit_results.rb
spec/services/audit_results_spec.rb
spec/services/workflow_reporter_spec.rb

also refine specs so they'd have caught that and the equivalent issue in WorkflowReporter
see #1414, #1388
fixes #1414 (same issue as #1388, but in the one other spot that sort of call is made)
n/a
If so, please confirm:

AuditResults#events_client now uses namespaced druid

---

app/services/audit_results.rb
app/services/workflow_reporter.rb
spec/services/workflow_reporter_spec.rb

preservation catalog consistently uses the bare druid in the code and in the DB, so there's no need to safeguard against the prefix already being there when providing a namespaced druid string to other services.
remove the superfluous conditional, and a test that exercised it in a way that'd never be used IRL.
@jcoyne [asked if we could fix the code](https://github.com/sul-dlss/preservation_catalog/pull/1415#pullrequestreview-368207372) to not need the conditional that was removed here, but it was already unnecessary, so this just removes it.
n/a
no.  or at least, it doesn't intend to, though it does touch code that is used for interacting with other services.  happy to test on stage before this is merged or deployed to prod, if people want.
fwiw, i double-checked, and indeed, no druids …

remove unnecessary conditional from code that namespaces druid

---

.travis.yml
Gemfile
Gemfile.lock
README.md
app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
app/controllers/objects_controller.rb
config/application.rb
docs/index.html
openapi.yml
scripts/validate-openapi.bash
spec/requests/objects_controller_checksums_spec.rb
spec/requests/objects_controller_content_diff_spec.rb
spec/requests/objects_controller_file_spec.rb
spec/requests/objects_controller_object_spec.rb

Fixes #1216
Includes:
* Add OpenAPI specification (in YAML format)
* Use Committee gem to validate requests (but not yet responses)
* Validate the OpenAPI specification in CI
* Align ObjectsController documentation with implementation
* Adjust specs now that committee is doing some error handling
This PR could go farther by validating responses in addition to requests, and also by removing some error-checking/validation code paths in the controllers that may now effectively be dead by virtue of the work Committee is doing for us, but I opted to get this PR submitted instead due to its size and complexity.
Note that the [drop in coverage](https://coveralls.io/builds/28888801) is related to :point_up:. I'd like to hear what folks think about this.
yes

[HOLD] Add OpenAPI spec and validate requests against it

---

openapi.yml
spec/requests/objects_controller_content_diff_spec.rb

This is a case of drift between preservation_catalog (where tests assumed a request body with x-www-form-urlencoded args) and preservation-client (which was sending JSON). Since upstream code is using the client to access this endpoint, the openapi spec (and the tests) should reflect this expectation.
Should resolve https://app.honeybadger.io/projects/50568/faults/59300637
Yes
I have run the integration tests and there are no prescat-related errors.

Expect shelve diff endpoint to receive JSON not www-form

---

openapi.yml

This is the expected behavior in the controller. This bug is blocking integration testing.
openapi.yml, yes.
This will be integration tested.

Mark version and subset request body args as nullable

---

.circleci/config.yml
.simplecov
Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb

Fixes #1429
Adds code coverage back after we broke it when the switch was made from travis to CI (PR #1427).
I'm also moving coverage to CodeClimate.
Here's some proof it's working:  https://codeclimate.com/repos/5e680d9fbfd72e014c000fef/settings/test_reports/5e681b9cde48f40162009bf8
badge updated in README
no

circleci config updated for code climate test coverage reporting

---

openapi.yml
spec/requests/objects_controller_checksums_spec.rb

to fix #1434 (checksum report failing) likely due to new enforcement in openapi 
no
no

fix openapi for checksum

---

.github/ISSUE_TEMPLATE/storage-migration-checklist.md

Fixes #1417, more or less.
Questions (could become new tickets or could make changes here):
- should we be turning off all accessioning workers?
- should we be turning off technical-metadata-service workers? (reads preservation storage roots)
- should we *not* do PRs for shared_configs for migrations?
- should we consider a single checklist for multiple roots, instead of assuming a separate one for each root?
- should we consider a much terser checklist with an accompanying document?  This is overwhelming and hard to edit.
na
na

update storage migration checklist

---

app/services/checksum_validator.rb

refs #1430
To attempt to avoid a db timeout.
Since this is an intermittent problem, this is a wild guess.
No.
No.

Try to avoid db connection timeout when validating.

---

.github/ISSUE_TEMPLATE/storage-migration-checklist.md
lib/tasks/prescat.rake

* clarify migration checklist
* make it easier to run storage root migration task in a screen session, and make capturing the list of migrated druids easier.
yes
n/a

More migration usability

---

config/deploy/migrate.rb

To deploy to the instance of prescat we will be using in the storage migration
n/a -- this is a transient instance that will go away once the migration is complete
no

Add cap stage for storage migration instance

---

README.md
app/models/complete_moab.rb
app/services/moab_storage_root_reporter.rb
app/services/storage_root_migration_service.rb
spec/models/complete_moab_spec.rb
spec/services/storage_root_migration_service_spec.rb

to support manual migration of individual moabs between storage roots.
closes #1447 (per https://github.com/sul-dlss/preservation_catalog/issues/1447#issuecomment-600355906)
yes
n/a, just makes it easier to leverage functionality from rails console that was previously a private method for a manually run rake task.

make moab migration method public, document usage

---

.github/ISSUE_TEMPLATE/storage-migration-checklist.md

turns out we don't think we need to do that, see https://github.com/sul-dlss/preservation_catalog/issues/1439#issuecomment-600759173
just to be extra safe, i'd appreciate it if someone familiar with how the robots pick up work would review what i found in this comment before merging this, to make sure my understanding is correct:  https://github.com/sul-dlss/preservation_catalog/issues/1439#issuecomment-603078033
connects to #1439
documentation only
n/a

remove reference to disabling accessioning workers for storage migrations

---

config/routes.rb

per https://github.com/sul-dlss/preservation_catalog/issues/1439#issuecomment-600759173 we won't shut down accessioning robots for migration, which means that we'll need to enable the routes that allow accessioning robots to talk to pres cat for their read-only requests.
we'll leave disabled the create and update endpoints, but only the preservation robots should use those (and the preservation robots will still be disabled).
connects to #1439
yes, see #1452
we didn't shut down the accessioning robots in the [run through on stage](#1420) (the instructions removed here were added after that).  and we plan to test this again in a dry run the week of april 3.  so this has been …

re-enable read-only routes

---

Gemfile
Gemfile.lock

We no longer need to pin the rack gem as the okcomputer fix was merged in and released with okcomputer 1.18.1 (already in use here)
na
na

Rack upgrade

---

Gemfile
Gemfile.lock

to get gems into the correct groups
na
na

tidying up the Gemfile a bit

---

app/services/checksum_validator.rb
app/services/moab_validation_handler.rb
spec/services/checksum_validator_spec.rb

to make handling of wholly missing moab directories more robust when CV encounters druids like that (so we get an appropriate `status` change on the `CompleteMoab` instead of just a honeybadger error).
when first making the test changes (without the app changes in this PR), i was able to reproduce the backtrace seen in #1480.
when testing this app code change on pres cat's migrate instance, the `ChecksumValidator#validate_checksums` method now correctly updates `CompleteMoab#status` to `online_moab_not_found` if the combo of `druid` (via related `PreservedObject`) and `storage_location` (via related `MoabStorageRoot`) points to a moab directory that doesn't exist on the file system.  previously, this scenario would result in the uncaught error noted in #1480.
n/a
If so, please confirm …

ChecksumValidator#validate_checksums should check existence of moab dir first

---

.github/ISSUE_TEMPLATE/storage-migration-checklist-short.md

Because we are migrating many storage roots at once, the common text in the individual root issues is annoying.  This is a much shorter version of the template, to be used to track work for  individual storage roots only.  
Work pertaining to more than one root will be put in the uber ticket.  Examples:
- https://github.com/sul-dlss/preservation_catalog/issues/1462
- https://github.com/sul-dlss/preservation_catalog/issues/1465
na
na

add shorter storage-migration-checklist template

---

.github/ISSUE_TEMPLATE/storage-migration-checklist-short.md

in light of the fact that checksum validation of all migrated moabs will take weeks, adjust the instructions to:
* remove it from the "week before" procedure
* move it to the end of the migration checks, in such a way that it can wind down in the weeks following the migration
* replace its immediate use before and after the migration with the much speedier C2M check (which just ensures that the moab directories exists at the expected locations, without checksum validating their contents).
also notes about why this change is not as scary as it seems at first glance.

update short storage migration checklist re: when to run CV and C2M

---

.circleci/config.yml
Dockerfile
Gemfile
Gemfile.lock
app/lib/audit.rb
spec/models/complete_moab_spec.rb
spec/models/zip_part_spec.rb

update CI to test on current latest ruby (and make some other changes to address deprecation warnings and to clean up other cruft).
N/A
N/A

Test ruby 2.7.1

---

app/services/audit_results.rb
spec/services/audit_results_spec.rb
spec/services/checksum_validator_spec.rb

we were never setting the `moab-valid` step in `preservationAuditWF` to `complete`, even when we determined that a moab had gone back to being `ok` (pres cat maps its notion of `ok` to the workflow service's notion of `complete`).  as such, we'd add this workflow step if it didn't previously exist, but it would always be set to `waiting` unless it was remediated manually (usually by @andrewjbtw), which was erroneously preventing further versioning work on such objects.  this was recently exacerbated by the preservation storage migration, since we queued up all of the recently moved objects for audit, adding this workflow step anew to many of our repository objects.
i ran this fix by @ndushay, and she agreed that it is sensible to set `moab-valid` to `complete` whenever we set the …

set moab-valid step to completed when a moab is determined to be ok

---

app/services/checksum_validator.rb
spec/services/checksum_validator_spec.rb

also
* fix one test to expect moab version to get passed to workflow reporter (for passing along if/when creating workflow, which is the point of this fix)
* take two other tests broken by app code change, consolidate into one test that's more behavior focused and less focused on underlying implementation
connects to #1515 (and hopefully resolves the vast majority of occurrences of that issue)
note there are still some situations where audit won't send a version along
* C2M detects that the `PreservedObject` and `CompleteMoab` record different versions
* no moab is found on disk
* any time `PartReplicationAudit` detects an error that it reports to workflows, though this is rare, and `PartReplicationAudit` doesn't currently concern itself with the on premises moab, so i am hesitant to …

send current moab version in CV audit results, test adjustment/cleanup

---

app/models/druid_version_zip.rb

Fixes #1519
I briefly looked into testing this change but I don't think we get much value out of essentially testing a dependency. I suspect the test suite as currently written suffices as this is a refactoring.
Why? Because `Dir.chdir` is not thread-safe, and that will be a problem when we switch to using Sidekiq for background jobs.
No.
No.

Prefer `chdir:` arg to Open3 method over `Dir.chdir`

---

app/models/complete_moab.rb
db/migrate/20200507153050_add_index_unique_constraint_druid_moab_storage_root_to_complete_moab.rb
db/schema.rb
spec/models/complete_moab_spec.rb

Unique constraint on Preservation Object id and Moab Storage Root Id

---

app/lib/preservation_catalog/s3_audit.rb
spec/lib/preservation_catalog/aws_provider_spec.rb
spec/lib/preservation_catalog/ibm_provider_spec.rb
spec/lib/preservation_catalog/shared_examples_s3_audit.rb

* more descriptive param name for shared_examples 's3 audit'
* replace TRAVIS_JOB_ID usage in s3 upload integration test with truncated CIRCLE_SHA1 (since we moved from travis to circle)
* S3Audit#bucket can use method delegation since that's all the current method is doing
noticed a few small rough edges while reviewing 862dd017936b6a0687bb9ffb30cddf79bdcd4a3d, but only the third thing in the list was actually changed in that commit.
unit tests
n/a

a few small part audit touchups

---

app/services/audit_results.rb
spec/services/audit_results_spec.rb

While @andrewjbtw worked on #1520, he was confused because he didn't know which signatureCatalog.xml file was being used, and also because the mismatch was about the file size, not a checksum.
test suite
n/a

improve error message for MOAB_FILE_CHECKSUM_MISMATCH

---

app/lib/preservation_catalog/aws_provider.rb
app/lib/preservation_catalog/ibm_provider.rb
config/settings.yml
spec/lib/preservation_catalog/aws_provider_spec.rb
spec/lib/preservation_catalog/ibm_provider_spec.rb
spec/lib/preservation_catalog/shared_examples_provider.rb
spec/lib/preservation_catalog/shared_examples_s3_audit.rb

* get rid of AWS_BUCKET_NAME -- the codebase only referenced this in a test, our CI env doesn't make use of it, and none of our deployed envs make use of it (searching puppet for it turns up nothing).  additionally, the config gem allows override of any setting value via env var already (which our CI env does take advantage of).
* get rid of Settings.aws.bucket_name and Settings.ibm.bucket_name.  these were only leveraged in test code, were never overridden from the defaults, and were duplicative of the values specified in Settings.zip_endpoints.<endpoint_name>.storage_location.  standardize on that setting throughout the codebase.
* clarify a comment in shared_examples_s3_audit.rb
to make the code easier to understand by reducing complexity.
unit tests
clarification of a code comment, …

standardize on a single place to specify archive endpoint bucket name

---

.rubocop.yml
app/models/complete_moab.rb
app/services/complete_moab_handler.rb
spec/controllers/catalog_controller_spec.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/models/complete_moab_spec.rb
spec/services/complete_moab_handler_check_exist_spec.rb
spec/services/complete_moab_handler_create_spec.rb
spec/services/complete_moab_handler_spec.rb
spec/services/shared_examples_complete_moab_handler.rb

Fixes #1535 by adding new `CompleteMoab#by_storage_root` scope .
Ran test suite. 
n/a

Add scope to query CompleteMoabs by storage root

---

.rubocop.yml
app/models/druid_version_zip.rb
app/models/druid_version_zip_part.rb
app/services/complete_moab_handler.rb
spec/controllers/catalog_controller_spec.rb
spec/services/moab_storage_root_reporter_spec.rb

Opting-in to new rubocops. This makes it so we don't see a warning about them
Test suite
n/a

Enable the new rubocops

---

app/models/preserved_object_primary_moab.rb
db/migrate/20200616220804_create_preserved_objects_primary_moabs.rb
db/schema.rb

Part of #1528 (John - perhaps this is all of what you intended for #1528 ?)
To allow multiple CompleteMoab objects to be associated with a PreservedObject, we need for a single CompleteMoab to be "primary."   This PR adds a thin join table to accomplish this.

add preserved_objects_primary_moab table

---

app/models/complete_moab.rb
app/models/preserved_object.rb
app/models/preserved_object_primary_moab.rb
app/models/preserved_objects_primary_moab.rb
app/services/complete_moab_handler.rb
spec/services/complete_moab_handler_create_spec.rb

When we create a new CompleteMoab, populate the PreservedObjectsPrimaryMoab join table
Closes #1583
unit tests - which sufficiently kicked my behind
n/a

PreservedObjectsPrimaryMoab populated in CompleteMoabHandler

---

app/services/complete_moab_handler.rb

i suggested too exact a find condition when discussing #1587 w/ @ndushay.  we just want to check whether there's a primary moab for the _druid_ (`PreservedObject`), not whether there's an entry in the table that maps primary for the `PreservedObject`/`CompleteMoab` combo (which there won't be, since the specific `CompleteMoab` instance was just created in the code above the `PreservedObjectsPrimaryMoab` insertion).
existing unit tests.  #1591 should also shore up testing around this functionality.

loosen overly specific find when setting default primary moab

---

app/controllers/objects_controller.rb
config/routes.rb
openapi.yml
spec/requests/objects_controller_primary_moab_spec.rb

Fixes #1529 by adding a get route for an objects primary moab.
Unit test added
OpenAPI doc

Add a route to get the primary moab for a preserved object

---

db/migrate/20200624144318_populate_preserved_objects_primary_moabs.rb
db/schema.rb

closes https://github.com/sul-dlss/preservation_catalog/issues/1585
Provide initial population of primary moabs.
Local.
No.

Populates preserved_objects_primary_moabs table.

---

config/schedule.rb
config/settings.yml
lib/tasks/prescat.rake

Fixes #1576
Because without it, we are not purging the cache correctly, which results in running out of space.
Ran the rake tasks locally and they cleaned out `/tmp` as expected.
Added a new configuration. Does not require shared_configs work or clean-up.

Cleanup zip cache using parameterized directory and expiry time

---

app/lib/preservation_catalog/s3_audit.rb
spec/lib/preservation_catalog/shared_examples_s3_audit.rb

needs tests
to make it easier to audit parts that might have a spurious `unreplicated` status.
unit tests as they are pass (to my slight surprise), but i think we should add a new test or two (e.g. does an `unreplicated` part entry without a corresponding part entry in the cloud stay in the `unreplicated` state and trigger appropriate alerting/logging, and does an `unreplicated` part entry that actually has a corresponding physical part in the cloud with a matching checksum get set to `ok`).
n/a

S3Audit#check_replicated_zipped_moab_version checks all parts

---

app/models/complete_moab.rb
app/models/preserved_object.rb
spec/jobs/integration_spec.rb

_**note** wasn't clear in the initial wording, but this is a fix for work in progress that hasn't yet been merged_
to fix the application so that replication is triggered automatically when the catalog learns that a moab has been versioned.
(hopefully) fixes the regression described in [this comment](https://github.com/sul-dlss/preservation_catalog/pull/1589#issuecomment-653276439) on #1589.
unit tests initially, but i also plan to deploy to stage again and run the integration tests, as was done to find this issue in the first place.
the second commit is a test for the specific regression:
```
Failures:
1) the whole replication pipeline updating an existing moab gets from zipmaker queue to replication result message for the new version when the moab is updated
Failure/Error: …
```

Move zipped moab version: fix replication on moab update

---

app/models/complete_moab.rb
app/services/complete_moab_handler.rb
spec/controllers/catalog_controller_spec.rb
spec/factories/preserved_object.rb
spec/jobs/catalog_to_moab_job_spec.rb
spec/jobs/integration_spec.rb
spec/jobs/moab_to_catalog_job_spec.rb
spec/services/complete_moab_handler_check_exist_spec.rb
spec/services/complete_moab_handler_confirm_version_spec.rb
spec/services/complete_moab_handler_update_version_spec.rb

I didn't get around to ticketing this, but I discussed this with @andrewjbtw at the beginning of last week.
Our expectation is that pres robots will keep the primary updated, and the non-primary copy will be synced out of band from pres cat and pres robots to keep it up to date, using the primary copy as the syncing source, e.g. in preparation for migrating moab content to new storage hardware (allowing content to be synced and validated gradually from within the catalog, without needing to shut down pres cat and migrate DB entries while it refrains from doing anything with storage, so as to only see one copy of a moab in one known location at a time).  Alternatively, a non-primary copy might be created when retrieving a cloud copy, e.g. for use in remediating a damaged local copy.
In …

Only update PreservedObject#current version if CompleteMoab being checked/updated is primary

---

app/jobs/zipmaker_job.rb
config/settings.yml

in hopes of ameliorating problems due to lag between when pres robots worker finishes writing a file, and when pres cat is able to read it
* unit tests cover the code change for basic functionality
* as a basic smoke test will deploy to stage and run infra integration tests and confirm preservation works, before deploying to prod.
* will babysit in prod for a while after deployment
added a couple settings, left explanation in code comments, since that seems like the most visible/useful place for the necessary info.

configurable artificial delay before making zip for replication

---

app/models/druid_version_zip.rb
spec/models/druid_version_zip_spec.rb

To confirm that the contents of a Moab directory are readable before attempting to create a zip file from it, and to maybe kick Ceph MDS into making the files readable if MDS still sees the files as strays.
Per our hypothesizing in #1633, preservation_robots' implementation of similar logic (see https://github.com/sul-dlss/preservation_robots/pull/273) should (we hope) mitigate issues reading the new Moab version content.  But in the event there are still read issues, this will at least make it easier to retry the `zipmaker` failure without having to clean up a bad zip file from `/sdr-transfers`, by failing the job early (#1637 will also help keep retrying easy, if for some reason read issues crop up after the check added by this PR -- we haven't seen that in practice, but we're just …

Check moab readability

---

app/models/zipped_moab_version.rb

This will make it easier to safely remediate Moab replications that got wedged part way through the pipeline, by allowing more confidence that data about replicated parts won't be accidentally deleted when trying to clean up hanging `ZippedMoabVersion` records.
(discussed briefly on slack last week)
unit tests.  in the normal course of app operation, `ZippedMoabVersion`s aren't deleted.  that's only done manually, to remediate replication problems.
n/a

raise if trying to delete a ZippedMoabVersion for which ZipParts still exist

---

app/jobs/zipmaker_job.rb
app/models/druid_version_zip.rb
spec/jobs/integration_spec.rb
spec/jobs/zipmaker_job_spec.rb
spec/models/druid_version_zip_spec.rb

closes #1642
builds on #1644 (hence the non-master base branch, since that's already been approved)
First commit does some test improvement without touching the app code, hopefully making the modified tests more illustrative, more realistic, and less likely to break in the face of an implementation change that doesn't introduce regressions. (https://github.com/sul-dlss/preservation_catalog/commit/c7f064780040eaf41587a7993107388d60b9fac4 -- to make this easier to review, i pushed this commit as a separate branch to show that it passed CI on its own)
Second commit is the change that the first commit paves the way for, and is the functionality asked for by #1642 (I went with the "just raise" approach).  Third commit has two new tests to show that the new check does what it's supposed to, and …

Zipmaker raise on undersized extant zip

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb

This replaces `capistrano-resque-pool` and works as expected with a hot-swappable pool.
Also includes:
* Store resque-pool lockfile in shared dir
* this allows the `resque:pool:hot_swap` capistrano task to do what we expect it to do.
in prescat-qa
None

Use dlss-capistrano to manage resque-pool tasks 

---

Gemfile.lock

force updating to latest cocina-models and dor-services-client (didn't happen with weekly updates, for whatever reason)
unit tests

manual bundle update to force getting new deps

---

.rubocop.yml
app/jobs/results_recorder_job.rb
app/models/zipped_moab_version.rb
db/README.md
db/schema.rb
spec/factories/zip_parts.rb
spec/jobs/integration_spec.rb
spec/jobs/results_recorder_job_spec.rb
spec/models/zip_endpoint_spec.rb

closes #1685 
ref https://github.com/sul-dlss/infrastructure-integration-test/issues/249
* unit tests
* deploy to stage: run `create_preassembly_image_spec.rb` from infra integration test suite, look for replication event on argo detail page for item that was created (item should have two versions, stage has 3 cloud endpoints, so there should be 6 events)
random housekeeping and preparatory refactoring in the first commit.
in case it's helpful, here's the diagram of the replication pipeline:  https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/README.md
a couple comments, a bit of inline rubocop config

log to event service when all zip parts for a moab version have been replicated to one cloud endpoint

---

app/models/druid_version_zip.rb

To make honeybadger error less cryptic:  https://app.honeybadger.io/projects/54415/faults/75709216

improve errmsg

---

app/jobs/validate_moab_job.rb
app/services/audit_results.rb
app/services/reporters/audit_workflow_reporter.rb
spec/controllers/catalog_controller_spec.rb
spec/jobs/validate_moab_job_spec.rb
spec/lib/audit/catalog_to_moab_spec.rb
spec/lib/audit/checksum_spec.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/services/audit_results_spec.rb
spec/services/checksum_validator_spec.rb
spec/services/complete_moab_handler_check_exist_spec.rb
spec/services/complete_moab_handler_confirm_version_spec.rb
spec/services/complete_moab_handler_create_spec.rb
spec/services/complete_moab_handler_spec.rb
spec/services/complete_moab_handler_update_version_spec.rb
spec/services/reporters/audit_workflow_reporter_spec.rb

In order to avoid continuing with preservationIngestWF when a Moab hasn't been correctly written to Ceph, or isn't yet ready to be accessed by the replication steps, we want to add a validation of the on disk Moab, without reference to the preservation-catalog basis.
Closes #1697, #1698
Review the 2 commits separately;  the first is a rename for clarity;  the second accomplishes the goals of the tickets.
- unit tests
- script that is similar

ValidateMoabJob added 

---

config/initializers/okcomputer.rb
config/settings.yml
spec/lib/okcomputer_spec.rb

Fixes #1712 -- add more thorough okcomputer checks for pres-cat disks
This now verifies:
1. That both the `sdr2objects` and `deposits` directories exist for each pres-cat disk and that they are directories
2. That the `sdr2objects` directory has a minimum number of subfolders contained in it (configurable in settings, but should be set at a threshold below the current numbers for all disks, which is currently 402 in production).  This could be a problem when a new disk is added since the count would then be lower for just the last disk.  At this point we may want to configure it per disk instead by adding some new settings.
Updated the existing unit test.
Deployed to stage to validate

add more rigorous okcomputer checks for pres disks

---

app/controllers/objects_controller.rb
config/routes.rb
openapi.yml
spec/requests/objects_controller_validate_moab_spec.rb

Adds a new endpoint to start a MoabValidation job which can later be called from a new preservationWF robot
Added new tests

add endpoint for new MoabValidation job

---

config/resque-pool.yml

So there are workers to execute steps in the validate_moab queue.
May address #1719

add 2 workers for validate-moab step by default

---

app/jobs/validate_moab_job.rb
spec/jobs/validate_moab_job_spec.rb

Fixes two problems:
- before_enqueue was looking for the druid parameter before we had it
- the moab validation needs to use the full druid, with the "druid:" prefix
Closes #1719, #1722
rspec tests and on stage with https://github.com/sul-dlss/workflow-server-rails/pull/470 deployed.

ValidateMoabJob uses full druid to instantiate Moab and checks druid param usefully

---

.rubocop.yml
app/jobs/validate_moab_job.rb
spec/jobs/validate_moab_job_spec.rb

Fixes #1720
We only want to perform checksums for Moab content files for the latest version, not for all versions.
unit tests

ValidateMoabJob only does data file checksums for latest version

---

Gemfile
Gemfile.lock
app/controllers/objects_controller.rb
app/jobs/application_job.rb
app/jobs/zip_part_job_base.rb
app/jobs/zipmaker_job.rb
openapi.yml
spec/jobs/application_job_spec.rb
spec/requests/objects_controller_validate_moab_spec.rb

* wire up lock cleanup so it's actually invoked (fixes https://github.com/sul-dlss/preservation_catalog/issues/1726)
* comments explaining locking behavior and providing necessary license info
closes #1726
WIP until testing's all sorted out
bonus: have `ObjectsController#validate_moab` return an informative error to the caller in the unlikely event that it can't queue the job.
comments in relevant code

inline the logic provided by the resque-lock gem, drop the dependency

---

app/controllers/objects_controller.rb
spec/requests/objects_controller_checksums_spec.rb

Fixes sul-dlss/argo#2784 - instead of failing the entire checksum job if some druids are not found, return the response and include information about the missing druids instead
if another unexpected error occurs, still fail the entire job
~~Hold pending verification of this behavior by Andrew~~ Verified in ticket sul-dlss/argo#2784 
Updated/added tests

allow checksum job to return for multiple checksums when some not found

---

.rubocop.yml
Gemfile
Rakefile
app/services/audit_results.rb
app/services/catalog_remediator.rb
lib/tasks/prescat.rake
spec/lib/audit/catalog_to_archive_spec.rb
spec/lib/audit/catalog_to_moab_spec.rb
spec/lib/preservation_catalog/shared_examples_s3_audit.rb
spec/requests/objects_controller_primary_moab_spec.rb
spec/services/audit_results_spec.rb
spec/services/catalog_remediator_spec.rb
spec/services/reporters/audit_workflow_reporter_spec.rb
spec/services/reporters/event_service_reporter_spec.rb

Fixes #1748
And call the class from a new rake task, printing out results.
Also includes:
* Add new Rubocop rules
* Because rubocop barked at me. And, as part of spinning up the app after a long time, do a little work to make sure `rake` does what we expect usually. That involved moving rspec-rails to the dev/test bundler group and some Rakefile touches.
Fixes #1748 
TBD
None

Add CatalogRemediator class to prune replication failures from catalog 

---

config/deploy/prod.rb

To migrate the API instance to Ubuntu
Tested file downloads from argo, and versioning objects with Andrew
DevOpsDocs PR forthcoming

Add web-prod-01

---

config/deploy/prod.rb

Ops seems to have changed the VM name:

fix prod deploy targets

---

config/deploy/qa.rb
config/deploy/stage.rb

specifically:
* everything that has the `app` role puts it first, for a bit more readability
* the missing `queue_populator` and `cache_cleaner` roles are added to the worker boxes (-02) for stage and QA, as they apparently went entirely missing at some point (noticed because the zip temp space filled up on stage, and the cache cleaner rake task wasn't in the crontab for -stage-02, where i'd have expected it).
noticed because stage workers couldn't create archive zips, because the zip temp space had filled up
* this branch was deployed to stage at 4:37 pm
* the job was allowed to run at 5:00 pm (it's scheduled for the top of the hour)
* space started freeing up once the job started (at 635 GB of 1 TB available as of 5:34 pm)
* the failed `zipmaker` jobs were retried, and all of the 10 or …

make capistrano deployment roles consistent between prod, stage, and qa

---

lib/tasks/prescat.rake

Fixes #1782
To prevent deleting a directory that must be present. This was happening on QA.
I ran the find command before and after with a test directory locally. Before this change, the test dir was deleted. After, it wasn't.
None

Prevent deletion of transfers directory

---

Capfile
Gemfile
Gemfile.lock

It let us get past a deployment error to the new web-stage machines:
```
bundle stderr: /usr/bin/env: 'bundle': No such file or directory
```
Deployed to the stage load-balanced nodes
DevOpsDoce PR forthcoming

Use cap-rvm in prescat

---

config/deploy.rb

Because honeybadger doesn't integrate with capistrano-rvm
This worked for technical-metadata-service
N/A

Let capistrano report to honeybadger

---

config/deploy/prod.rb

Closes #1783
@tallenaz gave us the magic to fix this problem.
I deployed to prod and it didn't hang.

cap resque:pool:hot_swap no longer hangs!

---

.github/pull_request_template.md

⚡ ⚠ If this change has cross service impact, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test) on stage as it tests preservation*** and/or test in stage environment, in addition to specs. ⚡

suggestion for a situation where it'd be good to run integration tests even w/o cross service changes

---

.circleci/config.yml

Update to the orb that has the updated version of redis

---

config/deploy.rb

Still occasionally seeing dead workers lingering after deployment. So prune dead workers as part of deployment process.
CI, + a test deploy to stage. Resulted in expected number of workers! (Was previously +1.)

Prune dead resque-pool workers after hot-swapping during deploy

---

config/deploy.rb

see also https://github.com/sul-dlss/preservation_catalog/wiki/More-than-the-expected-number-of-Resque-workers-are-running---too-many-resque-workers---worker-count-high#the-above-determines-that-the-right-number-of-workers-are-actually-running
small follow on to #1834 
n/a, comment only change
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and …

comment on cap call to Resque::Worker#prune_dead_workers

---

config/deploy.rb

see https://github.com/sul-dlss/preservation_catalog/issues/1836
remedy what seems like a small deployment and monitoring rough edge that may have been newly introduced, while we figure out what's going on.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication …

comment out prune_dead_workers cap hook

---

app/jobs/plexer_job.rb
spec/jobs/plexer_job_spec.rb

Fixes #1830. 
Unit tests pass and specs added. Ran `create_preassembly_image_spec.rb` from integration tests successfully on stage. 

Fix PlexerJob infinite retries

---

Gemfile
Gemfile.lock

Updated dor-services-client

---

config/initializers/okcomputer.rb
config/schedule.rb

and adjust audit threshold to prevent false alerts.
for your consideration: the alternative (more idiomatic?) native whenever syntax for the job where raw cron syntax was used would be:
`every :month, at: 'Jan 15th at 11:00'`
the month part of the `at:` param would be disregarded (but without that placeholder month in the `at:` param, '15', '15th', etc, is interpreted as an hour on the first day of the month, not a day of the month).  this appears to be an artifact of whenever's use of chronic (the gem whenever relies on for date parsing).
Per recurring discussion/suggestion in slack (see e.g. [here](https://stanfordlib.slack.com/archives/G6K8R3VBK/p1655835935574139)) we think that the current level of parallelization of the m2c and c2m work (done by `MoabToCatalogJob` and …

put M2C and C2M audits on monthly schedule

---

Gemfile
Gemfile.lock
app/jobs/results_recorder_job.rb
app/services/reporters/event_service_reporter.rb
config/initializers/dor_event_client.rb
config/initializers/dor_services_client.rb
config/settings.yml
spec/jobs/integration_spec.rb
spec/jobs/results_recorder_job_spec.rb
spec/services/checksum_validator_spec.rb

closes #1860
To make the job more resilient.
Unit

Switch dor-event-client for dor-services-client for creating events.

---

docker-compose.yml

Otherwise docker-compose will pull an old copy and build a new copy
`docker compose up`

Don't specify image because we're building the image

---

app/jobs/application_job.rb
app/jobs/catalog_to_moab_job.rb
app/jobs/checksum_validation_job.rb
app/jobs/moab_replication_audit_job.rb
app/jobs/moab_to_catalog_job.rb
app/jobs/part_replication_audit_job.rb
app/jobs/results_recorder_job.rb
app/jobs/validate_moab_job.rb
app/jobs/zip_part_job_base.rb
app/jobs/zipmaker_job.rb
spec/jobs/application_job_spec.rb

Now every job that is using the locking strategy declares "include UniqueJob".  This means we only have jobs that have opted into this strategy on purpose rather than accidentally inheriting this behavior.
Fixes #1899
Test suite

Make job locking explicit

---

spec/services/reporters/event_service_reporter_spec.rb

* it seemed like `client` was still referenced even after its definition was removed [here](https://github.com/sul-dlss/preservation_catalog/pull/1909/files#diff-092e0f690b001a6977f6f5b15d9412246f6ce67764588074112ec71dc818d436), so it wasn't clear to me how that spec was passing in Circle.
* and then when i tried to see what would happen for me locally with that branch, i got an error when those tests actually tried to connect to rabbitmq on `localhost` (where i had no rabbitmq instance running).
* it's nice to keep some explicit expectations about what the event service will receive, esp in that event reporter spec.
unit tests (local/CI)
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test …

replace expectations on removed dor-services-client event client with expectations on its replacement, Dor::Event::Client

---

.circleci/config.yml

Bump sul-dlss orb to 3.1.2

---

spec/lib/audit/catalog_to_moab_spec.rb
spec/services/audit_results_spec.rb
spec/services/reporters/event_service_reporter_spec.rb

This gets the build working again. There was a problem because we don't have Dor::Services::Client in the gemfile anymore.
This prevents errors like:
```
Failure/Error:
allow(Dor::Services::Client).to receive(:object).with("druid:#{druid}").and_return(
instance_double(Dor::Services::Client::Object, events: events_client)
)
NameError:
uninitialized constant Dor::Services
```
when running the tests.
CI

Remove the vestiges of Dor::Services::Client from the tests

---

app/models/druid_version_zip.rb

refs #1881
Thread safety. Maybe.

Change zip version to instance variable.

---

.rubocop.yml
app/jobs/application_job.rb
app/jobs/validate_moab_job.rb
app/jobs/zipmaker_job.rb
config/deploy.rb
config/settings.yml
spec/jobs/validate_moab_job_spec.rb
spec/jobs/zipmaker_job_spec.rb

closes #1918
Be nice to ceph.
* Unit
* `create_preassembly_image_spec.rb` in QA.

Adds delay to ValidateMoabJob.

---

Gemfile
Gemfile.lock

closes #1926
To pin the correct version of faraday-retries.

Update to latest workflow client.

---

bin/create_bag

Port `bin/create_bag.rb` from preservation_robots so that it can run against a read-only filesystem in prescat environments.
Closes #1871 

Adding create_bag.rb from preservation_robots

---

spec/models/complete_moab_spec.rb
spec/models/preserved_object_spec.rb

These occurrences of "PreservedCopies" should have become "CompleteMoabs" a long time ago, with the database migration in July 2018.  Whoops.

specs - they are CompleteMoabs, not PreservedCopies

---

app/lib/audit/moab_to_catalog.rb
db/migrate/20221004215925_add_unique_constraint_preserved_object_id_to_complete_moab.rb
db/migrate/20221007185705_rename_index_complete_moab_on_po_and_storage_root.rb
db/schema.rb
spec/controllers/catalog_controller_spec.rb
spec/jobs/catalog_to_moab_job_spec.rb
spec/jobs/moab_to_catalog_job_spec.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/models/complete_moab_spec.rb
spec/models/preserved_object_spec.rb
spec/services/complete_moab_handler_check_exist_spec.rb
spec/services/complete_moab_handler_confirm_version_spec.rb
spec/services/complete_moab_handler_spec.rb
spec/services/complete_moab_handler_update_version_spec.rb

**HOLD -- DO NOT WANT TO DEPLOY WITH DEPENDENCY UPDATES**
**Before Merge/Deploy:**
part of #1891, which is part of Epic #1892 to remove multiple moab instances
specs.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/job …

[HOLD] add database constraint limiting us to one CompleteMoab per PreservedObject

---

app/models/complete_moab.rb
spec/lib/audit/moab_to_catalog_spec.rb
spec/models/complete_moab_spec.rb
spec/services/complete_moab_handler_update_version_spec.rb

* follow on from review of #1946
* connects with #1891 ("change complete_moab to `validates :preserved_object_id, uniqueness: true` from `validates :preserved_object_id, uniqueness: { scope: [:moab_storage_root_id] }`")
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication …

follow-on to one-moab-per-druid DB constraint

---

db/migrate/20221018143200_add_unique_zipped_moab_versions.rb
db/schema.rb
spec/services/catalog_remediator_spec.rb

closes #1831
Safety.
Verified that no existing zipped moab versions violate this constraint in all environments.

Add unique index to ZippedMoabVersions.

---

app/models/complete_moab.rb
app/models/preserved_object.rb
config/schedule.rb
spec/models/complete_moab_spec.rb
spec/models/preserved_object_spec.rb

closes #1939
Even out auditing/validation load.

Perform daily auditing/validation.

---

app/jobs/abstract_delivery_job.rb
app/jobs/ibm_south_delivery_job.rb
app/jobs/s3_east_delivery_job.rb
app/jobs/s3_west_delivery_job.rb
app/services/zip_delivery_service.rb
spec/jobs/abstract_delivery_job_spec.rb
spec/jobs/ibm_south_delivery_job_spec.rb
spec/jobs/s3_east_delivery_job_spec.rb
spec/services/zip_delivery_service_spec.rb

Fixes #1922
This commit refactors zip delivery in the following ways:
* Move zip delivery into its own small service class
* Invoke zip delivery service from a new abstract delivery job
* Base all three delivery jobs on the abstract delivery job
CI

Refactor zip delivery

---

app/models/audit_results.rb
app/services/audit/catalog_to_moab.rb
app/services/complete_moab_service/base.rb
app/services/complete_moab_service/check_existence.rb
app/services/complete_moab_service/create.rb
app/services/complete_moab_service/create_after_validation.rb
app/services/complete_moab_service/update_version.rb
app/services/complete_moab_service/update_version_after_validation.rb
spec/services/audit/catalog_to_moab_spec.rb
spec/services/complete_moab_service/shared_examples.rb

Extract common from Complete Moab services into base class

---

app/services/complete_moab_service/base.rb
app/services/complete_moab_service/check_existence.rb
app/services/complete_moab_service/update_version.rb
app/services/complete_moab_service/update_version_after_validation.rb
spec/services/complete_moab_service/check_existence_spec.rb
spec/services/complete_moab_service/create_after_validation_spec.rb
spec/services/complete_moab_service/create_spec.rb
spec/services/complete_moab_service/shared_examples.rb
spec/services/complete_moab_service/update_version_after_validation_spec.rb
spec/services/complete_moab_service/update_version_spec.rb

Debreviates

---

app/services/complete_moab_service/base.rb
app/services/complete_moab_service/check_existence.rb
app/services/complete_moab_service/update_version.rb
app/services/complete_moab_service/update_version_after_validation.rb

Move remove_db_updated_results to transaction method.

---

.rubocop.yml
app/services/complete_moab_service/base.rb
app/services/complete_moab_service/check_existence.rb

Refactor check existence service.

---

app/services/complete_moab_service/create.rb
app/services/complete_moab_service/create_after_validation.rb

Refactor create and create_after validation services.

---

app/services/complete_moab_service/base.rb
app/services/complete_moab_service/check_existence.rb
app/services/complete_moab_service/update_version.rb
app/services/complete_moab_service/update_version_after_validation.rb
spec/services/complete_moab_service/update_version_after_validation_spec.rb
spec/services/complete_moab_service/update_version_spec.rb

Refactor update_version and update_version_after_validation services.

---

app/jobs/ibm_south_delivery_job.rb
app/jobs/s3_east_delivery_job.rb
app/jobs/s3_west_delivery_job.rb
app/services/s3/aws/audit.rb
app/services/s3/ibm/audit.rb
db/README.md
docker-compose.yml
spec/services/audit/moab_to_catalog_spec.rb
spec/services/complete_moab_service/check_existence_spec.rb

mostly misc small follow on from comments on https://github.com/sul-dlss/preservation_catalog/pull/1953 and #1983, and a couple similarly small unrelated things.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/REA …

Misc touchups

---

app/models/complete_moab.rb
app/services/complete_moab_service/base.rb
app/services/complete_moab_service/check_existence.rb
app/services/complete_moab_service/update_version.rb

at least part of #1977
Legacy
Unit

Removes primary moab related code.

---

app/models/complete_moab.rb
app/models/preserved_object.rb
app/services/complete_moab_service/base.rb
spec/controllers/catalog_controller_spec.rb
spec/jobs/integration_spec.rb
spec/services/complete_moab_service/check_existence_spec.rb
spec/services/complete_moab_service/create_after_validation_spec.rb
spec/services/complete_moab_service/create_spec.rb
spec/services/complete_moab_service/update_version_after_validation_spec.rb
spec/services/complete_moab_service/update_version_spec.rb

closes #1977
This is the last of the primary moab code to remove before removing the db table and associations for primary moab concept.
rspec tests

removing use of PreservedObjectsPrimaryMoab table

---

app/models/audit_results.rb
app/services/audit/catalog_to_moab.rb
app/services/checksum_validator.rb
app/services/complete_moab_service/base.rb
app/services/complete_moab_service/check_existence.rb
app/services/complete_moab_service/update_version.rb
app/services/complete_moab_service/update_version_after_validation.rb
app/services/moab_utils.rb
app/services/moab_validator.rb
app/services/status_handler.rb
spec/services/audit/catalog_to_moab_spec.rb
spec/services/checksum_validator_spec.rb
spec/services/complete_moab_service/check_existence_spec.rb
spec/services/complete_moab_service/create_after_validation_spec.rb

refs https://github.com/sul-dlss/preservation_catalog/issues/1951
MoabValidator had 3 different uses:
* Validation
* Updating status
* Acting as a convenience container for some objects.
This PR refactors so that: (1) MoabValidator only does validation; (2) StatusHandler updates status; and (3) the need for a convenience container is factored out.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, …

Refactors MoabValidator.

---

app/services/complete_moab_service/check_existence.rb

'cause the build was failing and it wasn't my branch's fault.

fix rubocop failure

---

app/controllers/application_controller.rb
app/controllers/dashboard_controller.rb
app/helpers/dashboard_helper.rb
app/models/complete_moab.rb
app/views/dashboard/_audit_information.html.erb
app/views/dashboard/_audit_status.html.erb
app/views/dashboard/_catalog_information.html.erb
app/views/dashboard/_catalog_status.html.erb
app/views/dashboard/_complete_moab_status_counts.html.erb
app/views/dashboard/_endpoint_data.html.erb
app/views/dashboard/_moab_storage_root_data.html.erb
app/views/dashboard/_object_versions.html.erb
app/views/dashboard/_replicated_files.html.erb
app/views/dashboard/_replication_flow.html.erb
app/views/dashboard/_replication_information.html.erb
app/views/dashboard/_replication_status.html.erb
app/views/dashboard/_zip_parts_suffix_counts.html.erb
app/views/dashboard/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/helpers/dashboard_helper_spec.rb
spec/requests/dashboard_spec.rb
spec/routing/routing_spec.rb

Fixes #1962 
See https://preservation-catalog-web-stage-01.stanford.edu/dashboard
This is, essentially, some ideas with first pass implemetations.  I would expect:
- more, better ideas to come
- better display of information
- potential implementation improvements
Once this PR is merged, we can have multiple folks simultaneously work on improving the PR.  So it is less important that this code is close to perfect, and more important that the functionality has tests, as lots of refactors are expected.
There are already a bunch of tickets with label dashbaord for improvements;  I am about to make more from the notes from storytime last week.
specs and in situ
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test …

dashboard beginnings

---

app/helpers/dashboard_helper.rb
app/services/complete_moab_service/check_existence.rb

after merging dashboard branch in PR #1992, we had rubocop violations

fix rubocop after dashboard PR #1992 merge

---

app/helpers/dashboard_replication_helper.rb
app/views/dashboard/_replication_endpoint_data.html.erb
spec/helpers/dashboard_replication_helper_spec.rb
spec/requests/dashboard_spec.rb

Lower cognitive load - make the data structure more transparent by giving it a better name and using a hash instead of an array to keep the information, so it is defactor labeled.
Also added a little more explanation to the view:
Fixes #2014
locally and with new spec.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for …

refactor dashboard helper method for endpoint data and tweak the view slightly

---

app/views/dashboard/_replicated_files.html.erb
app/views/dashboard/_replication_information.html.erb

After looking at prod, this will make a better layout
(zip parts are after Replication Flow table)

dashboard: Replication information display tweak

---

app/services/catalog_remediator.rb

I was confused.  This comment change would have helped me.

improve comment for CatalogRemediator class

---

app/services/catalog_remediator.rb
app/services/s3/s3_audit.rb
spec/services/catalog_remediator_spec.rb

I was having trouble grokking the code; I believe these changes, largely comments, make it easier.  
CodeClimate is out of its gourd.
Wingnut approves this PR.
specs
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs …

Refactor: CatalogRemediator slight refactors, ditto S3Audit

---

README.md
db/README.md

One of my tiny PRs to changes `docker-compose` to `docker compose` as I find them...

Update docker compose syntax in README

---

app/services/moab_validator.rb

MoabValidator: improve class comment

---

README.md

This commit started with the intention of changing the docs to include
foreman instructions. But in the process I noticed that I ran into some
difficulty running tests when following the instructions, which led to a
wider set of changes.
The key changes are:
- Mention running with `bin/dev` for development since it will take care
of (optionally) installing foreman and using it. The docs also now
indicate that the webapp can be run via Docker if you prefer.
- Moving the testing section up into the beginning since that's what
people most likely will be doing when they come to the app for the
first time? Previously information on how to get up and running to
develop was fragmented, and easy (for me) to miss.
- Removed the table of contents, mostly because not everything was
linked up and …

Docs changes

---

config/settings.yml

closes #2020
Make replication retries easier.

Increase zip cache expiration to 2 weeks.

---

app/jobs/application_job.rb
config/settings.yml

closes #2047
Keep comments useful.

Update filesystem_delay_seconds comments.

---

config/deploy/qa.rb

finish off dropped part of OS migration and load balancing from this summer

QA: update cap deploy config to use load balanced web hosts

---

.github/pull_request_template.md

noticed this was out of date when putting up https://github.com/sul-dlss/preservation_catalog/pull/2050

update stale integration test reference

---

app/services/audit/catalog_to_moab.rb
app/services/audit/checksum_validator.rb
app/services/complete_moab_service/check_existence.rb
app/services/complete_moab_service/update_version.rb
app/services/complete_moab_service/update_version_after_validation.rb
app/services/status_handler.rb
spec/services/audit/catalog_to_moab_spec.rb

Refactor catalog to moab

---

app/models/complete_moab.rb
spec/models/complete_moab_spec.rb

Remove replicatable_status.

---

app/helpers/dashboard_audit_helper.rb
app/models/complete_moab.rb
app/models/moab_storage_root.rb
config/initializers/okcomputer.rb
spec/config/okcomputer_spec.rb
spec/models/complete_moab_spec.rb

closes #2067
To make things not confusing.

Renames CompleteMoab.least_recent_version_audit.

---

app/components/dashboard/audit_information_component.rb
app/components/dashboard/complete_moabs_component.rb
app/components/dashboard/moab_storage_roots_component.rb
app/components/dashboard/object_versions_component.rb
app/components/dashboard/replication_endpoints_component.rb
app/components/dashboard/replication_files_component.rb
app/components/dashboard/zip_parts_suffixes_component.rb
app/services/dashboard/audit_service.rb
app/services/dashboard/catalog_service.rb
app/services/dashboard/replication_service.rb
spec/services/dashboard/audit_service_spec.rb
spec/services/dashboard/catalog_service_spec.rb
spec/services/dashboard/replication_service_spec.rb

This was an excellet suggestion by @justinlittman in PR #2076.   Check out the giant simplification of the ViewComponent classes.
Fixes #2078.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/READM …

dashboard service classes become modules

---

app/components/dashboard/audit_information_component.rb
app/components/dashboard/complete_moabs_component.rb
app/components/dashboard/moab_on_storage_status_component.rb
app/components/dashboard/moab_storage_roots_component.rb
app/components/dashboard/object_versions_component.rb
app/components/dashboard/replication_endpoints_component.rb
app/components/dashboard/replication_status_component.rb
app/services/dashboard/audit_service.rb
app/services/dashboard/catalog_service.rb
app/services/dashboard/moab_on_storage_service.rb
app/services/dashboard/replication_service.rb
app/views/dashboard/_replication_information.html.erb
spec/services/dashboard/moab_on_storage_service_spec.rb

from storytime 2022-11-28:   our code uses "catalog" in a misleading way, because it's more "on prem storage" vs. cloud (replicated) storage -- both are in the catalog.
I renamed the dashboard classes and partials that had "catalog" in the name and tweaked some comments and dashboard explanatory text with this in mind.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, …

Dashboard and dashboard code get some clarifications

---

app/components/dashboard/audit_information_component.html.erb
app/components/dashboard/audit_status_component.html.erb
app/components/dashboard/complete_moabs_component.html.erb
app/components/dashboard/moab_storage_roots_component.html.erb
app/components/dashboard/object_versions_component.html.erb
app/components/dashboard/replication_endpoints_component.html.erb
app/components/dashboard/replication_files_component.html.erb
app/services/dashboard/audit_service.rb
app/services/dashboard/moab_on_storage_service.rb
app/services/dashboard/replication_service.rb
spec/services/dashboard/audit_service_spec.rb
spec/services/dashboard/moab_on_storage_service_spec.rb
spec/services/dashboard/replication_service_spec.rb

The goal here is to make the erb files more straightforward.
Fixes #2079

dashboard view components: moving more logic to ruby

---

app/services/zip_delivery_service.rb
spec/services/zip_delivery_service_spec.rb

These errors must be surfaced so we can address them.  Automatic retries won't fix them, and allowing the `CatalogToArchive` audit to backfill missing parts ... will never address this either.   So let's report the error.
Fixes #2041 
new unit test
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview …

ZipDeliveryService notifies Honeybadger if s3 part exists already

---

.rspec
spec/spec_helper.rb

I find this very helpful while developing -- I often want to debug a part of the code and being able to more easily spot "which specs in the individual file I am running are failing" is great. …

when running a single spec file, run tests in order

---

app/components/dashboard/audit_information_component.html.erb
app/components/dashboard/complete_moabs_component.html.erb
app/services/dashboard/moab_on_storage_service.rb
spec/services/dashboard/moab_on_storage_service_spec.rb

1.  we get expired checksums for replicated ZipPart and for CompleteMoab so ... let's distinguish better.
2.  get a little more logic out of erb files.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/j …

refactor: clearer method name in Dashboard::MoabOnStorageService

---

app/components/dashboard/audit_information_component.html.erb

I noticed the styling was incorrect.  Whoopsie!

dashboard audit_info_component: fix table styling error

---

config/schedule.rb

The HB URL needed a close quote to run. Fixes #2099

Close quote for HB URL

---

config/schedule.rb

cron on `preservation-catalog-prod-04` was sending email because curl's diagnostic output was being sent to stderr, which caused cron to think something was wrong. This change tells curl to be silent, and removes some of the unneeded quoting so that the cron entries are easier to read. The `:output` for runner_hb was also positioned earlier since curl will be quiet.
The two different styles of resulting cron entries now look like:
```
0 0 * * 3 /bin/bash -l -c 'cd /opt/app/pres/preservation_catalog/releases/20221207173228 && bin/rails runner -e production "PreservedObject.archive_check_expired.find_each(&:audit_moab_version_replication!)" >> /dev/null 2>> log/c2a-err.log && curl --silent https://api.honeybadger.io/v1/check_in/rkIdpB'
0 * * * * /bin/bash -l -c 'cd …
```

Silence curl and simplify quoting

---

app/components/dashboard/moab_storage_roots_component.html.erb
app/services/dashboard/moab_on_storage_service.rb
spec/components/dashboard/moab_storage_roots_component_spec.rb
spec/services/dashboard/moab_on_storage_service_spec.rb

Fixes #2013 - refactor some confusing code I wrote to be less confusing

Dashboard::MoabOnStorageService refactors for clarity

---

README.md
app/components/dashboard/audit_information_component.html.erb
db/README.md

Andrew mentioned recently that "integrity" was being used in a way that he found troubling:
> My suggestion was to use “completeness” to refer to a Moab that has all the manifests and all the files in the right places in the manifests (including size checks). I think of integrity including all of that plus checksums.
This PR attemtps to address that.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are …

update documentation around the word 'integrity'

---

.github/ISSUE_TEMPLATE/storage-migration-checklist-short.md
app/components/dashboard/audit_status_component.html.erb
app/components/dashboard/replication_status_component.html.erb
app/controllers/api_controller.rb
spec/components/dashboard/audit_status_component_spec.rb
spec/components/dashboard/replication_status_component_spec.rb

because we switched to sidekiq.
Fixes #2090 
CI

resque references become sidekiq references

---

app/jobs/concerns/unique_job.rb

acknowledge that it's confusing that we continue to use borrowed old resque-lock code for enforcing job uniqueness with Sidekiq.
(thanks to @ndushay for the suggestion)
PR review, documentation only …

UniqueJob: update comment about borrowed code to reduce confusion

---

app/components/dashboard/zip_parts_suffixes_component.html.erb
app/models/replication/druid_version_zip.rb
app/views/dashboard/_replication_information.html.erb
spec/components/dashboard/zip_parts_suffixes_component_spec.rb
spec/jobs/zipmaker_job_spec.rb
spec/models/replication/druid_version_zip_spec.rb

Fixes #2037
Since it IS a hardcoded constant, and since it was hard for me to find when writing the dashboard views, this was warranted.
CodeClimate is out of it's little mind.
specs and CI …

Replication::DruidVersionZip gets ZIP_SPLIT_SIZE constant instead of zip_split_size method

---

app/components/dashboard/zip_parts_suffixes_component.html.erb
app/components/dashboard/zip_parts_suffixes_component.rb
spec/components/dashboard/zip_parts_suffixes_component_spec.rb

Fixes #2027
To put `.z100` after `.z99`, for example:
(no image because need to deploy to prod for zips that are split into 100 parts)
unit test, runnning locally and on stage …

dashboard: sort zip part suffixes numerically

---

app/services/dashboard/moab_on_storage_service.rb
app/services/dashboard/replication_service.rb
spec/services/dashboard/replication_service_spec.rb

I started a PR for dashboard performance improvemets a while back.  These are simple memoizations that may help performance a bit.  It seemed better to do this than throw away the work.
Part of #2084.
CI …

dashboard services get memoization for perf improvement

---

config/schedule.rb

I didn't intend to hijack the rake job type.

Fix to rake hb whenever job type.

---

README.md

Fix to Audit::MoabToCatalog module.

---

README.md

Add a broad overview and diagram of prescat to help orient people to
what it is, and what its function is in the larger SDR service landscape.
Closes #1971
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/a …

Added an overview

---

app/components/dashboard/audit_information_component.html.erb

short answer:  because some things are non-obvious and the audit information part of the dashboard seems like a useful place for them.
longer answer:  I was looking to get rid of some github labels and encountered issue #490
Closes #490 
Related to #2010
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for …

dashbaord audit information gets a couple of notes

---

app/components/dashboard/audit_information_component.html.erb
app/components/dashboard/moab_storage_roots_component.html.erb
app/components/dashboard/replication_flow_component.html.erb
app/views/dashboard/_moab_information.html.erb
app/views/dashboard/_replication_information.html.erb

closes #2124
Local.
Tables with side-by-side layout changed to vertical layout since tables don't play well in columns.
Wide tables …

Adjust table layout.

---

Dockerfile

Update to a supported Docker image.

---

app/models/moab_record.rb

refs #2084
Faster dashboard.
Rails console.

Tweaks slow query.

---

db/migrate/20221220212633_add_index_to_zip_parts.rb
db/schema.rb

refs #2084
Address slow queries:
```
{"time":"2022-12-20T09:56:00-08:00","duration_ms":1980,"source":"Dashboard::AuditInformationComponent.num_replication_errors (line 51)","query":"SELECT COUNT(*) FROM 'zip_parts' WHERE 'zip_parts'.'status' != $1","bindings":[0]}
{"time":"2022-12-20T09:56:03-08:00","duration_ms":3204,"source":"Dashboard::ReplicationStatusComponent.num_replication_errors (line 51)","query":"SELECT COUNT(*) FROM 'zip_parts' WHERE 'zip_parts'.'status' != $1","bindings":[0]}
```
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) …

Adds index to ZipParts.

---

README.md
app/services/dashboard/audit_service.rb
app/services/dashboard/moab_on_storage_service.rb
app/services/dashboard/replication_service.rb
app/services/instrumentation_support.rb
config/initializers/slow_queries.rb
config/settings.yml
config/settings/development.yml
lib/slow_query_logger.rb
spec/services/dashboard/moab_on_storage_service_spec.rb
spec/spec_helper.rb

refs #2084
Support targeted performance instrumentation (in particular, for the dashboard).
Tested on stage.

Adds query performance instrumentation.

---

app/models/preserved_object.rb

refs #2084
Speed
Rails db / console

Speed up PreservedObject.archive_check_expired

---

app/services/dashboard/replication_service.rb

Faster dashboard
Rails / db console

Replication error query

---

app/jobs/moab_replication_audit_job.rb
spec/jobs/moab_replication_audit_job_spec.rb

closes #2142
Avoid unnecessary HB alerts.
Unit

Do not audit replication parts when backfilling.

---

.github/pull_request_template.md
app/components/dashboard/replication_flow_component.html.erb
app/jobs/README.md
app/jobs/abstract_delivery_job.rb
app/jobs/delivery_dispatcher_job.rb
app/jobs/results_recorder_job.rb
app/jobs/zipmaker_job.rb
app/models/zip_part.rb
spec/jobs/delivery_dispatcher_job_spec.rb
spec/jobs/integration_spec.rb
spec/jobs/zipmaker_job_spec.rb

more obvious naming makes maintenance easier.
Part of #2063

rename PlexerJob to DeliveryDispatcherJob

---

app/components/dashboard/replication_status_component.rb
app/services/dashboard/replication_service.rb
spec/services/dashboard/replication_service_spec.rb

Speed up replication status

---

app/components/dashboard/replication_files_component.html.erb
app/services/dashboard/replication_service.rb
spec/components/dashboard/replication_files_component_spec.rb
spec/controllers/dashboard_controller_spec.rb
spec/services/dashboard/replication_service_spec.rb

refs #2084
This query is slow and not crucial.

Remove total zip part size.

---

app/components/dashboard/replication_files_component.html.erb
app/services/dashboard/replication_service.rb

Improve performance and move some hidden queries out of the component views.
Prod

Changes for performance of replication files component.

---

app/views/dashboard/index.html.erb

For dashboard, do not load any tabs by default.

---

app/controllers/objects_controller.rb
app/jobs/validate_moab_job.rb

You pick:
1.  to make it clear why ValidateMoabJob is not considered an audit job, strictly speaking
2. to make hidden information readily available to any that peruse this code.
3. unknown reasons
4. all of the above
5. 1 and 2 only.
it's just comments.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation_**, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see …

add comments about use of ValidateMoabJob

---

app/views/dashboard/index.html.erb
spec/controllers/dashboard_controller_spec.rb

Remove unnecessary dashboard render.

---

app/services/audit_reporters/audit_workflow_reporter.rb
app/services/audit_reporters/base_reporter.rb
app/services/audit_reporters/event_service_reporter.rb
app/services/audit_reporters/honeybadger_reporter.rb
app/services/audit_reporters/logger_reporter.rb
app/services/audit_reporters/message_helper.rb
app/services/audit_results_reporter.rb
spec/controllers/catalog_controller_spec.rb
spec/services/audit/catalog_to_moab_spec.rb
spec/services/audit/checksum_validator_spec.rb
spec/services/audit/checksum_validator_utils_spec.rb
spec/services/audit_reporters/audit_workflow_reporter_spec.rb
spec/services/audit_reporters/event_service_reporter_spec.rb
spec/services/audit_reporters/honeybadger_reporter_spec.rb
spec/services/audit_reporters/logger_reporter_spec.rb
spec/services/audit_results_reporter_spec.rb
spec/services/catalog_utils_spec.rb
spec/services/moab_record_service/check_existence_spec.rb
spec/services/moab_record_service/create_after_validation_spec.rb
spec/services/moab_record_service/create_spec.rb
spec/services/moab_record_service/update_version_after_validation_spec.rb
spec/services/moab_record_service/update_version_spec.rb

per discussion 2023-01-09, this clarifies that the classes in the namespace are used only by the audit_results_reporter
specs.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation_**, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/README.md …

AuditReporters namespace instead of Reporters for clarity

---

app/services/audit/replication_support.rb
lib/tasks/prescat.rake

Easier troubleshooting by providing debug info from clound endpoints.
Prod

Adds checking of cloud endpoint to zip_part_debug_info

---

app/jobs/replication/delivery_dispatcher_job.rb
spec/jobs/replication/delivery_dispatcher_job_spec.rb

closes #2172
Allow retry of DeliveryDispatchJob for partially replicated moabs.
Unit

Do not attempt to replicate to endpoints that are already replicated.

---

app/components/dashboard/replication_files_component.html.erb
spec/components/dashboard/replication_files_component_spec.rb
spec/controllers/dashboard_controller_spec.rb

Slow queries that didn't add actionable info.
Unit

Remove total zipparts and ok from replication files dashboard.

---

.rubocop.yml
Gemfile.lock
app/components/dashboard/replication_endpoint_status_component.html.erb
app/components/dashboard/replication_endpoint_status_component.rb
app/components/dashboard/replication_status_component.html.erb
app/components/dashboard/replication_status_component.rb
app/components/spinner.rb
app/services/dashboard/replication_service.rb
spec/components/dashboard/replication_endpoint_status_component_spec.rb
spec/components/dashboard/replication_status_component_spec.rb

Fixes #2089
* Extract replication endpoint status component
* Extracts a new subcomponent of the replication status component to reflect that endpoint replication statuses are distinct from the overall replication status. In doing this work, move logic out of component ERB templates into the component Ruby (reducing logic in views).
* Update rubocop version and config and make it happy
Tested locally and in QA

Extract replication endpoint status component

---

app/services/audit/replication_support.rb
lib/tasks/prescat.rake

More helpful replication diagnosis.
QA

Adds additional fields to replication diagnosis.

---

.circleci/config.yml
Dockerfile

So that docker image will build.

Allow installing Sidekiq Pro in docker image.

---

app/services/audit/catalog_to_moab.rb
app/services/audit/checksum_validator_utils.rb
app/services/catalog_utils.rb
spec/services/catalog_utils_spec.rb

Rename log files for clarity

---

config/initializers/okcomputer.rb
spec/config/okcomputer_spec.rb

closes #2195
This is an expensive test to be performing every few seconds.

Remove OKComputer feature-version-audit-window-check.

---

app/services/audit/checksum_validator.rb
config/application.rb
spec/services/audit/checksum_validator_utils_spec.rb

- build is currently broken, see e.g. [here](https://app.circleci.com/pipelines/github/sul-dlss/preservation_catalog/1847/workflows/fe1b590e-b835-4700-8a46-ce82d2a2b040/jobs/4702/tests#failed-test-0).  this gets rid of a couple straggler references to `cv.log`
- we're getting some annoying deprecation warnings from `Committee::Middleware::RequestValidation`, which the config param here should silence
unit/CI, `preassembly_image_accessioning_spec.rb` and `preassembly_hfs_accessioning_spec.rb`
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against …

Fix build and silence deprecation warning

---

app/services/audit_reporters/audit_workflow_reporter.rb
app/services/audit_reporters/honeybadger_reporter.rb

this can happen when pres robots alerts pres cat to a moab version that's already been cataloged, as might happen when the update-catalog workflow step sits after having failed, and the moab version is detected by e.g. moab-to-catalog audit before the step is retried.
it's unusual, and worth a glance, but shouldn't wedge preservation or accessioning workflows.
will take this out of draft if/when https://github.com/sul-dlss/preservation_robots/pull/469 is merged.
once this and the pres robots PR are merged and deployed, we should (hopefully) be able to easily clear the druids wedged at the `update-catalog` step atm, by using argo to reset the workflow step en masse, instead of manually marking the step complete for individual druids (whether via argo show page or WFS rails console/rake …

move Audit::Results::DB_OBJ_ALREADY_EXISTS from audit workflow report codes to honeybadger report codes

---

app/controllers/catalog_controller.rb
openapi.yml
spec/controllers/catalog_controller_spec.rb

follow on to https://github.com/sul-dlss/preservation_robots/pull/469 and https://github.com/sul-dlss/preservation-client/pull/97
discovered during integration testing on QA of (the updated pres client consumers):
- https://github.com/sul-dlss/dor-services-app/pull/4358
- https://github.com/sul-dlss/argo/pull/3948
- https://github.com/sul-dlss/happy-heron/pull/3006
- https://github.com/sul-dlss/preservation_robots/pull/469
the only trouble spot was that pres robots' updated pres client call is now sending a `Content-Type` of `application/json` instead of `application/x-www-form-urlencoded`.  that resulted in errors like:
addressed in first commit:
```
Preservation::Client::UnexpectedResponseError: Preservation::Client.http_response got 400 from Preservation at v1/catalog: …
```

openapi spec: allow POST/PUT/PATCH requests to /v1/catalog* to use Content-Type=application/json

---

lib/tasks/prescat.rake

Add rake task for validating checksum of single druid.

---

lib/tasks/prescat.rake

Adds rake task for running replication audit for a single druid.

---

lib/tasks/prescat.rake

So rake task correctly handles boolean arg.

Fix to prune rake task.

---

Gemfile
Gemfile.lock
app/jobs/concerns/unique_job.rb
config/resque.yml
spec/support/job_config.rb

Upgrade to Sidekiq7.

---

config/schedule.rb

Less confusion is good for all.

schedule.rb - improve comments

---

.rubocop.yml

Rubocop updates.

---

config/schedule.rb

Executing with the default runner was failing.
```
0 20 * * * /bin/bash -l -c 'cd /Users/jlittman/data/sdr/preservation_catalog && bin/rails runner -e production "PreservedObject.order(last_archive_audit: :asc).limit(PreservedObject.daily_check_count).find_each(&:audit_moab_version_replication!)" >> /dev/null 2>> log/c2a-err.log'
0 22 * * * /bin/bash -l -c 'cd /Users/jlittman/data/sdr/preservation_catalog && bin/rails runner -e production "MoabRecord.order(last_checksum_validation: :asc).limit(MoabRecord.daily_check_count).find_each(&:validate_checksums!)" >> /dev/null 2>> log/cv-err.log'``
```
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss …

Do not bundle exec when using runner in whenever.

---

config/deploy/stage.rb

Prescat does not use newrelic (not even in the Gemfile), and the newrelic.yml file is removed from shared_configs.

Remove newrelic from stage deploy steps

---

config/deploy/qa.rb

Prescat does not use newrelic (not even in the Gemfile), and the newrelic.yml file is removed from shared_configs.

Remove newrelic from qa deploy steps

---

.circleci/config.yml

It now defaults to Ruby 3.2.2 and has all the latest orb deps.
Keep pace with change.
CI

Update to latest CI orb

---

app/views/dashboard/_replication_endpoints.html.erb

Because I think the wiki page is now stable enough to warrant linking from the part of the dashboard where we would most like to see it.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation_**, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs …

add link to replication errors wiki in dashboard

---

.github/pull_request_template.md

same heading cleanup that @mjgiarlo has been doing in our other PR templates, plus freshen a stale doc link
⚡ ⚠ Please …

Normalize headings in pull_request_template.md, update replication diagram link

---

README.md
app/services/catalog_utils.rb
spec/services/catalog_utils_spec.rb

* remove some redundancy from the README
* fix some ambiguous/unnecessary Rails terminology re-use in our own util methods and documentation, see https://github.com/sul-dlss/preservation_catalog/issues/1154
* part of sul-dlss/argo#4052
* closes sul-dlss/preservation_catalog#1154
CI, and a slightly different version of the reset procedure will be tried as part of the upcoming QA and stage reset (see this [comment describing the one-off this first reset will use](https://github.com/sul-dlss/argo/issues/4052#issuecomment-1690550978))
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassem …

add instructions for doing a complete reset of QA or stage (including wiping out preserved SDR content), other touchups

---

openapi.yml
spec/requests/objects_controller_checksums_spec.rb

⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation (including cloud replication)_**, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/wiki/Replication-Flow).⚡
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA …

Remove unnecessary json suffix from endpoint.

---

Gemfile
Gemfile.lock
app/jobs/concerns/unique_job.rb
config/initializers/redis.rb
config/initializers/sidekiq.rb
config/settings.yml

To try to address redis timeouts in production.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation (including cloud replication)_**, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/wiki/Replication-Flow).⚡
Ran c2m and sdr deposit spec in stage.
⚡ ⚠ Please …

Adds connection pool for redis. Increases timeout for redis.

---

app/jobs/validate_moab_job.rb
app/services/audit_reporters/audit_workflow_reporter.rb
app/services/audit_reporters/event_service_reporter.rb
app/services/audit_reporters/honeybadger_reporter.rb
spec/services/audit/checksum_validator_spec.rb

ideally we would've done this at the time we added the check, but we forgot, and then declined to fix it at the time because QA and stage were a mess, and we were worried about noise.  now that QA and stage have been reset, we should have less concern about noise, so we'll see how widespread an issue this is in prod.  see https://github.com/sul-dlss/preservation_catalog/pull/1993
CI
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation (including cloud replication)_**, and/or test in stage environment, in addition …

Report ZIP_PARTS_SIZE_INCONSISTENCY to HB and event service, and other smallt touchups

---

app/services/audit_reporters/audit_workflow_reporter.rb

Remove replication-related result codes from audit workflow reporter

---

Gemfile
Gemfile.lock

pinning is only useful when it's to solve a problem, and even then, an explanation of the problem or what is needed to unpin should be provided.
I left a bunch of gems pinned as I think they might have more impact (sidekiq, redis, rails, aws-sdk ...)
CI.

unpin gems

---

Gemfile
Gemfile.lock

To void getting breaking v2.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation (including cloud replication)_**, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/wiki/Replication-Flow).⚡
⚡ ⚠ Please ensure this change does not introduce accessibility …

Pin turbo to avoid getting 2.

---

Capfile
Gemfile
Gemfile.lock
app/javascript/application.js
app/views/layouts/application.html.erb
bin/importmap
config/deploy.rb
config/importmap.rb

closes #2288
So that dashboard will render.
QA
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation (including cloud replication)_**, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/wiki/Replication-Flow).⚡
⚡ ⚠ Please ensure this change does not introduce …

Switch to importmap and propshaft.

---

.github/pull_request_template.md
config/initializers/okcomputer.rb
docker-compose.yml
spec/config/okcomputer_spec.rb

* add okcomputer check for expected RabbitMQ queues as suggested in https://github.com/sul-dlss/preservation_catalog/issues/2291 (ironically, it was added to a [few](https://github.com/sul-dlss/happy-heron/pull/3436) [other](https://github.com/sul-dlss/dor-services-app/pull/4661) [apps](https://github.com/sul-dlss/dor_indexing_app/pull/1073) before pres cat).
* bump redis in docker compose to currently deployed major version
* freshen PR template (fix reference to renamed infra integration test, add a little whitespace to testing hint for readability)
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/s …

Okcomputer 🐇 check and misc touchups

---

bin/gis_remediation

This is a temporary utility to help in GIS remediation. Currently it is only checking to see if a `data.zip` can be found in preservation. For context see: https://github.com/sul-dlss/gis-robot-suite/issues/829
The utility will be modified to extract files from the data.zip and write them to an external location. Once it has been used, and remediation is complete it can be deleted.
It was run in prescat stage.

A tool to identify which GIS items have a data.zip

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/objects_controller.rb
app/services/audit/checksum_validator_utils.rb
app/services/moab_storage_root_report_service.rb
lib/tasks/prescat.rake
spec/services/catalog_utils_spec.rb

The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/wiki/Replication-Flow).⚡
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA …

Bump Ruby to 3.3.1

---

README.md

fix docker hub and openapi validation status badges
* badge service previously in use for docker hub seems defunct, use a working image and link directly to docker hub
* need to make openapi validation link https
via markdown preview:
before fix:
after this PR:
no

[README] fix badges

---

app/services/audit/checksum_validator.rb
lib/tasks/prescat.rake
spec/services/audit/checksum_validator_spec.rb

tweak call in `prescat:audit:validate_uncataloged` rake task to call `validate` instead of `validate!` (small method rename since the method doesn't have side-effects).
this got the rake task working in my basic command line testing, otherwise i got e.g.
```
% be rake  prescat:audit:validate_uncataloged\['bj102hs9687','spec/fixtures/storage_root01/sdr2objects/'\]
Starting checksum validation for bj102hs9687 in spec/fixtures/storage_root01/sdr2objects/ (NOTE: this may take some time!)
rake aborted!
NoMethodError: undefined method 'validate!' for an instance of Audit::ChecksumValidator (NoMethodError)
).validate!
^^^^^^^^^^
```
after that i got e.g.
```
% be rake  prescat:audit:validate_uncataloged\['bj102hs9687','spec/fixtures/storage_root01/sdr2objects/'\] …
```

add missing Audit::ChecksumValidator#validate method

---

spec/jobs/application_job_spec.rb
spec/jobs/replication/integration_spec.rb
spec/support/job_config.rb

Flappy specs make for grumpy developers.
Closes #2394 
I used an RSpec seed from a failing build in CI and analyzed which tests were running when. From there I was able to determine that the application job spec *always* fails when run after the replication integration spec. That led me to removing all the manual queue adapter jazz and making job specs consistently use the test adapter. I have now run the job specs in the same order as used to reproducibly fail about thirty times in a row with no failures, and run the whole suite a bunch of times with other random seeds. Looks better to me now, at least.
I suspect that this used to work just fine, but then the job testing harness and adapter defaults changed circa Rails 5-to-6 or 6-to-7.
See above.

Deflappify application job spec

---

config/settings.yml

requested by @julianmorley in slack conversation: https://stanfordlib.slack.com/archives/C04D8DJDRJ9/p1743787754692749
The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/wiki …

per request from ops, halve expiry time for the zip files that we generate to send to cloud archive endpoints

---

app/jobs/replication/gcp_delivery_job.rb
app/services/replication/gcp_provider.rb
config/settings/test.yml
spec/jobs/audit/moab_replication_audit_job_spec.rb
spec/jobs/replication/integration_spec.rb
spec/models/zip_endpoint_spec.rb
spec/services/audit/replication_to_gcp_spec.rb
spec/services/replication/gcp_provider_spec.rb

more consistent naming for configurations that serve very similar purposes
The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/wiki/Replication-Flow).⚡
⚡ ⚠ Please ensure this …

GCP archive endpoint: better align zip_endpoint config name with AWS endpoint name convention

---

spec/services/replication/shared_examples_provider.rb

see e.g. `Aws::S3::Errors::AccessDenied` error at https://app.circleci.com/pipelines/github/sul-dlss/preservation_catalog/2455/workflows/98b3ce04-c6a6-44d4-9b46-c19e8f47281c/jobs/6663
@edsu ran into this issue when working on dependency updates this week.  we thought something like this would be a reasonable fix when pairing.
The main classes relevant to replication are …

avoid possible S3 key conflict conflict in live S3 test

---

app/jobs/replication/gcp_delivery_job.rb
app/services/replication/gcp_provider.rb
config/settings/test.yml
spec/jobs/audit/moab_replication_audit_job_spec.rb
spec/jobs/replication/integration_spec.rb
spec/models/zip_endpoint_spec.rb
spec/services/audit/replication_to_gcp_spec.rb
spec/services/replication/gcp_provider_spec.rb

turns out the new endpoint is going to be in the US south region afterall, for parity with IBM, since that region was chosen specifically for geographic diversity compared to the AWS endpionts (which aren't changing in any way at present).
i have an idea, which i'll ticket, for making the code more flexible with respect to hardcoded endpoint names in settings references and the need to coordinate endpoint names across all environments because of the hardcoding.  for now, churn for accuracy and expediency.
there is a current puppet PR for access info in stage and prod that lines up with this PR.  i'll update QA settings in shared_configs and puppet to match this PR, and will deal with the cleanup for in flight jobs (QA GCP creds already needed rotating due to a desire to switch it to a new …

update gcp endpoint setting name again

---

Gemfile
Gemfile.lock
app/jobs/validate_moab_job.rb
app/services/audit_reporters/audit_workflow_reporter.rb
config/initializers/dor_services_client.rb
config/settings.yml
spec/jobs/validate_moab_job_spec.rb
spec/services/audit_reporters/audit_workflow_reporter_spec.rb

Fixes #2442 
The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/wiki/Replication-Flow).⚡
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the …

Switch to dor-services-client over dor-workflow-client

---

.github/pull_request_template.md
.rubocop.yml
app/components/dashboard/audit_information_component.html.erb
app/models/replication/druid_version_zip.rb
app/services/audit/replication.rb
config/settings.yml
lib/tasks/prescat.rake
spec/jobs/application_job_spec.rb
spec/models/zip_endpoint_spec.rb

* add GCP awareness to `purge_zips` rake task
* update old page text and check names to get rid of missed cruft from `PartReplicationAuditJob` to `MoabReplicationAuditJob` transition
* explain strategy for a moderately complicated set of query tests (because it took me a bit to figure it out again myself when i went to update for GCP endpoint addition, and i was the original author)
* add new rubocop rules (and make small change for one of them)
* explanatory comment on archive zip size check
* freshen PR template
* remove obsolete setting
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_reaccessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/pre …

various maintenance
