sul-dlss/preservation_catalog

- README.md
Creating a username, password, and database in postgresql.
> Add postgresql setup to readme

- .gitignore
- Gemfile
- Gemfile.lock
- config/application.rb
- config/initializers/config.rb
- config/settings.yml
> Add config gem so we can use Settings.yml etc.

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- app/models/endpoint.rb
- app/models/preservation_copy.rb
- app/models/preserved_object.rb
- config/database.yml
- db/migrate/20170823232731_create_preserved_objects.rb
- db/migrate/20170823233116_create_endpoints.rb
- db/migrate/20170823233217_create_preservation_copies.rb
- db/schema.rb
- spec/models/endpoint_spec.rb
- spec/models/preservation_copy_spec.rb
- spec/models/preserved_object_spec.rb
- spec/rails_helper.rb
A first pass at the tables and models needed for the object inventory store: preserved_objects (a master record covering all preserved copies for a given druid), endpoints (unique replication targets), and preservation_copies (individual preserved copies of preservation objects, on specific endpoints).
paired w/ @SaravShah on implementation.  met w/ @LynnMcRae and @julianmorley to refine schema choices (meeting w/ @julianmorley again this afternoon for further schema refinement).
supersedes #28 
Resolves #16
Resolves #17
Resolves #31
> initial schema and database configuration

- spec/controllers/moab_storage_controller_spec.rb
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/data/metadata/contentMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/data/metadata/descMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/data/metadata/identityMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/data/metadata/provenanceMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/data/metadata/relationshipMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/data/metadata/rightsMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/data/metadata/technicalMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/data/metadata/versionMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/data/metadata/workflows.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/manifests/fileInventoryDifference.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/manifests/manifestInventory.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/manifests/signatureCatalog.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/manifests/versionAdditions.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0001/manifests/versionInventory.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/data/metadata/descMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/data/metadata/events.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/data/metadata/provenanceMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/data/metadata/versionMetadata.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/data/metadata/workflows.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/manifests/fileInventoryDifference.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/manifests/manifestInventory.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/manifests/signatureCatalog.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/manifests/versionAdditions.xml
- spec/fixtures/moab_storage_root/jj/925/bx/9565/jj925bx9565/v0002/manifests/versionInventory.xml
it's nice to have a small fixture that works
> add fixture jj925bx9565

- app/controllers/moab_storage_controller.rb
Resolves #24
Turns out there was a simpler way!  W00t!
> moab_storage_controller: improve how we get current version for a druid

- app/controllers/moab_storage_controller.rb
- Used updated moab-versioning gem for object_size method
connects to #61
> Change object_size method

- config/routes.rb
- spec/controllers/catalog_controller_spec.rb
Changed POST to PATCH
connects to #58
> Update to PATCH method

- spec/controllers/catalog_controller_spec.rb
Spec file: change put to patch
connects to #58
> Update put to patch

- .simplecov
- lib/benchmarking/postgres_testing.rb
> Add benchmark script

- README.md
- Rakefile
- config/database.yml
- db/scripts/pcc_test_setup.sql
- db/scripts/preservation_core_catalog_setup.sql
- Only changed preservation_core_catalog to pcc_test
- haven't done anything with dev or prod
connects #94
> Change preservation_core_catalog db to pcc_test db

- app/models/preservation_policy.rb
- db/migrate/20170928181349_add_archive_ttl_and_fixity_ttl_to_preservation_policies.rb
- db/schema.rb
- spec/models/preservation_copy_spec.rb
- spec/models/preservation_policy_spec.rb
- spec/models/preserved_object_spec.rb
Adds migration and validations, documentation and updated specs
Closes #127
> Add ttls for archive and fixity to preservation_policies

- db/migrate/20171002192320_change_size_type_in_preserved_objects.rb
- db/schema.rb
-Change_column :preserved_object, :size, :bigint
closes #143
> Change size type in preserved objects to bigint

- app/models/status.rb
- db/migrate/20171005204015_add_index_to_statuses.rb
- db/schema.rb
- spec/models/status_spec.rb
Create migration to add index and uniqueness as well as rspec tests
connects #138
> Update statuses.status text model

- db/migrate/20171006193035_add_index_to_preserved_objects.rb
- db/migrate/20171006193131_add_index_to_endpoints.rb
- db/schema.rb
- spec/models/endpoint_spec.rb
- spec/models/preserved_object_spec.rb
- added unique constraint on indices 
- added corresponding tests
connects #163
> update unique constraint to columns and rspec tests

- spec/models/endpoint_spec.rb
- spec/models/preservation_policy_spec.rb
> fix skipped tests for Endpoint.default_storage_root_endpoint_type and PreservationPolicy.default_preservation_policy

- app/models/preservation_policy.rb
- app/models/status.rb
- config/settings.yml
- spec/models/status_spec.rb
Resolves #152 - uses value in Settings.yml for default_status.
also found an errant comment from before we had defaults set in settings.yml.
> added default status

- app/services/preserved_object_handler.rb
- spec/services/preserved_object_handler_spec.rb
> PreservedObjectHandler: create method rescues ActiveRecordError

- spec/services/preserved_object_handler_spec.rb
This is preparatory work for writing update_version  method (which will use these shared examples).
connected to #218 
This isn't rocket science, so don't need all of you to review.
One question is "am I checking that rails ActiveRecord validation works?" or "am I checking that the error messages are what we want, informative, and that we actually call validation appropriately early in the methods?"  Dunno.
> pohandler_spec: use shared_examples to check for attribute validation

- app/models/moab_storage_directory.rb
> require find

- .travis.yml
> Update travis to match ruby version on vm

- app/models/endpoint.rb
- app/models/preserved_copy.rb
- app/models/preserved_object.rb
- app/models/status.rb
- app/services/preserved_object_handler.rb
- db/migrate/20171101194518_rename_preservation_copies_to_preserved_copies.rb
- db/schema.rb
- lib/audit/catalog_to_moab.rb
- spec/load_fixtures_helper.rb
- spec/models/endpoint_spec.rb
- spec/models/preserved_copy_spec.rb
- spec/models/preserved_object_spec.rb
- spec/models/status_spec.rb
- spec/services/preserved_object_handler_spec.rb
- paired with @tingulfsen 
closes #186
> change PreservationCopy to PreservedCopy

- app/models/preserved_copy.rb
- app/models/preserved_object.rb
- app/services/preserved_object_handler.rb
- db/migrate/20171101203342_add_size_to_preserved_copies.rb
- db/migrate/20171101203630_remove_size_from_preserved_objects.rb
- db/schema.rb
- spec/models/preserved_copy_spec.rb
- spec/models/preserved_object_spec.rb
- spec/services/preserved_object_handler_spec.rb
Fixes #235 
(paired with Sarav - he told me to do this stuff, so if it doesn't work it's his fault)
> Move size column from PreservedObject to PreservedCopy

- db/migrate/20171101214052_add_storage_location_index_and_endpoint_node_to_endpoints.rb
- db/schema.rb
- spec/models/endpoint_spec.rb
> Add index to storage_location and endpoint_node as well as RSpec tests

- app/models/preserved_copy.rb
- app/services/preserved_object_handler.rb
- db/migrate/20171101214666_rename_current_version_to_version_in_preserved_copies.rb
- db/schema.rb
- spec/models/preserved_copy_spec.rb
- spec/services/preserved_object_handler_spec.rb
> PreservedCopy.version not .current_version

- lib/audit/moab_to_catalog.rb
- spec/lib/audit/moab_to_catalog_spec.rb
> Add method to loop through all the storage roots when seeding.

- config/deploy/dev.rb
> Remove cap stage for sul-pcc-dev: the machine is gone

- spec/services/preserved_object_handler_spec.rb
resolves #239 (and shortens spec file a bit)
> Refactor poh specs

- spec/services/preserved_object_handler_spec.rb
trying to make it shorter without losing "clarity" - hahaha
removes about 30 lines of duplicated content ...
> Refactor pohandler spec

- config/settings.yml
- spec/models/status_spec.rb
> settings.yml: add invalid_moab status

- Gemfile.lock
> Update moab-versioning to v2.5.0

- Rakefile
so it shows up when you do a `rake -T` from console
> add a description to the seed_catalog rake task

- Gemfile.lock
> update moab versioning gem

- app/services/preserved_object_handler.rb
~~this builds on #296, so that should get merged before this, and then this should get rebased on master.~~
provides endpoint class differentiation to start addressing the concern from #264 
connects to #264
> POH#update_version differentiates by endpoint class

- Gemfile
- Gemfile.lock
- config/deploy/stage.rb
on stage, this is turned off for the moment
in newrelic.yml until we hook up robots
> Install newrelic gem for performance monitoring

- app/models/status.rb
- app/services/preserved_object_handler.rb
- spec/services/preserved_object_handler_create_spec.rb
~~WIP because Stanford::StorageObjectValidator fails fast on invalid moabs and it shouldn't~~ - Fixed ✔️ 
connects #177 
connects to #179
connects to #178
>  Add #create_with_validation to PO_handler

- lib/audit/moab_to_catalog.rb
- spec/lib/audit/moab_to_catalog_spec.rb
> moab_to_catalog.seed calls create_with_validation

- .rubocop.yml
- Rakefile
- lib/audit/moab_to_catalog.rb
Resolves #300
I didn't feel it was worth it to write tests to prove that these messages were in the logs or written to to STDOUT ...
> add timestamps to log and puts statements for seeding and M2C

- README.md
- Rakefile
Adds an argument to rake seed_catalog
to distinguish profiling runs
Fixes #275
> Document seeding the catalog

- app/services/preserved_object_handler.rb
The private method will also be used by update_version_after_validation.  :-)
> pohandler: refactor moab_validation_errors into private method

- .travis.yml
- app/services/preserved_object_handler.rb
- lib/audit/moab_to_catalog.rb
- spec/lib/audit/moab_to_catalog_spec.rb
- spec/services/preserved_object_handler_create_spec.rb
> pohandler method now named create_after_validation

- spec/services/preserved_object_handler_update_version_spec.rb
- implement the pending specs about update_version timestamp and status changes
- beef up the specs a bit in preparation for work on #283 
Connects to #287 -- it has the specs for timestamp and status updates expected for plain update_version
Connects to #283 -- it lays groundwork for the tests we will be changing for update_version_with_validation
> pohandler_update_vers_spec: beef up specs and code pending specs

- db/README.md
* obviously the first part needs to actually be filled in with schema explanation and probably a diagram
* part 3 ("some useful ActiveRecord queries") might be more appropriate in the wiki, not sure, but wanted to start capturing it somewhere
closes #281
> [WIP] start a readme about DB development

- .rubocop.yml
- app/models/status.rb
- app/services/preserved_object_handler.rb
- config/settings.yml
- spec/models/status_spec.rb
- spec/services/preserved_object_handler_create_spec.rb
- want to distinguish between objects failing moab validation and objects failing checksum validation.
connects #318
> 318 invalid moab status

- app/services/preserved_object_handler.rb
- spec/services/preserved_object_handler_create_spec.rb
- spec/services/preserved_object_handler_spec.rb
- spec/services/preserved_object_handler_update_version_spec.rb
here are some suggested fixes to #354 that felt easier to implement with commit comments than to suggest in comments on that PR
> Pohandler refactor touchups

- .rubocop.yml
- app/services/preserved_object_handler.rb
- spec/services/preserved_object_handler_create_spec.rb
- spec/services/preserved_object_handler_spec.rb
- spec/services/preserved_object_handler_update_version_spec.rb
Some small stuff I noticed while working on #352
Also, closes #360, which was created due to review comments.
> Pohandler refactor

- Gemfile.lock
- app/services/preserved_object_handler.rb
- config/settings.yml
- spec/services/preserved_object_handler_spec.rb
> PreservedObjectHandler uses setting to allow Moabs to have subdirs under data/content

- app/services/preserved_object_handler.rb
- spec/services/preserved_object_handler_spec.rb
> Stub preserved object handler check_existence method

- spec/services/preserved_object_handler_check_exist_spec.rb
there are still known failures for bad specs.
> more WIP on pohandler.check_existence specs

- spec/services/preserved_object_handler_check_exist_spec.rb
This concludes writing the new specs for check_existence before the code is fully functional.
Note that check_existence tests in `pohandler_spec` (plain) should be removed in favor of these specs.
The specs may not be perfect, but they are a reasonable attempt at testing the outcome(s) of calling check_existence under all the different conditions.
For the record, on my laptop, I get:  111 examples, 16 failures
>  pohandler.check_exists object not in db tests written 

- Rakefile
- lib/audit/moab_to_catalog.rb
- spec/lib/audit/moab_to_catalog_spec.rb
Add option to add profiler or not
closes #413
> Add profiler to .populate_endpoint

- app/services/preserved_object_handler.rb
- app/services/preserved_object_handler_results.rb
- spec/services/preserved_object_handler_check_exist_spec.rb
- spec/services/preserved_object_handler_confirm_version_spec.rb
- spec/services/preserved_object_handler_results_spec.rb
> Version mismatch error shows object versions in message

- app/services/preserved_object_handler.rb
- app/services/preserved_object_handler_results.rb
- spec/services/preserved_object_handler_check_exist_spec.rb
- spec/services/preserved_object_handler_confirm_version_spec.rb
- spec/services/preserved_object_handler_create_spec.rb
- spec/services/preserved_object_handler_results_spec.rb
- spec/services/preserved_object_handler_update_version_spec.rb
- spec/services/shared_examples_preserved_object_handler.rb
Some refactoring I did while working on #434 (improve audit timestamps).
Should be easy to review commit by commit.
> Refactoring happens

- spec/services/preserved_object_handler_confirm_version_spec.rb
- spec/services/preserved_object_handler_create_spec.rb
- Started refactoring `pohr.confirm_version` 
- Removed unused var in `pohr.create`
connects to #455
> Refactor pohr confirm version

- .gitignore
- .rubocop.yml
- lib/audit/catalog_to_moab.rb
- lib/audit/moab_to_catalog.rb
- spec/lib/audit/catalog_to_moab_spec.rb
- spec/lib/audit/moab_to_catalog_spec.rb
- spec/load_fixtures_helper.rb
- Also had to refactor moab_to_catalog output slightly to more easily distinguish between the two (C2M vs M2C).
- got load_fixtures_helper working 
- put guts of C2M into a separate method in catalog_to_moab, for now.
Connected to #108
> catalog-to-moab: add all methods needed for rake tasks and start working on C2M

- lib/audit/catalog_to_moab.rb
- spec/lib/audit/catalog_to_moab_spec.rb
This method could use some further specs, and that work is ticketed (connects to #476)
Fixes #460
> Add query to C2M check_version_on_dir

- lib/audit/catalog_to_moab.rb
hopefully keeping us from stepping on each other while doing critical path C2M work
> catalog_to_moab: add github issue numbers to TODO comments

- app/services/preserved_object_handler_results.rb
- added new stack_trace
- moved `result_hash`,  `report_errors_to_workflows` to private
- rename variable from `x` to `results`
> Test stack trace help

- .rubocop.yml
- README.md
- Rakefile
- Rake Task with and without profiling for `check_version_on_dir` and `check_version_all_dirs`
connects #461
> rake tasks for c2m methods

- lib/audit/catalog_to_moab.rb
I also reorganized the beginning of the method to help other PRs ...
Fixes #496
> catalog_to_moab: use storage dir attr to get moab

- lib/audit/catalog_to_moab.rb
- spec/lib/audit/catalog_to_moab_class_spec.rb
Fixes #487
Paired with @jmartin-sul 
Should just need 1 pair of eyes for review.
> Limit c2m SQL query by storage_dir

- lib/audit/catalog_to_moab.rb
This only needs one reviewer.  Who will be first?
> catalog_to_moab: tag comment about ensuring date format with #485

- .rubocop.yml
- app/services/preserved_object_handler_results.rb
- lib/audit/catalog_to_moab.rb
- spec/lib/audit/catalog_to_moab_instance_spec.rb
- Would like 2 reviewers to approve this before it gets merged
- Added 2 rubocop exceptions.
- Going commit by commit will probably be easiest to for reviewers
closes #482
1) One question:
Do we want to add any additional information, when sending the `ONLINE_MOAB_DOES_NOT_EXIST` error code?
> Moab exists on Catalog but does not exist online

- .rubocop.yml
- app/services/preserved_object_handler.rb
- app/services/preserved_object_handler_results.rb
- lib/audit/catalog_to_moab.rb
- spec/lib/audit/catalog_to_moab_instance_spec.rb
- spec/services/preserved_object_handler_check_exist_spec.rb
- spec/services/preserved_object_handler_confirm_version_spec.rb
- spec/services/preserved_object_handler_results_spec.rb
- spec/services/preserved_object_handler_update_version_spec.rb
- spec/services/shared_examples_preserved_object_handler.rb
Closes #478 
Could probably use more than 1 set of eyes, since this touches a lot of code.
> Use .save! instead of custom method to save db objects

- spec/services/audit_results_spec.rb
~~WIP until #532 is merged~~
Per a suggestion form @tallenaz on #530, I beefed up the spec for #remove_db_updated_results.  I also beefed up the logging specs.
> Audit results spec beefed up

- spec/services/preserved_object_handler_check_exist_spec.rb
- spec/services/preserved_object_handler_confirm_version_spec.rb
- spec/services/preserved_object_handler_update_version_spec.rb
- spec/services/shared_examples_preserved_object_handler.rb
~~WIP:  to be reviewed after #530 is merged~~
Winnow out some specs (about logging) for
- check_existence
- confirm_version
- update_version
- shared_examples
Closes #455
> pohandler specs check results array,  not results behavior

- README.md
Only needs 1 pair of eyes.
- Make sure to enter `last_checked_b4_date` as a String
> date/timestamp argument must be a string when entered into c2m_checks

- app/services/checksum_validator.rb
- spec/services/checksum_validator_spec.rb
something like this?
closes #511
> stub for ChecksumValidator service class and tests

- .rubocop.yml
- app/services/audit_results.rb
- spec/services/audit_results_spec.rb
1 reviewer??
~~WIP: until #551 is merged, then will rebase~~
Adds endpoint info and actual version info to error messages sent to workflows
Closes #528
> Workflow error msgs get endpoint and actual version info

- lib/audit/checksum.rb
- spec/lib/audit/checksum_spec.rb
I think this is what we are looking for, for now? 
closes #513
> stub for ChecksumValidator class and tests

- README.md
- Rakefile
Are the descriptions good enough?
closes #514
> Rake tasks

- Rakefile
and profile log name is capitalized
> Timestamp in c2m rake task argument is a string

- app/services/audit_results.rb
- app/services/checksum_validator.rb
- spec/services/checksum_validator_spec.rb
for when a moab passes CV
~~also adds a skipped test as a reminder~~
set up `validate_checksum` method and specs
wait till #594  is merge (still needs to rebase off master too)
connects #596
> Add MOAB_CHECKSUM_VALID code

- db/README.md
- Add SQL query to get all druids for a given endpoint
> View the druids on  a given endpoint

- lib/audit/checksum.rb
- spec/lib/audit/checksum_spec.rb
Takes in strg_root_name and not strg_root_location
> This method takes in endpoint_name not storage_dir

- app/services/checksum_validator.rb
- spec/services/checksum_validator_spec.rb
When a moab does not have the correct file or directory, the rake task would throw an error. 
```
be rake cv_all_endpoints  
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - spec/fixtures/storage_root02/moab_storage_trunk/yy/000/yy/0000/yy000yy0000/v0001/manifests/signatureCatalog.xml
```
connects #618
> (CV) Fix rake aborted bug when moab does not have correct file or dir

- README.md
- Rakefile
- lib/audit/checksum.rb
- spec/lib/audit/checksum_spec.rb
Update ReadME w/ usage info
Add Rake task
Add method in `checksum.rb` w/ Spec
connects #587
> Rake task druid

- Gemfile.lock
version 2.5.0.4 was pulled from rubygems
> Update parser gem

- Capfile
- Gemfile
- Gemfile.lock
To automate shared_configs tasks on deployment
> Add capistrano-shared_configs gem

- spec/services/shared_examples_preserved_object_handler.rb
- we missed a blank description for this it block
> Add description for RSpec test

- app/services/audit_results.rb
- spec/services/audit_results_spec.rb
please merge before #643 and #657 is merged.
This adds the druid to the `to_json` method
https://github.com/sul-dlss/preservation_catalog/pull/643#pullrequestreview-109546060
connects #656
> include druid w/ to_json method

- spec/controllers/catalog_controller_spec.rb
- add a test for the druid
- and fix tests for create controller
> Fix RSpec tests for catalog controller

- .rubocop.yml
- app/controllers/catalog_controller.rb
- config/routes.rb
- spec/controllers/catalog_controller_spec.rb
rebased off master!
What does everyone think of me changing 
https://github.com/sul-dlss/preservation_catalog/blob/8bb87b8454d8a8d4f3c9e9d9a8e1df4843e1fc47/app/controllers/catalog_controller.rb#L40-L52
to :
```
if poh.handler_results.contains_result_code?(:actual_vers_gt_db_obj)
:ok # 200
elsif poh.handler_results.contains_result_code?(:db_obj_does_not_exist)
:not_found # 404
elsif poh.handler_results.contains_result_code?(:invalid_arguments)
:not_acceptable # 406
else
:internal_server_error # 500
end
``` 
????
connects #219
>  Update route ReST call

- app/controllers/application_controller.rb
> Disable csrf

- .rubocop.yml
- app/controllers/catalog_controller.rb
- app/services/audit_results.rb
- app/services/checksum_validator.rb
- app/services/moab_validation_handler.rb
- app/services/preserved_object_handler.rb
- lib/audit/catalog_to_moab.rb
- lib/audit/checksum.rb
- spec/lib/audit/catalog_to_moab_instance_spec.rb
- spec/services/checksum_validator_spec.rb
- spec/services/preserved_object_handler_confirm_version_spec.rb
- spec/services/shared_examples_preserved_object_handler.rb
* ~~easiest version, sets INVALID_CHECKSUM_STATUS on failure, unsets it on success (but doesn't set OK_STATUS, because we don't really know it's ok)~~
* see comments below for implementation summary
* tests
connects to #655
> update pres copy status

- app/models/preserved_copy.rb
- lib/audit/checksum.rb
- spec/lib/audit/checksum_spec.rb
- spec/models/preserved_copy_spec.rb
adds a `by_druid` scope w/ tests
closes #644
> Use PC scope

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
https://github.com/sul-dlss/preservation_catalog/pull/719#pullrequestreview-117054121
> Add .split to update method and fix rspec test

- app/services/audit_results.rb
- spec/services/audit_results_spec.rb
Also provide a default for `logger_severity_level`, namely `Logger::ERROR` (the highest of the values returned).
Added one test to confirm default, others for branches of case statement.
Refactored one indirect array composition.
> Refactor big repetitive case statement

- config/deploy.rb
> Remove dup call to update shared configs before restart

- README.md
Corrected `ruby` code blocks that are actually shell commands and other markdown formatting issues.
> Update README for redis prerequisite

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/models/preserved_object.rb
- db/migrate/20180511210539_noramlize_druid_name.rb
- db/schema.rb
- spec/factories/preserved_copy.rb
- spec/factories/preserved_object.rb
- spec/models/preserved_object_spec.rb
- spec/rails_helper.rb
- spec/support/factory_bot.rb
- spec/support/job_config.rb
> Normalize prod data

- README.md
I also updated the repo description to match in github.
Came up while starting to work on DevOps docs for preservation Catalog.
> README: improve brief description

- app/jobs/plexer_job.rb
- app/models/endpoint.rb
- app/models/preserved_copy.rb
- db/migrate/20180517212635_add_delivery_class_to_endpoint.rb
- db/schema.rb
- spec/factories/endpoint.rb
- spec/factories/endpoint_type.rb
- spec/factories/preserved_copy.rb
- spec/jobs/integration_spec.rb
- spec/jobs/plexer_job_spec.rb
Initially based off John's branch, but I didn't end up using anything from it, so rebased on master.
Adds more factories.  
Closes #709
> Plexer logic and tests

- app/services/checksum_validator.rb
> checksum_validator: set check_name for AuditResults

- .rubocop.yml
- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/prod.rb
- config/deploy/stage.rb
- config/schedule.rb
Resolves #647  M2C cron
Resolves #648   C2M cron
Connects to #783   deploy only executes db commands for cap db role
> use whenever to schedule m2c and c2m cron jobs

- app/models/endpoint.rb
- app/models/endpoint_type.rb
- db/seeds.rb
- spec/models/endpoint_spec.rb
- spec/models/endpoint_type_spec.rb
- spec/services/preserved_object_handler_check_exist_spec.rb
- spec/services/preserved_object_handler_confirm_version_spec.rb
- spec/services/preserved_object_handler_create_spec.rb
- spec/services/preserved_object_handler_update_version_spec.rb
follow-on work from #759
connects to #793
closes #215
> target archive endpoints followons pt 1

- config/deploy.rb
this fix is also necessary for deploying the latest code.  Yay!
> deploy needs to seed with release_path not current_path

- app/jobs/results_recorder_job.rb
- app/jobs/s3_endpoint_delivery_job.rb
- spec/factories/preserved_copy.rb
- spec/jobs/integration_spec.rb
- spec/jobs/results_recorder_job_spec.rb
- spec/jobs/s3_endpoint_delivery_job_spec.rb
Depends on John's branch that adds the `unreplicated` status.  Will rebase after #759 is merged.
Requires #759 
Closes #711
> ResultsRecorderJob implementation

- app/jobs/plexer_job.rb
- app/jobs/results_recorder_job.rb
- app/models/endpoint.rb
- app/models/endpoint_type.rb
- app/models/preservation_policy.rb
- app/models/preserved_object.rb
- db/migrate/20180530232909_index_some_more_cols.rb
- db/schema.rb
- spec/models/endpoint_spec.rb
- spec/models/endpoint_type_spec.rb
- spec/models/preserved_object_spec.rb
> touchups to Endpoint & PreservedObject tests, some indexes, some comment touchups and other misc refinement

- .rubocop.yml
- README.md
- bin/is_it_saturday.sh
- config/schedule.rb
It turns out this cron:
```
0 5 1-7 * 6
```
runs each day numbered between 1-7 as well as on every Saturday.   So I took a kludge from the interwebs to fix it,  so we *only* run M2C and C2M on the appropriate Saturdays.
I also tweaked the README:
- added a linked TOC
- made the Headings more skimmable
- moved the seeding section down
Connects to #810
> M2C and C2M crons only run on correct Saturdays

- app/jobs/s3_east_delivery_job.rb
- app/jobs/s3_west_delivery_job.rb
- app/models/endpoint.rb
- spec/jobs/integration_spec.rb
- spec/jobs/plexer_job_spec.rb
- spec/jobs/s3_east_delivery_job_spec.rb
- spec/jobs/s3_west_delivery_job_spec.rb
- spec/models/endpoint_spec.rb
> Second S3 endpoint: us-east-1

- db/schema.rb
we never regenerated our db/schema.rb after a migration was changed from this PR
https://github.com/sul-dlss/preservation_catalog/pull/804
> Update our db/schema

- Rakefile
- lib/audit/checksum.rb
- lib/audit/moab_to_catalog.rb
> [WIP] remove double logging and add druid in message

- lib/tasks/resque.rake
Fix #842
See: https://github.com/resque/resque/issues/1265
> Make resque:setup load :environment

- Rakefile
we missed these with the changes to have the Audit module ...
> Rakefile: add Audit namespace to M2C and C2M rake tasks

- spec/fixtures/aws_credentials
- spec/lib/preservation_catalog/s3_spec.rb
through the AWS_PROFILE env var
Fixes #847
> Add test to show sdk picking up credentials from files

- app/models/endpoint.rb
- config/settings/development.yml
- config/settings/test.yml
- spec/models/endpoint_spec.rb
update specs, update dev and test configs.
connects to #877
> Endpoint.seed_archive_endpoints_from_config should set delivery class

- app/models/preserved_copy.rb
- spec/models/preserved_copy_spec.rb
This is both a convenience method (all a caller has to know about is the PC) and the decision point for whether to put the object into the existing pipeline. Subsequently this would be where logic to reroute to a different pipeline ties in.
This is just a *part* of the overall strategy for large objects, but we can establish this piece independently.
> Add `PreservedCopy#replicate!` with tests

- config/initializers/okcomputer.rb
check whether queues are backed up
and for failed jobs
> Monitor resque

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
so that a deployment will set up the workers
> Set up capistrano integration for resque-pool

- config/initializers/okcomputer.rb
- config/initializers/resque.rb
- Configure Resque to have a separate error queue per job queue
- Check whether Resque itself is down
- Check job failures per error queue
> Resque backend

- app/models/archive_endpoint.rb
- app/models/archive_preserved_copy.rb
- app/models/archive_preserved_copy_part.rb
- app/models/endpoint.rb
- app/models/preservation_policy.rb
- db/migrate/20180626221500_create_archive_endpoints.rb
- db/migrate/20180626221547_create_archive_preserved_copies.rb
- db/migrate/20180626222814_create_archive_preserved_copy_parts.rb
- db/migrate/20180628222502_create_archive_endpoints_preservation_policies.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/archive_endpoints.rb
- spec/factories/archive_preserved_copies.rb
- spec/factories/archive_preserved_copy_parts.rb
- spec/factories/endpoint.rb
- spec/factories/preserved_copy.rb
- spec/jobs/integration_spec.rb
- spec/jobs/plexer_job_spec.rb
- spec/jobs/replicated_file_check_job_spec.rb
- spec/jobs/results_recorder_job_spec.rb
- spec/models/archive_endpoint_spec.rb
- spec/models/archive_preserved_copy_part_spec.rb
- spec/models/archive_preserved_copy_spec.rb
- spec/models/endpoint_spec.rb
- spec/models/preserved_object_spec.rb
- spec/services/preserved_object_handler_spec.rb
at least still need to write tests.  TBD how much refactoring of existing code will fall under this PR.
> Archive pres copies - introduction

- db/migrate/20180702212656_add_status_to_archive_preserved_copy.rb
- db/schema.rb
Adding tests via #944, putting schema change up for now
> ArchivePreservedCopy Status Enum needs to have an integer not string.

- .rubocop.yml
- app/jobs/replicated_file_check_job.rb
- app/models/preserved_object.rb
- spec/jobs/replicated_file_check_job_spec.rb
Add some logging if archival pres copy has a status of unreplicated, if the checksums mismatch, and if the archival pres copy does not exist on s3.
> C2a logging

- spec/models/archive_preserved_copy_spec.rb
> ArchivePreservedCopy Model Rspec tests

- app/lib/audit/catalog_to_moab.rb
- app/lib/audit/checksum.rb
- app/lib/audit/moab_to_catalog.rb
- spec/lib/audit/catalog_to_moab_class_spec.rb
- spec/lib/audit/checksum_spec.rb
- spec/lib/audit/moab_to_catalog_spec.rb
> Send audit check output to separate logs

- .rubocop.yml
- app/jobs/plexer_job.rb
- app/jobs/replicated_file_check_job.rb
- app/jobs/results_recorder_job.rb
- app/models/archive_preserved_copy.rb
- app/models/archive_preserved_copy_part.rb
- app/models/preservation_policy.rb
- app/models/preserved_copy.rb
- app/models/preserved_object.rb
- app/models/zip_endpoint.rb
- config/initializers/okcomputer.rb
- config/resque-pool.yml
- config/settings/development.yml
- config/settings/test.yml
- db/migrate/20180712203748_rename_archive_endpoint_to_zip_endpoint.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/archive_preserved_copies.rb
- spec/factories/zip_endpoints.rb
- spec/jobs/integration_spec.rb
- spec/jobs/plexer_job_spec.rb
- spec/jobs/results_recorder_job_spec.rb
- spec/models/archive_preserved_copy_spec.rb
- spec/models/endpoint_spec.rb
- spec/models/preserved_copy_spec.rb
- spec/models/zip_endpoint_spec.rb
I can squash all of the commits if needed but 
First Commit: Migration and schema change
Second Commit: renames in app/ dir
Third Commit: renames in spec/ dir
Fourth Commit: renames in config/ and seeds
closes #975 
Edit need shared_config reviewed too:
https://github.com/sul-dlss/shared_configs/pull/620
https://github.com/sul-dlss/shared_configs/pull/621
> Rename Archive Endpoint to Zip endpoint

- app/jobs/plexer_job.rb
> created helper method for metadata arguments

- app/jobs/plexer_job.rb
- app/jobs/results_recorder_job.rb
- app/models/archive_preserved_copy.rb
- app/models/zip_part.rb
- db/migrate/20180712213532_change_archive_preserved_copy_parts_to_zip_parts.rb
- db/schema.rb
- spec/factories/zip_parts.rb
- spec/jobs/plexer_job_spec.rb
- spec/jobs/results_recorder_job_spec.rb
- spec/models/archive_preserved_copy_spec.rb
- spec/models/zip_part_spec.rb
> Change ArchivePreservedCopyPart to ZipPart

- app/jobs/plexer_job.rb
- app/jobs/replicated_file_check_job.rb
- app/jobs/results_recorder_job.rb
- app/models/preserved_copy.rb
- app/models/zip_endpoint.rb
- app/models/zip_part.rb
- app/models/zipped_moab_version.rb
- db/migrate/20180718223251_change_archive_preserved_copies_to_zipped_moab_versions.rb
- db/schema.rb
- spec/factories/zip_parts.rb
- spec/factories/zipped_moab_versions.rb
- spec/jobs/integration_spec.rb
- spec/jobs/plexer_job_spec.rb
- spec/jobs/results_recorder_job_spec.rb
- spec/models/preserved_copy_spec.rb
- spec/models/zip_endpoint_spec.rb
- spec/models/zip_part_spec.rb
- spec/models/zipped_moab_version_spec.rb
> Rename ArchivePreservedCopy to ZippedMoabVersion

- app/jobs/plexer_job.rb
>  revert metadata_arg method

- spec/models/preserved_copy_spec.rb
> Var change archive to zip

- app/lib/audit/catalog_to_moab.rb
- app/models/preserved_copy.rb
- app/services/checksum_validator.rb
- app/services/moab_validation_handler.rb
- app/services/preserved_object_handler.rb
- db/README.md
- spec/controllers/catalog_controller_spec.rb
- spec/lib/active_record_utils_spec.rb
- spec/lib/audit/catalog_to_moab_instance_spec.rb
- spec/lib/audit/moab_to_catalog_spec.rb
- spec/load_fixtures_helper.rb
- spec/models/preserved_copy_spec.rb
- spec/services/audit_results_spec.rb
- spec/services/checksum_validator_spec.rb
- spec/services/preserved_object_handler_check_exist_spec.rb
- spec/services/preserved_object_handler_confirm_version_spec.rb
- spec/services/preserved_object_handler_create_spec.rb
- spec/services/preserved_object_handler_spec.rb
- spec/services/preserved_object_handler_update_version_spec.rb
- spec/services/shared_examples_preserved_object_handler.rb
Rebased/repointed at master, now independent of #1018
> Purge constants

- .rspec
> Run tests in random order

- app/models/complete_moab.rb
- app/models/preserved_object.rb
- db/README.md
- spec/jobs/replicated_file_check_job_spec.rb
As recorded in comments for https://github.com/sul-dlss/preservation_catalog/pull/1022
> Rename a few stray PCs to CM

- spec/factories/preservation_policy.rb
- spec/models/zip_endpoint_spec.rb
Fixes #984 
Introduces a factory and uses it where we create a pres policy in our tests, which is in one place, AFAICT
> Pres policy factory

- app/jobs/s3_west_delivery_job.rb
- spec/jobs/integration_spec.rb
- spec/jobs/s3_west_delivery_job_spec.rb
- spec/lib/preservation_catalog/s3_spec.rb
> Upload file not put

- Gemfile
- Gemfile.lock
> Remove new_relic due to deadlocking conflict with resque

- config/deploy.rb
- config/deploy/prod.rb
remove redundant role
and unused linked_file
> Deploy to 2nd worker machine

- spec/models/zipped_moab_version_spec.rb
> RSpec test for ZippedMoabVersion.by_druid(druid)

- .travis.yml
remove outdated build versions
> Add build for ruby-2.5.1

- app/jobs/s3_west_delivery_job.rb
- app/models/druid_version_zip.rb
- app/models/druid_version_zip_part.rb
- spec/fixtures/zip_storage/bj/102/hs/9687/bj102hs9687.v0001.zip.md5
- spec/jobs/s3_west_delivery_job_spec.rb
- spec/models/druid_version_zip_part_spec.rb
- spec/models/druid_version_zip_spec.rb
> Write md5 and read md5 before upload

- spec/models/druid_version_zip_spec.rb
> Addes rspec tests for Druid Version Zip models, closes #968

- README.md
- app/jobs/moab_to_catalog_job.rb
- app/lib/audit/moab_to_catalog.rb
- app/models/moab_storage_root.rb
- bin/is_it_saturday.sh
- config/schedule.rb
- lib/tasks/cv_tasks.rake
- lib/tasks/m2c_tasks.rake
- spec/jobs/moab_to_catalog_job_spec.rb
- spec/lib/audit/catalog_to_moab_spec.rb
- spec/lib/audit/moab_to_catalog_spec.rb
- spec/models/moab_storage_root_spec.rb
This extends #1062 for M2C, using the same approach and with the same follow-on expectations. Will rebase if that is merged.
> Convert M2C to worker queue also

- config/deploy/prod.rb
- config/schedule.rb
> Add crontab entry to delete empty dirs from zip storage

- app/jobs/moab_replication_audit_job.rb
- spec/jobs/moab_replication_audit_job_spec.rb
> MoabReplicationAuditJob updates archive timestamp

- app/jobs/s3_west_delivery_job.rb
- spec/jobs/s3_west_delivery_job_spec.rb
As the comment documents:
```
note: base class gives us `zip`, `dvz_part`
```
So we should use them rather than our own `DruidVersionZip.new`, etc.
Do the `exists?` check **before** computing a checksum that we might just do nothing with anyway.  
Also clarify test language and structure, matching new error message, and remove duplicative `let` statement.
> Don't recreate what Base class already provides

- app/services/audit_results.rb
> Add honey badger notifications

- app/services/checksum_validator.rb
- config/initializers/moab_verification_result_monkeypatch.rb
- Reduction of unnecessary constants.
- Minor reduction of shame.
- Intermediate hashes removed
- YARD docs
> CV retouches

- Gemfile
- Gemfile.lock
- app/services/workflow_reporter.rb
- config/initializers/dor_workflow_service.rb
- spec/controllers/catalog_controller_spec.rb
- spec/lib/audit/catalog_to_moab_spec.rb
- spec/lib/audit/checksum_spec.rb
- spec/lib/audit/moab_to_catalog_spec.rb
- spec/services/audit_results_spec.rb
- spec/services/checksum_validator_spec.rb
- spec/services/preserved_object_handler_check_exist_spec.rb
- spec/services/preserved_object_handler_confirm_version_spec.rb
- spec/services/preserved_object_handler_create_spec.rb
- spec/services/preserved_object_handler_spec.rb
- spec/services/preserved_object_handler_update_version_spec.rb
- spec/services/workflow_reporter_spec.rb
The older version was previously called dor-workflow-service
Fixes #1169
> Upgrade dor-workflow-client

- app/controllers/objects_controller.rb
- config/routes.rb
- spec/requests/objects_controller_checksums_spec.rb
fixes #1212 
Note: after merge and deploy, move onto sul-dlss/argo#1642
> allow multi druid endpoint to accept either get or post

- README.md
closes #1243
Provide documentation for the Pres Cat API.
Yup.
> Added API docs to README.

- app/controllers/application_controller.rb
- spec/requests/auth_spec.rb
we are currently being rate limited by honeybadger, and so it's useful to have the same info in the logs, in case HB doesn't capture all the notifications we'd otherwise see.
N/A
connects to sul-dlss/argo#1777 (may assist in debugging it)
> ApplicatonController: Honeybadger notifications should get logged too

- app/controllers/objects_controller.rb
- spec/requests/objects_controller_checksums_spec.rb
Part of https://github.com/sul-dlss/argo/issues/1776 - checksum report problems.
To provide a better user experience for errors when a moab exists but didn't cleanly execute the methods to get checksums for a report. 
The checksum report log now has useful information in cases like this:
```
2020-01-28 23:37:18 UTC Starting ChecksumReportJob for BulkAction 366
2020-01-28 23:37:57 UTC ChecksumReportJob got error from Preservation Catalog API (Preservation::Client::UnexpectedResponseError): Preservation::Client.http_response got 409 from Preservation at v1/objects/checksums: 409 conflict - problems processing mr240yx9239
2020-01-28 23:37:57 UTC Finished ChecksumReportJob for BulkAction 366
```
here are the sorts of errors we are avoiding now:
n/a
> checksums API call traps for StandardError and returns 409 and druids

- app/controllers/objects_controller.rb
- spec/requests/objects_controller_checksums_spec.rb
It's better for users if we return all the bad druids at once.  :-)
n/a
> checksums returns missing AND errored druids (all of 'em!)

- app/services/moab_storage_root_reporter.rb
> comment fixes from #1373

- .github/ISSUE_TEMPLATE/storage-migration-checklist.md
Addresses suggestions / comments from PR #1384
Also set it up for github to create the title of the new issue.
Connected to #1378
n/a
> tweak storage-migration-checklist per feedback

- app/services/workflow_reporter.rb
> Namespace druid for events_client

- .github/ISSUE_TEMPLATE/storage-migration-checklist.md
- lib/tasks/prescat.rake
These are all mistakes and concerns I noticed while doing a trial run through the storage-migration checklist.
Closes #1332
Part of #1354
the checklist template was updated.
> Checklist tweaks

- .github/ISSUE_TEMPLATE/storage-migration-checklist.md
just noticed one typo that got missed in #1403
doc only update
> small typo

- openapi.yml
Fixes #1421
This fixes a bug in the stage environment that we would likely also see in prod.
Yes
Yes, will test on stage.
> Allow version query arg to be nullable

- .github/ISSUE_TEMPLATE/storage-migration-checklist.md
clarifications and small fixes based on the checklist runthrough captured here:  https://github.com/sul-dlss/preservation_catalog/issues/1420
feedback adapted from https://github.com/sul-dlss/preservation_catalog/issues/1377#issuecomment-594945208
An attempt to make the checklist more usable and more accurate based on feedback from a dry run using it on stage.
yes
n/a
closes #1377
> tweaks based on feedback from #1420

- .github/ISSUE_TEMPLATE/storage-migration-checklist.md
clarification from question raised in https://github.com/sul-dlss/preservation_catalog/pull/1438
docs only update
n/a
> add advice about shared_configs PR review (or lack thereof)

- config/initializers/okcomputer.rb
Because hot_swap for resque workers can temporarily allow extra workers, most often due to long running jobs.
This change does imply we won't get nagios failures if prescat Resque has dead workers ... how often does that happen?
na
only in that fewer spurious nagios alerts are likely to be raised.
> tweak okcomputer check for number of workers

- app/services/complete_moab_handler.rb
- spec/services/complete_moab_handler_check_exist_spec.rb
- spec/services/complete_moab_handler_update_version_spec.rb
> Renamed #comp_moab to #complete_moab

- Gemfile
- Gemfile.lock
Updates to dor-services-client 6.
No.
Not yet.
> Updates to dor-services-client 6.0

- app/models/moab_storage_root.rb
- db/migrate/20200504194352_add_index_unique_constraint_to_moab_storage_roots.rb
- db/schema.rb
- spec/models/moab_storage_root_spec.rb
> Unique constraint for MoabStorageRoot's storage_root

- app/models/druid_version_zip.rb
- spec/models/druid_version_zip_spec.rb
Fixes #1302
To satisfy the feature request in #1302.
Unit tests.
None.
> Raise an error if the zip file(s) are smaller than the Moab version size on disk

- spec/lib/preservation_catalog/aws_provider_spec.rb
- spec/lib/preservation_catalog/ibm_provider_spec.rb
- spec/lib/preservation_catalog/shared_examples_provider.rb
closes #1561
Refactor duplicate testing code.
NA
No
> Refactors provider spec.

- README.md
- app/lib/active_record_utils.rb
- app/lib/audit/checksum.rb
- spec/lib/active_record_utils_spec.rb
- spec/lib/audit/checksum_spec.rb
- spec/lib/preservation_catalog/shared_examples_provider.rb
- spec/spec_helper.rb
- spec/support/live_s3.rb
address the "general cruft removal" suggestion in #1487, and a bit of follow on from the #1564 consolidation.
unit tests
small update to main README
> Simplifications

- config/settings.yml
settings cruft cleanup.  see https://github.com/sul-dlss/preservation_catalog/pull/1565 and https://github.com/sul-dlss/preservation_catalog/issues/1487
grepped for usage and found none.  also, unit tests.
n/a, i believe
> clean up settings cruft

- .rubocop.yml
- .rubocop_todo.yml
- app/services/audit_results.rb
- app/services/checksum_validator.rb
- spec/controllers/catalog_controller_spec.rb
- spec/jobs/moab_replication_audit_job_spec.rb
Restoring this choice we made: https://github.com/sul-dlss/preservation_catalog/blob/50bb119490a0a302bae0e8e38900fb2928077c5f/.rubocop.yml#L36-L38
Test suite
n/a
> Set a reasonable line length

- app/models/preserved_objects_primary_moab.rb
- spec/models/preserved_objects_primary_moab_spec.rb
Fixes #1601
Added unit test to suite
n/a
> PreservedObjectPrimaryMoab custom validation

- app/jobs/zipmaker_job.rb
- config/settings.yml
by eliminating the random stagging.
also, better name for the config section, not copypasta'ed from pres robots.
unit tests, will also run infra integration test for creating and versioning an object in stage
base settings.yml, and comments by relevant source code
> simplify the delay mechanism for ZipmakerJob

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/storage-migration-checklist-short.md
- README.md
- config/deploy.rb
- db/README.md
- docs/index.html
New policy for DLSS to rename `master` branch as `main` branch.
Testing suite
See PR file list
> Updates master with main branch

- app/services/checksum_validator.rb
- spec/services/checksum_validator_spec.rb
To improve code clarity
Unit tests, global search showed they were unit tests
> checksum_validator: make private methods ... private

- spec/services/checksum_validator_spec.rb
> checksum_validator_spec: fix typos

- .rubocop.yml
> add new cops to rubocop.yml

- .rubocop.yml
- app/controllers/objects_controller.rb
- openapi.yml
- spec/requests/objects_controller_checksums_spec.rb
small follow on to #1738 implementing the changes i'd requested, plus bonus rubocop touchup (added the new rules that didn't necessitate any other changes)
CI
openapi definition
> Checksum report error handling touchup

- db/README.md
i found this useful when looking for test cases on stage for https://github.com/sul-dlss/preservation_catalog/pull/1750
it should be useful for auditing the catalog in the future.
i spot checked a number of druids the query returned on stage, confirming that they in fact had no zip parts for the versions returned by this query.
documentation only change
> add orphaned ZMV query to db README

- Gemfile
- Gemfile.lock
> simplecov recent version works with codeclimate

- .circleci/config.yml
- Gemfile
- Gemfile.lock
> Updating to Ruby 3.0.3.

- .circleci/config.yml
- Gemfile
- Gemfile.lock
> Switched to sul-dlss/ruby-rails for circleci config.

- config/initializers/okcomputer.rb
Because they do not mount that directory, which leads to a required status check failing when actually all is well.
> Do not register the zips dir OKComputer check on 01 boxes

- config/initializers/okcomputer.rb
when deploying to stage to test load balancing of pres cat (see e.g. #1795), we were seeing errors like the following in the apache logs:
```
App 658587 output: Error: The application encountered the following error: No matching check (OkComputer::Registry::CheckNotFound)
```
we'll deploy to stage and test
ok computer config
> fixup okcomputer check for zip temp space

- config/deploy/migrate.rb
- config/deploy/prod.rb
To load-balance the prescat API
In stage
DevOpsDocs PR forthcoming
> Deploy prescat-prod to load-balancer

- .circleci/config.yml
get to the latest orb version.
> Update the ruby-rails orb to 3.0.1

- app/jobs/application_job.rb
- app/jobs/concerns/unique_job.rb
This keeps all the locking code together.  This refactor is in preparation for #1899
Test suite.
> Extract locking code to a new module

- .gitignore
- app/jobs/concerns/unique_job.rb
- config/initializers/resque.rb
- config/resque.yml
- spec/spec_helper.rb
Fixes #1882
Ran https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb
> Decouple the redis useage in the lock from Resque

- app/models/audit_results.rb
> Use match? instead of present?

- app/jobs/concerns/unique_job.rb
Add a @note indicating the motivation for de-deuplication when a caller tries to enqueue a job.
Also, small touchups to class comment formatting and removal of a duplicative/copypasta comment.
closes #1898
comment change only
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication …
> document the motivation for UniqueJob's locking mechanism

- README.md
the top level README was really long.  I moved the information about running audits, and the information abou moving moabs to the wiki.   
I put links in the readme on where to find the info about running audit code (and basic info about audit code).
Since moving moabs is very rare, I didn't keep a link in the README.
from wiki pages sidebar:
Fixes #2125
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are …
> README shrunk; content moved to wiki

- app/services/dashboard/audit_service.rb
> Moab audits older

- app/services/dashboard/moab_on_storage_service.rb
refs #2084
Faster dashboard
Rails console / db
> Speed up generation of storage root info.

- app/services/audit/replication_support.rb
- lib/tasks/prescat.rake
> Add rake tasks to support replication fixes.

- app/jobs/replication/results_recorder_job.rb
refs #2181
Get rid of `before_perform` (on the theory that if there was a problem during before_perform, it might not be handled correctly).
Unit, stage.
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation_**, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication …
> Refactor ResultsRecorderJob to git rid of before_perform.

- .rubocop.yml
- spec/models/replication/druid_version_zip_part_spec.rb
- spec/services/audit/shared_examples_replication_to_endpoint.rb
- spec/services/dashboard/replication_service_spec.rb
- spec/services/moab_record_service/update_version_spec.rb
Enable new cops and autocorrect errors.
> Enable new cops and fix linting errors

- README.md
hadn't yet figured this out at [the time we executed the stage reset](https://github.com/sul-dlss/argo/issues/4052#issuecomment-1746350879), so documenting what i ended up arriving at when i finally did this last friday.
this is documentation of the successfully run procedure for stage/QA cloud content purge
N/A
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) for more detail. ⚡
> fix up reset instructions to include detail on purging cloud content

- Dockerfile
- Gemfile.lock
- docker-compose.yml
Use debian-based image for`ffi` dependency.
Local build
> Update docker-compose and Dockerfile

- .circleci/config.yml
Restore DLSS context in CI configs which handling secrets easier.
CI
> Add DLSS CI context back to Circle config

- .circleci/config.yml
- .rubocop.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- config/initializers/resolv_replace.rb
Keep pace with Ruby upgrades
CI, stage
> Bump Ruby to 3.4.1

- app/models/zip_endpoint.rb
- spec/models/zip_endpoint_spec.rb
when partial settings are provided such that an endpoint entry can't be created, warn and skip, so that deployment can continue.  this allows, for example, setting up config gem env vars that provide access credentials, before the shared_configs override containing the rest of the settings is in place.  this also keeps us from missing the inadvertent omission of a new endpoint if partial information was configured in error.
see e.g. https://app.honeybadger.io/projects/54415/faults/119965876 (in which deployment failed, since the `seed` task failed).
⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_reaccessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/fe …
> zip endpoint config seeding: tolerate incomplete configuration of new endpoints
